// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccessCache is an autogenerated mock type for the AccessCache type
type AccessCache struct {
	mock.Mock
}

type AccessCache_Expecter struct {
	mock *mock.Mock
}

func (_m *AccessCache) EXPECT() *AccessCache_Expecter {
	return &AccessCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, playlistID
func (_m *AccessCache) Delete(ctx context.Context, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccessCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AccessCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *AccessCache_Expecter) Delete(ctx interface{}, playlistID interface{}) *AccessCache_Delete_Call {
	return &AccessCache_Delete_Call{Call: _e.mock.On("Delete", ctx, playlistID)}
}

func (_c *AccessCache_Delete_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *AccessCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AccessCache_Delete_Call) Return(_a0 error) *AccessCache_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccessCache_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *AccessCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, playlistID
func (_m *AccessCache) Get(ctx context.Context, playlistID uuid.UUID) (*entity.PlaylistAccessMeta, error) {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.PlaylistAccessMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.PlaylistAccessMeta, error)); ok {
		return rf(ctx, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.PlaylistAccessMeta); ok {
		r0 = rf(ctx, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlaylistAccessMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccessCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type AccessCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *AccessCache_Expecter) Get(ctx interface{}, playlistID interface{}) *AccessCache_Get_Call {
	return &AccessCache_Get_Call{Call: _e.mock.On("Get", ctx, playlistID)}
}

func (_c *AccessCache_Get_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *AccessCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AccessCache_Get_Call) Return(_a0 *entity.PlaylistAccessMeta, _a1 error) *AccessCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccessCache_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.PlaylistAccessMeta, error)) *AccessCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, playlistID, meta
func (_m *AccessCache) Set(ctx context.Context, playlistID uuid.UUID, meta *entity.PlaylistAccessMeta) error {
	ret := _m.Called(ctx, playlistID, meta)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.PlaylistAccessMeta) error); ok {
		r0 = rf(ctx, playlistID, meta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccessCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type AccessCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
//   - meta *entity.PlaylistAccessMeta
func (_e *AccessCache_Expecter) Set(ctx interface{}, playlistID interface{}, meta interface{}) *AccessCache_Set_Call {
	return &AccessCache_Set_Call{Call: _e.mock.On("Set", ctx, playlistID, meta)}
}

func (_c *AccessCache_Set_Call) Run(run func(ctx context.Context, playlistID uuid.UUID, meta *entity.PlaylistAccessMeta)) *AccessCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.PlaylistAccessMeta))
	})
	return _c
}

func (_c *AccessCache_Set_Call) Return(_a0 error) *AccessCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccessCache_Set_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.PlaylistAccessMeta) error) *AccessCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccessCache creates a new instance of AccessCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccessCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccessCache {
	mock := &AccessCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
