// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AlbumService is an autogenerated mock type for the AlbumService type
type AlbumService struct {
	mock.Mock
}

type AlbumService_Expecter struct {
	mock *mock.Mock
}

func (_m *AlbumService) EXPECT() *AlbumService_Expecter {
	return &AlbumService_Expecter{mock: &_m.Mock}
}

// CreateAlbum provides a mock function with given fields: ctx, claims, _a2
func (_m *AlbumService) CreateAlbum(ctx context.Context, claims *entity.Claims, _a2 *entity.AlbumMeta) error {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.AlbumMeta) error); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumService_CreateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAlbum'
type AlbumService_CreateAlbum_Call struct {
	*mock.Call
}

// CreateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.AlbumMeta
func (_e *AlbumService_Expecter) CreateAlbum(ctx interface{}, claims interface{}, _a2 interface{}) *AlbumService_CreateAlbum_Call {
	return &AlbumService_CreateAlbum_Call{Call: _e.mock.On("CreateAlbum", ctx, claims, _a2)}
}

func (_c *AlbumService_CreateAlbum_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.AlbumMeta)) *AlbumService_CreateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.AlbumMeta))
	})
	return _c
}

func (_c *AlbumService_CreateAlbum_Call) Return(_a0 error) *AlbumService_CreateAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumService_CreateAlbum_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.AlbumMeta) error) *AlbumService_CreateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAlbum provides a mock function with given fields: ctx, claims, albumID
func (_m *AlbumService) DeleteAlbum(ctx context.Context, claims *entity.Claims, albumID uuid.UUID) error {
	ret := _m.Called(ctx, claims, albumID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumService_DeleteAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlbum'
type AlbumService_DeleteAlbum_Call struct {
	*mock.Call
}

// DeleteAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - albumID uuid.UUID
func (_e *AlbumService_Expecter) DeleteAlbum(ctx interface{}, claims interface{}, albumID interface{}) *AlbumService_DeleteAlbum_Call {
	return &AlbumService_DeleteAlbum_Call{Call: _e.mock.On("DeleteAlbum", ctx, claims, albumID)}
}

func (_c *AlbumService_DeleteAlbum_Call) Run(run func(ctx context.Context, claims *entity.Claims, albumID uuid.UUID)) *AlbumService_DeleteAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumService_DeleteAlbum_Call) Return(_a0 error) *AlbumService_DeleteAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumService_DeleteAlbum_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *AlbumService_DeleteAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbum provides a mock function with given fields: ctx, albumID
func (_m *AlbumService) GetAlbum(ctx context.Context, albumID uuid.UUID) (*entity.AlbumMeta, error) {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbum")
	}

	var r0 *entity.AlbumMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.AlbumMeta, error)); ok {
		return rf(ctx, albumID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.AlbumMeta); ok {
		r0 = rf(ctx, albumID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AlbumMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, albumID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlbumService_GetAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbum'
type AlbumService_GetAlbum_Call struct {
	*mock.Call
}

// GetAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID uuid.UUID
func (_e *AlbumService_Expecter) GetAlbum(ctx interface{}, albumID interface{}) *AlbumService_GetAlbum_Call {
	return &AlbumService_GetAlbum_Call{Call: _e.mock.On("GetAlbum", ctx, albumID)}
}

func (_c *AlbumService_GetAlbum_Call) Run(run func(ctx context.Context, albumID uuid.UUID)) *AlbumService_GetAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumService_GetAlbum_Call) Return(_a0 *entity.AlbumMeta, _a1 error) *AlbumService_GetAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlbumService_GetAlbum_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.AlbumMeta, error)) *AlbumService_GetAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAlbums provides a mock function with given fields: ctx
func (_m *AlbumService) GetAllAlbums(ctx context.Context) ([]*entity.AlbumMeta, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAlbums")
	}

	var r0 []*entity.AlbumMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.AlbumMeta, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.AlbumMeta); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AlbumMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlbumService_GetAllAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAlbums'
type AlbumService_GetAllAlbums_Call struct {
	*mock.Call
}

// GetAllAlbums is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AlbumService_Expecter) GetAllAlbums(ctx interface{}) *AlbumService_GetAllAlbums_Call {
	return &AlbumService_GetAllAlbums_Call{Call: _e.mock.On("GetAllAlbums", ctx)}
}

func (_c *AlbumService_GetAllAlbums_Call) Run(run func(ctx context.Context)) *AlbumService_GetAllAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AlbumService_GetAllAlbums_Call) Return(_a0 []*entity.AlbumMeta, _a1 error) *AlbumService_GetAllAlbums_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlbumService_GetAllAlbums_Call) RunAndReturn(run func(context.Context) ([]*entity.AlbumMeta, error)) *AlbumService_GetAllAlbums_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAlbum provides a mock function with given fields: ctx, claims, _a2
func (_m *AlbumService) UpdateAlbum(ctx context.Context, claims *entity.Claims, _a2 *entity.AlbumMeta) error {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.AlbumMeta) error); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumService_UpdateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAlbum'
type AlbumService_UpdateAlbum_Call struct {
	*mock.Call
}

// UpdateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.AlbumMeta
func (_e *AlbumService_Expecter) UpdateAlbum(ctx interface{}, claims interface{}, _a2 interface{}) *AlbumService_UpdateAlbum_Call {
	return &AlbumService_UpdateAlbum_Call{Call: _e.mock.On("UpdateAlbum", ctx, claims, _a2)}
}

func (_c *AlbumService_UpdateAlbum_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.AlbumMeta)) *AlbumService_UpdateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.AlbumMeta))
	})
	return _c
}

func (_c *AlbumService_UpdateAlbum_Call) Return(_a0 error) *AlbumService_UpdateAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumService_UpdateAlbum_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.AlbumMeta) error) *AlbumService_UpdateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlbumService creates a new instance of AlbumService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlbumService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlbumService {
	mock := &AlbumService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
