// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AlbumCoverRepository is an autogenerated mock type for the AlbumCoverRepository type
type AlbumCoverRepository struct {
	mock.Mock
}

type AlbumCoverRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AlbumCoverRepository) EXPECT() *AlbumCoverRepository_Expecter {
	return &AlbumCoverRepository_Expecter{mock: &_m.Mock}
}

// DeleteCover provides a mock function with given fields: ctx, albumID
func (_m *AlbumCoverRepository) DeleteCover(ctx context.Context, albumID uuid.UUID) error {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumCoverRepository_DeleteCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCover'
type AlbumCoverRepository_DeleteCover_Call struct {
	*mock.Call
}

// DeleteCover is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID uuid.UUID
func (_e *AlbumCoverRepository_Expecter) DeleteCover(ctx interface{}, albumID interface{}) *AlbumCoverRepository_DeleteCover_Call {
	return &AlbumCoverRepository_DeleteCover_Call{Call: _e.mock.On("DeleteCover", ctx, albumID)}
}

func (_c *AlbumCoverRepository_DeleteCover_Call) Run(run func(ctx context.Context, albumID uuid.UUID)) *AlbumCoverRepository_DeleteCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumCoverRepository_DeleteCover_Call) Return(_a0 error) *AlbumCoverRepository_DeleteCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumCoverRepository_DeleteCover_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *AlbumCoverRepository_DeleteCover_Call {
	_c.Call.Return(run)
	return _c
}

// GetCover provides a mock function with given fields: ctx, albumID
func (_m *AlbumCoverRepository) GetCover(ctx context.Context, albumID uuid.UUID) (*entity.Cover, error) {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for GetCover")
	}

	var r0 *entity.Cover
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Cover, error)); ok {
		return rf(ctx, albumID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Cover); ok {
		r0 = rf(ctx, albumID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cover)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, albumID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlbumCoverRepository_GetCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCover'
type AlbumCoverRepository_GetCover_Call struct {
	*mock.Call
}

// GetCover is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID uuid.UUID
func (_e *AlbumCoverRepository_Expecter) GetCover(ctx interface{}, albumID interface{}) *AlbumCoverRepository_GetCover_Call {
	return &AlbumCoverRepository_GetCover_Call{Call: _e.mock.On("GetCover", ctx, albumID)}
}

func (_c *AlbumCoverRepository_GetCover_Call) Run(run func(ctx context.Context, albumID uuid.UUID)) *AlbumCoverRepository_GetCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumCoverRepository_GetCover_Call) Return(_a0 *entity.Cover, _a1 error) *AlbumCoverRepository_GetCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlbumCoverRepository_GetCover_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Cover, error)) *AlbumCoverRepository_GetCover_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCover provides a mock function with given fields: ctx, _a1
func (_m *AlbumCoverRepository) SaveCover(ctx context.Context, _a1 *entity.Cover) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Cover) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumCoverRepository_SaveCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCover'
type AlbumCoverRepository_SaveCover_Call struct {
	*mock.Call
}

// SaveCover is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Cover
func (_e *AlbumCoverRepository_Expecter) SaveCover(ctx interface{}, _a1 interface{}) *AlbumCoverRepository_SaveCover_Call {
	return &AlbumCoverRepository_SaveCover_Call{Call: _e.mock.On("SaveCover", ctx, _a1)}
}

func (_c *AlbumCoverRepository_SaveCover_Call) Run(run func(ctx context.Context, _a1 *entity.Cover)) *AlbumCoverRepository_SaveCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Cover))
	})
	return _c
}

func (_c *AlbumCoverRepository_SaveCover_Call) Return(_a0 error) *AlbumCoverRepository_SaveCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumCoverRepository_SaveCover_Call) RunAndReturn(run func(context.Context, *entity.Cover) error) *AlbumCoverRepository_SaveCover_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlbumCoverRepository creates a new instance of AlbumCoverRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlbumCoverRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlbumCoverRepository {
	mock := &AlbumCoverRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
