// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AlbumTrackService is an autogenerated mock type for the AlbumTrackService type
type AlbumTrackService struct {
	mock.Mock
}

type AlbumTrackService_Expecter struct {
	mock *mock.Mock
}

func (_m *AlbumTrackService) EXPECT() *AlbumTrackService_Expecter {
	return &AlbumTrackService_Expecter{mock: &_m.Mock}
}

// GetAllTracks provides a mock function with given fields: ctx, albumID
func (_m *AlbumTrackService) GetAllTracks(ctx context.Context, albumID uuid.UUID) ([]*entity.TrackMeta, error) {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTracks")
	}

	var r0 []*entity.TrackMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.TrackMeta, error)); ok {
		return rf(ctx, albumID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.TrackMeta); ok {
		r0 = rf(ctx, albumID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TrackMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, albumID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlbumTrackService_GetAllTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTracks'
type AlbumTrackService_GetAllTracks_Call struct {
	*mock.Call
}

// GetAllTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID uuid.UUID
func (_e *AlbumTrackService_Expecter) GetAllTracks(ctx interface{}, albumID interface{}) *AlbumTrackService_GetAllTracks_Call {
	return &AlbumTrackService_GetAllTracks_Call{Call: _e.mock.On("GetAllTracks", ctx, albumID)}
}

func (_c *AlbumTrackService_GetAllTracks_Call) Run(run func(ctx context.Context, albumID uuid.UUID)) *AlbumTrackService_GetAllTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumTrackService_GetAllTracks_Call) Return(_a0 []*entity.TrackMeta, _a1 error) *AlbumTrackService_GetAllTracks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlbumTrackService_GetAllTracks_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.TrackMeta, error)) *AlbumTrackService_GetAllTracks_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlbumTrackService creates a new instance of AlbumTrackService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlbumTrackService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlbumTrackService {
	mock := &AlbumTrackService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
