// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AlbumCoverService is an autogenerated mock type for the AlbumCoverService type
type AlbumCoverService struct {
	mock.Mock
}

type AlbumCoverService_Expecter struct {
	mock *mock.Mock
}

func (_m *AlbumCoverService) EXPECT() *AlbumCoverService_Expecter {
	return &AlbumCoverService_Expecter{mock: &_m.Mock}
}

// DeleteCover provides a mock function with given fields: ctx, claims, albumID
func (_m *AlbumCoverService) DeleteCover(ctx context.Context, claims *entity.Claims, albumID uuid.UUID) error {
	ret := _m.Called(ctx, claims, albumID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumCoverService_DeleteCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCover'
type AlbumCoverService_DeleteCover_Call struct {
	*mock.Call
}

// DeleteCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - albumID uuid.UUID
func (_e *AlbumCoverService_Expecter) DeleteCover(ctx interface{}, claims interface{}, albumID interface{}) *AlbumCoverService_DeleteCover_Call {
	return &AlbumCoverService_DeleteCover_Call{Call: _e.mock.On("DeleteCover", ctx, claims, albumID)}
}

func (_c *AlbumCoverService_DeleteCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, albumID uuid.UUID)) *AlbumCoverService_DeleteCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumCoverService_DeleteCover_Call) Return(_a0 error) *AlbumCoverService_DeleteCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumCoverService_DeleteCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *AlbumCoverService_DeleteCover_Call {
	_c.Call.Return(run)
	return _c
}

// GetCover provides a mock function with given fields: ctx, albumID
func (_m *AlbumCoverService) GetCover(ctx context.Context, albumID uuid.UUID) (*entity.Cover, error) {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for GetCover")
	}

	var r0 *entity.Cover
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Cover, error)); ok {
		return rf(ctx, albumID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Cover); ok {
		r0 = rf(ctx, albumID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cover)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, albumID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlbumCoverService_GetCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCover'
type AlbumCoverService_GetCover_Call struct {
	*mock.Call
}

// GetCover is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID uuid.UUID
func (_e *AlbumCoverService_Expecter) GetCover(ctx interface{}, albumID interface{}) *AlbumCoverService_GetCover_Call {
	return &AlbumCoverService_GetCover_Call{Call: _e.mock.On("GetCover", ctx, albumID)}
}

func (_c *AlbumCoverService_GetCover_Call) Run(run func(ctx context.Context, albumID uuid.UUID)) *AlbumCoverService_GetCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumCoverService_GetCover_Call) Return(_a0 *entity.Cover, _a1 error) *AlbumCoverService_GetCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlbumCoverService_GetCover_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Cover, error)) *AlbumCoverService_GetCover_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCover provides a mock function with given fields: ctx, claims, cover
func (_m *AlbumCoverService) UploadCover(ctx context.Context, claims *entity.Claims, cover *entity.Cover) error {
	ret := _m.Called(ctx, claims, cover)

	if len(ret) == 0 {
		panic("no return value specified for UploadCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.Cover) error); ok {
		r0 = rf(ctx, claims, cover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumCoverService_UploadCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCover'
type AlbumCoverService_UploadCover_Call struct {
	*mock.Call
}

// UploadCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - cover *entity.Cover
func (_e *AlbumCoverService_Expecter) UploadCover(ctx interface{}, claims interface{}, cover interface{}) *AlbumCoverService_UploadCover_Call {
	return &AlbumCoverService_UploadCover_Call{Call: _e.mock.On("UploadCover", ctx, claims, cover)}
}

func (_c *AlbumCoverService_UploadCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, cover *entity.Cover)) *AlbumCoverService_UploadCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.Cover))
	})
	return _c
}

func (_c *AlbumCoverService_UploadCover_Call) Return(_a0 error) *AlbumCoverService_UploadCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumCoverService_UploadCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.Cover) error) *AlbumCoverService_UploadCover_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlbumCoverService creates a new instance of AlbumCoverService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlbumCoverService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlbumCoverService {
	mock := &AlbumCoverService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
