// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AlbumRepository is an autogenerated mock type for the AlbumRepository type
type AlbumRepository struct {
	mock.Mock
}

type AlbumRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AlbumRepository) EXPECT() *AlbumRepository_Expecter {
	return &AlbumRepository_Expecter{mock: &_m.Mock}
}

// CreateAlbum provides a mock function with given fields: ctx, album
func (_m *AlbumRepository) CreateAlbum(ctx context.Context, album *entity.AlbumMeta) error {
	ret := _m.Called(ctx, album)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AlbumMeta) error); ok {
		r0 = rf(ctx, album)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumRepository_CreateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAlbum'
type AlbumRepository_CreateAlbum_Call struct {
	*mock.Call
}

// CreateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - album *entity.AlbumMeta
func (_e *AlbumRepository_Expecter) CreateAlbum(ctx interface{}, album interface{}) *AlbumRepository_CreateAlbum_Call {
	return &AlbumRepository_CreateAlbum_Call{Call: _e.mock.On("CreateAlbum", ctx, album)}
}

func (_c *AlbumRepository_CreateAlbum_Call) Run(run func(ctx context.Context, album *entity.AlbumMeta)) *AlbumRepository_CreateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AlbumMeta))
	})
	return _c
}

func (_c *AlbumRepository_CreateAlbum_Call) Return(_a0 error) *AlbumRepository_CreateAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumRepository_CreateAlbum_Call) RunAndReturn(run func(context.Context, *entity.AlbumMeta) error) *AlbumRepository_CreateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAlbum provides a mock function with given fields: ctx, id
func (_m *AlbumRepository) DeleteAlbum(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumRepository_DeleteAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlbum'
type AlbumRepository_DeleteAlbum_Call struct {
	*mock.Call
}

// DeleteAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AlbumRepository_Expecter) DeleteAlbum(ctx interface{}, id interface{}) *AlbumRepository_DeleteAlbum_Call {
	return &AlbumRepository_DeleteAlbum_Call{Call: _e.mock.On("DeleteAlbum", ctx, id)}
}

func (_c *AlbumRepository_DeleteAlbum_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AlbumRepository_DeleteAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumRepository_DeleteAlbum_Call) Return(_a0 error) *AlbumRepository_DeleteAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumRepository_DeleteAlbum_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *AlbumRepository_DeleteAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbum provides a mock function with given fields: ctx, id
func (_m *AlbumRepository) GetAlbum(ctx context.Context, id uuid.UUID) (*entity.AlbumMeta, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbum")
	}

	var r0 *entity.AlbumMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.AlbumMeta, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.AlbumMeta); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AlbumMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlbumRepository_GetAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbum'
type AlbumRepository_GetAlbum_Call struct {
	*mock.Call
}

// GetAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AlbumRepository_Expecter) GetAlbum(ctx interface{}, id interface{}) *AlbumRepository_GetAlbum_Call {
	return &AlbumRepository_GetAlbum_Call{Call: _e.mock.On("GetAlbum", ctx, id)}
}

func (_c *AlbumRepository_GetAlbum_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AlbumRepository_GetAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumRepository_GetAlbum_Call) Return(_a0 *entity.AlbumMeta, _a1 error) *AlbumRepository_GetAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlbumRepository_GetAlbum_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.AlbumMeta, error)) *AlbumRepository_GetAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumArtists provides a mock function with given fields: ctx, albumID
func (_m *AlbumRepository) GetAlbumArtists(ctx context.Context, albumID uuid.UUID) ([]*entity.ArtistMeta, error) {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumArtists")
	}

	var r0 []*entity.ArtistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.ArtistMeta, error)); ok {
		return rf(ctx, albumID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.ArtistMeta); ok {
		r0 = rf(ctx, albumID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ArtistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, albumID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlbumRepository_GetAlbumArtists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumArtists'
type AlbumRepository_GetAlbumArtists_Call struct {
	*mock.Call
}

// GetAlbumArtists is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID uuid.UUID
func (_e *AlbumRepository_Expecter) GetAlbumArtists(ctx interface{}, albumID interface{}) *AlbumRepository_GetAlbumArtists_Call {
	return &AlbumRepository_GetAlbumArtists_Call{Call: _e.mock.On("GetAlbumArtists", ctx, albumID)}
}

func (_c *AlbumRepository_GetAlbumArtists_Call) Run(run func(ctx context.Context, albumID uuid.UUID)) *AlbumRepository_GetAlbumArtists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumRepository_GetAlbumArtists_Call) Return(_a0 []*entity.ArtistMeta, _a1 error) *AlbumRepository_GetAlbumArtists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlbumRepository_GetAlbumArtists_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.ArtistMeta, error)) *AlbumRepository_GetAlbumArtists_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumGenres provides a mock function with given fields: ctx, albumID
func (_m *AlbumRepository) GetAlbumGenres(ctx context.Context, albumID uuid.UUID) ([]*entity.Genre, error) {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumGenres")
	}

	var r0 []*entity.Genre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Genre, error)); ok {
		return rf(ctx, albumID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Genre); ok {
		r0 = rf(ctx, albumID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, albumID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlbumRepository_GetAlbumGenres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumGenres'
type AlbumRepository_GetAlbumGenres_Call struct {
	*mock.Call
}

// GetAlbumGenres is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID uuid.UUID
func (_e *AlbumRepository_Expecter) GetAlbumGenres(ctx interface{}, albumID interface{}) *AlbumRepository_GetAlbumGenres_Call {
	return &AlbumRepository_GetAlbumGenres_Call{Call: _e.mock.On("GetAlbumGenres", ctx, albumID)}
}

func (_c *AlbumRepository_GetAlbumGenres_Call) Run(run func(ctx context.Context, albumID uuid.UUID)) *AlbumRepository_GetAlbumGenres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AlbumRepository_GetAlbumGenres_Call) Return(_a0 []*entity.Genre, _a1 error) *AlbumRepository_GetAlbumGenres_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlbumRepository_GetAlbumGenres_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Genre, error)) *AlbumRepository_GetAlbumGenres_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAlbums provides a mock function with given fields: ctx
func (_m *AlbumRepository) GetAllAlbums(ctx context.Context) ([]*entity.AlbumMeta, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAlbums")
	}

	var r0 []*entity.AlbumMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.AlbumMeta, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.AlbumMeta); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AlbumMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AlbumRepository_GetAllAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAlbums'
type AlbumRepository_GetAllAlbums_Call struct {
	*mock.Call
}

// GetAllAlbums is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AlbumRepository_Expecter) GetAllAlbums(ctx interface{}) *AlbumRepository_GetAllAlbums_Call {
	return &AlbumRepository_GetAllAlbums_Call{Call: _e.mock.On("GetAllAlbums", ctx)}
}

func (_c *AlbumRepository_GetAllAlbums_Call) Run(run func(ctx context.Context)) *AlbumRepository_GetAllAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AlbumRepository_GetAllAlbums_Call) Return(_a0 []*entity.AlbumMeta, _a1 error) *AlbumRepository_GetAllAlbums_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AlbumRepository_GetAllAlbums_Call) RunAndReturn(run func(context.Context) ([]*entity.AlbumMeta, error)) *AlbumRepository_GetAllAlbums_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAlbum provides a mock function with given fields: ctx, album
func (_m *AlbumRepository) UpdateAlbum(ctx context.Context, album *entity.AlbumMeta) error {
	ret := _m.Called(ctx, album)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AlbumMeta) error); ok {
		r0 = rf(ctx, album)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumRepository_UpdateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAlbum'
type AlbumRepository_UpdateAlbum_Call struct {
	*mock.Call
}

// UpdateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - album *entity.AlbumMeta
func (_e *AlbumRepository_Expecter) UpdateAlbum(ctx interface{}, album interface{}) *AlbumRepository_UpdateAlbum_Call {
	return &AlbumRepository_UpdateAlbum_Call{Call: _e.mock.On("UpdateAlbum", ctx, album)}
}

func (_c *AlbumRepository_UpdateAlbum_Call) Run(run func(ctx context.Context, album *entity.AlbumMeta)) *AlbumRepository_UpdateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AlbumMeta))
	})
	return _c
}

func (_c *AlbumRepository_UpdateAlbum_Call) Return(_a0 error) *AlbumRepository_UpdateAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumRepository_UpdateAlbum_Call) RunAndReturn(run func(context.Context, *entity.AlbumMeta) error) *AlbumRepository_UpdateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlbumRepository creates a new instance of AlbumRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlbumRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlbumRepository {
	mock := &AlbumRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
