// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ArtistMetaService is an autogenerated mock type for the ArtistMetaService type
type ArtistMetaService struct {
	mock.Mock
}

type ArtistMetaService_Expecter struct {
	mock *mock.Mock
}

func (_m *ArtistMetaService) EXPECT() *ArtistMetaService_Expecter {
	return &ArtistMetaService_Expecter{mock: &_m.Mock}
}

// CreateArtistMeta provides a mock function with given fields: ctx, claims, _a2
func (_m *ArtistMetaService) CreateArtistMeta(ctx context.Context, claims *entity.Claims, _a2 *entity.ArtistMeta) error {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtistMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.ArtistMeta) error); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistMetaService_CreateArtistMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtistMeta'
type ArtistMetaService_CreateArtistMeta_Call struct {
	*mock.Call
}

// CreateArtistMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.ArtistMeta
func (_e *ArtistMetaService_Expecter) CreateArtistMeta(ctx interface{}, claims interface{}, _a2 interface{}) *ArtistMetaService_CreateArtistMeta_Call {
	return &ArtistMetaService_CreateArtistMeta_Call{Call: _e.mock.On("CreateArtistMeta", ctx, claims, _a2)}
}

func (_c *ArtistMetaService_CreateArtistMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.ArtistMeta)) *ArtistMetaService_CreateArtistMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.ArtistMeta))
	})
	return _c
}

func (_c *ArtistMetaService_CreateArtistMeta_Call) Return(_a0 error) *ArtistMetaService_CreateArtistMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistMetaService_CreateArtistMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.ArtistMeta) error) *ArtistMetaService_CreateArtistMeta_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteArtistMeta provides a mock function with given fields: ctx, claims, artistID
func (_m *ArtistMetaService) DeleteArtistMeta(ctx context.Context, claims *entity.Claims, artistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, artistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtistMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, artistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistMetaService_DeleteArtistMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArtistMeta'
type ArtistMetaService_DeleteArtistMeta_Call struct {
	*mock.Call
}

// DeleteArtistMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - artistID uuid.UUID
func (_e *ArtistMetaService_Expecter) DeleteArtistMeta(ctx interface{}, claims interface{}, artistID interface{}) *ArtistMetaService_DeleteArtistMeta_Call {
	return &ArtistMetaService_DeleteArtistMeta_Call{Call: _e.mock.On("DeleteArtistMeta", ctx, claims, artistID)}
}

func (_c *ArtistMetaService_DeleteArtistMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, artistID uuid.UUID)) *ArtistMetaService_DeleteArtistMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistMetaService_DeleteArtistMeta_Call) Return(_a0 error) *ArtistMetaService_DeleteArtistMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistMetaService_DeleteArtistMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *ArtistMetaService_DeleteArtistMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllArtistMeta provides a mock function with given fields: ctx
func (_m *ArtistMetaService) GetAllArtistMeta(ctx context.Context) ([]*entity.ArtistMeta, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllArtistMeta")
	}

	var r0 []*entity.ArtistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.ArtistMeta, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.ArtistMeta); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ArtistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArtistMetaService_GetAllArtistMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllArtistMeta'
type ArtistMetaService_GetAllArtistMeta_Call struct {
	*mock.Call
}

// GetAllArtistMeta is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ArtistMetaService_Expecter) GetAllArtistMeta(ctx interface{}) *ArtistMetaService_GetAllArtistMeta_Call {
	return &ArtistMetaService_GetAllArtistMeta_Call{Call: _e.mock.On("GetAllArtistMeta", ctx)}
}

func (_c *ArtistMetaService_GetAllArtistMeta_Call) Run(run func(ctx context.Context)) *ArtistMetaService_GetAllArtistMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ArtistMetaService_GetAllArtistMeta_Call) Return(_a0 []*entity.ArtistMeta, _a1 error) *ArtistMetaService_GetAllArtistMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArtistMetaService_GetAllArtistMeta_Call) RunAndReturn(run func(context.Context) ([]*entity.ArtistMeta, error)) *ArtistMetaService_GetAllArtistMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtistMeta provides a mock function with given fields: ctx, artistID
func (_m *ArtistMetaService) GetArtistMeta(ctx context.Context, artistID uuid.UUID) (*entity.ArtistMeta, error) {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for GetArtistMeta")
	}

	var r0 *entity.ArtistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.ArtistMeta, error)); ok {
		return rf(ctx, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.ArtistMeta); ok {
		r0 = rf(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ArtistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArtistMetaService_GetArtistMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtistMeta'
type ArtistMetaService_GetArtistMeta_Call struct {
	*mock.Call
}

// GetArtistMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
func (_e *ArtistMetaService_Expecter) GetArtistMeta(ctx interface{}, artistID interface{}) *ArtistMetaService_GetArtistMeta_Call {
	return &ArtistMetaService_GetArtistMeta_Call{Call: _e.mock.On("GetArtistMeta", ctx, artistID)}
}

func (_c *ArtistMetaService_GetArtistMeta_Call) Run(run func(ctx context.Context, artistID uuid.UUID)) *ArtistMetaService_GetArtistMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistMetaService_GetArtistMeta_Call) Return(_a0 *entity.ArtistMeta, _a1 error) *ArtistMetaService_GetArtistMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArtistMetaService_GetArtistMeta_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.ArtistMeta, error)) *ArtistMetaService_GetArtistMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtistMeta provides a mock function with given fields: ctx, claims, _a2
func (_m *ArtistMetaService) UpdateArtistMeta(ctx context.Context, claims *entity.Claims, _a2 *entity.ArtistMeta) error {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtistMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.ArtistMeta) error); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistMetaService_UpdateArtistMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtistMeta'
type ArtistMetaService_UpdateArtistMeta_Call struct {
	*mock.Call
}

// UpdateArtistMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.ArtistMeta
func (_e *ArtistMetaService_Expecter) UpdateArtistMeta(ctx interface{}, claims interface{}, _a2 interface{}) *ArtistMetaService_UpdateArtistMeta_Call {
	return &ArtistMetaService_UpdateArtistMeta_Call{Call: _e.mock.On("UpdateArtistMeta", ctx, claims, _a2)}
}

func (_c *ArtistMetaService_UpdateArtistMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.ArtistMeta)) *ArtistMetaService_UpdateArtistMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.ArtistMeta))
	})
	return _c
}

func (_c *ArtistMetaService_UpdateArtistMeta_Call) Return(_a0 error) *ArtistMetaService_UpdateArtistMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistMetaService_UpdateArtistMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.ArtistMeta) error) *ArtistMetaService_UpdateArtistMeta_Call {
	_c.Call.Return(run)
	return _c
}

// NewArtistMetaService creates a new instance of ArtistMetaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistMetaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistMetaService {
	mock := &ArtistMetaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
