// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ArtistAvatarService is an autogenerated mock type for the ArtistAvatarService type
type ArtistAvatarService struct {
	mock.Mock
}

type ArtistAvatarService_Expecter struct {
	mock *mock.Mock
}

func (_m *ArtistAvatarService) EXPECT() *ArtistAvatarService_Expecter {
	return &ArtistAvatarService_Expecter{mock: &_m.Mock}
}

// DeleteCover provides a mock function with given fields: ctx, claims, artistID
func (_m *ArtistAvatarService) DeleteCover(ctx context.Context, claims *entity.Claims, artistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, artistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, artistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAvatarService_DeleteCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCover'
type ArtistAvatarService_DeleteCover_Call struct {
	*mock.Call
}

// DeleteCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - artistID uuid.UUID
func (_e *ArtistAvatarService_Expecter) DeleteCover(ctx interface{}, claims interface{}, artistID interface{}) *ArtistAvatarService_DeleteCover_Call {
	return &ArtistAvatarService_DeleteCover_Call{Call: _e.mock.On("DeleteCover", ctx, claims, artistID)}
}

func (_c *ArtistAvatarService_DeleteCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, artistID uuid.UUID)) *ArtistAvatarService_DeleteCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAvatarService_DeleteCover_Call) Return(_a0 error) *ArtistAvatarService_DeleteCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAvatarService_DeleteCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *ArtistAvatarService_DeleteCover_Call {
	_c.Call.Return(run)
	return _c
}

// GetCover provides a mock function with given fields: ctx, artistID
func (_m *ArtistAvatarService) GetCover(ctx context.Context, artistID uuid.UUID) (*entity.Cover, error) {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for GetCover")
	}

	var r0 *entity.Cover
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Cover, error)); ok {
		return rf(ctx, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Cover); ok {
		r0 = rf(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cover)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArtistAvatarService_GetCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCover'
type ArtistAvatarService_GetCover_Call struct {
	*mock.Call
}

// GetCover is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
func (_e *ArtistAvatarService_Expecter) GetCover(ctx interface{}, artistID interface{}) *ArtistAvatarService_GetCover_Call {
	return &ArtistAvatarService_GetCover_Call{Call: _e.mock.On("GetCover", ctx, artistID)}
}

func (_c *ArtistAvatarService_GetCover_Call) Run(run func(ctx context.Context, artistID uuid.UUID)) *ArtistAvatarService_GetCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAvatarService_GetCover_Call) Return(_a0 *entity.Cover, _a1 error) *ArtistAvatarService_GetCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArtistAvatarService_GetCover_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Cover, error)) *ArtistAvatarService_GetCover_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCover provides a mock function with given fields: ctx, claims, cover
func (_m *ArtistAvatarService) UploadCover(ctx context.Context, claims *entity.Claims, cover *entity.Cover) error {
	ret := _m.Called(ctx, claims, cover)

	if len(ret) == 0 {
		panic("no return value specified for UploadCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.Cover) error); ok {
		r0 = rf(ctx, claims, cover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAvatarService_UploadCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCover'
type ArtistAvatarService_UploadCover_Call struct {
	*mock.Call
}

// UploadCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - cover *entity.Cover
func (_e *ArtistAvatarService_Expecter) UploadCover(ctx interface{}, claims interface{}, cover interface{}) *ArtistAvatarService_UploadCover_Call {
	return &ArtistAvatarService_UploadCover_Call{Call: _e.mock.On("UploadCover", ctx, claims, cover)}
}

func (_c *ArtistAvatarService_UploadCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, cover *entity.Cover)) *ArtistAvatarService_UploadCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.Cover))
	})
	return _c
}

func (_c *ArtistAvatarService_UploadCover_Call) Return(_a0 error) *ArtistAvatarService_UploadCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAvatarService_UploadCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.Cover) error) *ArtistAvatarService_UploadCover_Call {
	_c.Call.Return(run)
	return _c
}

// NewArtistAvatarService creates a new instance of ArtistAvatarService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistAvatarService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistAvatarService {
	mock := &ArtistAvatarService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
