// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ArtistMetaRepository is an autogenerated mock type for the ArtistMetaRepository type
type ArtistMetaRepository struct {
	mock.Mock
}

type ArtistMetaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ArtistMetaRepository) EXPECT() *ArtistMetaRepository_Expecter {
	return &ArtistMetaRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, artist
func (_m *ArtistMetaRepository) Create(ctx context.Context, artist *entity.ArtistMeta) error {
	ret := _m.Called(ctx, artist)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ArtistMeta) error); ok {
		r0 = rf(ctx, artist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistMetaRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ArtistMetaRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - artist *entity.ArtistMeta
func (_e *ArtistMetaRepository_Expecter) Create(ctx interface{}, artist interface{}) *ArtistMetaRepository_Create_Call {
	return &ArtistMetaRepository_Create_Call{Call: _e.mock.On("Create", ctx, artist)}
}

func (_c *ArtistMetaRepository_Create_Call) Run(run func(ctx context.Context, artist *entity.ArtistMeta)) *ArtistMetaRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ArtistMeta))
	})
	return _c
}

func (_c *ArtistMetaRepository_Create_Call) Return(_a0 error) *ArtistMetaRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistMetaRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.ArtistMeta) error) *ArtistMetaRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ArtistMetaRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistMetaRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ArtistMetaRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ArtistMetaRepository_Expecter) Delete(ctx interface{}, id interface{}) *ArtistMetaRepository_Delete_Call {
	return &ArtistMetaRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ArtistMetaRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ArtistMetaRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistMetaRepository_Delete_Call) Return(_a0 error) *ArtistMetaRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistMetaRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ArtistMetaRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *ArtistMetaRepository) GetAll(ctx context.Context) ([]*entity.ArtistMeta, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.ArtistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.ArtistMeta, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.ArtistMeta); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ArtistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArtistMetaRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type ArtistMetaRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ArtistMetaRepository_Expecter) GetAll(ctx interface{}) *ArtistMetaRepository_GetAll_Call {
	return &ArtistMetaRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *ArtistMetaRepository_GetAll_Call) Run(run func(ctx context.Context)) *ArtistMetaRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ArtistMetaRepository_GetAll_Call) Return(_a0 []*entity.ArtistMeta, _a1 error) *ArtistMetaRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArtistMetaRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*entity.ArtistMeta, error)) *ArtistMetaRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ArtistMetaRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.ArtistMeta, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.ArtistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.ArtistMeta, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.ArtistMeta); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ArtistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArtistMetaRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ArtistMetaRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ArtistMetaRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ArtistMetaRepository_GetByID_Call {
	return &ArtistMetaRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ArtistMetaRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ArtistMetaRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistMetaRepository_GetByID_Call) Return(_a0 *entity.ArtistMeta, _a1 error) *ArtistMetaRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArtistMetaRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.ArtistMeta, error)) *ArtistMetaRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, artist
func (_m *ArtistMetaRepository) Update(ctx context.Context, artist *entity.ArtistMeta) error {
	ret := _m.Called(ctx, artist)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ArtistMeta) error); ok {
		r0 = rf(ctx, artist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistMetaRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ArtistMetaRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - artist *entity.ArtistMeta
func (_e *ArtistMetaRepository_Expecter) Update(ctx interface{}, artist interface{}) *ArtistMetaRepository_Update_Call {
	return &ArtistMetaRepository_Update_Call{Call: _e.mock.On("Update", ctx, artist)}
}

func (_c *ArtistMetaRepository_Update_Call) Run(run func(ctx context.Context, artist *entity.ArtistMeta)) *ArtistMetaRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ArtistMeta))
	})
	return _c
}

func (_c *ArtistMetaRepository_Update_Call) Return(_a0 error) *ArtistMetaRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistMetaRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.ArtistMeta) error) *ArtistMetaRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewArtistMetaRepository creates a new instance of ArtistMetaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistMetaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistMetaRepository {
	mock := &ArtistMetaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
