// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ArtistAvatarRepository is an autogenerated mock type for the ArtistAvatarRepository type
type ArtistAvatarRepository struct {
	mock.Mock
}

type ArtistAvatarRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ArtistAvatarRepository) EXPECT() *ArtistAvatarRepository_Expecter {
	return &ArtistAvatarRepository_Expecter{mock: &_m.Mock}
}

// DeleteCover provides a mock function with given fields: ctx, artistID
func (_m *ArtistAvatarRepository) DeleteCover(ctx context.Context, artistID uuid.UUID) error {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, artistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAvatarRepository_DeleteCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCover'
type ArtistAvatarRepository_DeleteCover_Call struct {
	*mock.Call
}

// DeleteCover is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
func (_e *ArtistAvatarRepository_Expecter) DeleteCover(ctx interface{}, artistID interface{}) *ArtistAvatarRepository_DeleteCover_Call {
	return &ArtistAvatarRepository_DeleteCover_Call{Call: _e.mock.On("DeleteCover", ctx, artistID)}
}

func (_c *ArtistAvatarRepository_DeleteCover_Call) Run(run func(ctx context.Context, artistID uuid.UUID)) *ArtistAvatarRepository_DeleteCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAvatarRepository_DeleteCover_Call) Return(_a0 error) *ArtistAvatarRepository_DeleteCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAvatarRepository_DeleteCover_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ArtistAvatarRepository_DeleteCover_Call {
	_c.Call.Return(run)
	return _c
}

// GetCover provides a mock function with given fields: ctx, artistID
func (_m *ArtistAvatarRepository) GetCover(ctx context.Context, artistID uuid.UUID) (*entity.Cover, error) {
	ret := _m.Called(ctx, artistID)

	if len(ret) == 0 {
		panic("no return value specified for GetCover")
	}

	var r0 *entity.Cover
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Cover, error)); ok {
		return rf(ctx, artistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Cover); ok {
		r0 = rf(ctx, artistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cover)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, artistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ArtistAvatarRepository_GetCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCover'
type ArtistAvatarRepository_GetCover_Call struct {
	*mock.Call
}

// GetCover is a helper method to define mock.On call
//   - ctx context.Context
//   - artistID uuid.UUID
func (_e *ArtistAvatarRepository_Expecter) GetCover(ctx interface{}, artistID interface{}) *ArtistAvatarRepository_GetCover_Call {
	return &ArtistAvatarRepository_GetCover_Call{Call: _e.mock.On("GetCover", ctx, artistID)}
}

func (_c *ArtistAvatarRepository_GetCover_Call) Run(run func(ctx context.Context, artistID uuid.UUID)) *ArtistAvatarRepository_GetCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ArtistAvatarRepository_GetCover_Call) Return(_a0 *entity.Cover, _a1 error) *ArtistAvatarRepository_GetCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ArtistAvatarRepository_GetCover_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Cover, error)) *ArtistAvatarRepository_GetCover_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCover provides a mock function with given fields: ctx, cover
func (_m *ArtistAvatarRepository) SaveCover(ctx context.Context, cover *entity.Cover) error {
	ret := _m.Called(ctx, cover)

	if len(ret) == 0 {
		panic("no return value specified for SaveCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Cover) error); ok {
		r0 = rf(ctx, cover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtistAvatarRepository_SaveCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCover'
type ArtistAvatarRepository_SaveCover_Call struct {
	*mock.Call
}

// SaveCover is a helper method to define mock.On call
//   - ctx context.Context
//   - cover *entity.Cover
func (_e *ArtistAvatarRepository_Expecter) SaveCover(ctx interface{}, cover interface{}) *ArtistAvatarRepository_SaveCover_Call {
	return &ArtistAvatarRepository_SaveCover_Call{Call: _e.mock.On("SaveCover", ctx, cover)}
}

func (_c *ArtistAvatarRepository_SaveCover_Call) Run(run func(ctx context.Context, cover *entity.Cover)) *ArtistAvatarRepository_SaveCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Cover))
	})
	return _c
}

func (_c *ArtistAvatarRepository_SaveCover_Call) Return(_a0 error) *ArtistAvatarRepository_SaveCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtistAvatarRepository_SaveCover_Call) RunAndReturn(run func(context.Context, *entity.Cover) error) *ArtistAvatarRepository_SaveCover_Call {
	_c.Call.Return(run)
	return _c
}

// NewArtistAvatarRepository creates a new instance of ArtistAvatarRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtistAvatarRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtistAvatarRepository {
	mock := &ArtistAvatarRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
