// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// AudioConverter is an autogenerated mock type for the AudioConverter type
type AudioConverter struct {
	mock.Mock
}

type AudioConverter_Expecter struct {
	mock *mock.Mock
}

func (_m *AudioConverter) EXPECT() *AudioConverter_Expecter {
	return &AudioConverter_Expecter{mock: &_m.Mock}
}

// ChangeBitrate provides a mock function with given fields: ctx, chunk
func (_m *AudioConverter) ChangeBitrate(ctx context.Context, chunk *entity.AudioChunk) (*entity.AudioChunk, error) {
	ret := _m.Called(ctx, chunk)

	if len(ret) == 0 {
		panic("no return value specified for ChangeBitrate")
	}

	var r0 *entity.AudioChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AudioChunk) (*entity.AudioChunk, error)); ok {
		return rf(ctx, chunk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AudioChunk) *entity.AudioChunk); ok {
		r0 = rf(ctx, chunk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AudioChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.AudioChunk) error); ok {
		r1 = rf(ctx, chunk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AudioConverter_ChangeBitrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeBitrate'
type AudioConverter_ChangeBitrate_Call struct {
	*mock.Call
}

// ChangeBitrate is a helper method to define mock.On call
//   - ctx context.Context
//   - chunk *entity.AudioChunk
func (_e *AudioConverter_Expecter) ChangeBitrate(ctx interface{}, chunk interface{}) *AudioConverter_ChangeBitrate_Call {
	return &AudioConverter_ChangeBitrate_Call{Call: _e.mock.On("ChangeBitrate", ctx, chunk)}
}

func (_c *AudioConverter_ChangeBitrate_Call) Run(run func(ctx context.Context, chunk *entity.AudioChunk)) *AudioConverter_ChangeBitrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AudioChunk))
	})
	return _c
}

func (_c *AudioConverter_ChangeBitrate_Call) Return(_a0 *entity.AudioChunk, _a1 error) *AudioConverter_ChangeBitrate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AudioConverter_ChangeBitrate_Call) RunAndReturn(run func(context.Context, *entity.AudioChunk) (*entity.AudioChunk, error)) *AudioConverter_ChangeBitrate_Call {
	_c.Call.Return(run)
	return _c
}

// NewAudioConverter creates a new instance of AudioConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAudioConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *AudioConverter {
	mock := &AudioConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
