// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AudioFileRepository is an autogenerated mock type for the AudioFileRepository type
type AudioFileRepository struct {
	mock.Mock
}

type AudioFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AudioFileRepository) EXPECT() *AudioFileRepository_Expecter {
	return &AudioFileRepository_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function with given fields: ctx, trackID
func (_m *AudioFileRepository) DeleteFile(ctx context.Context, trackID uuid.UUID) error {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AudioFileRepository_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type AudioFileRepository_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
func (_e *AudioFileRepository_Expecter) DeleteFile(ctx interface{}, trackID interface{}) *AudioFileRepository_DeleteFile_Call {
	return &AudioFileRepository_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, trackID)}
}

func (_c *AudioFileRepository_DeleteFile_Call) Run(run func(ctx context.Context, trackID uuid.UUID)) *AudioFileRepository_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AudioFileRepository_DeleteFile_Call) Return(_a0 error) *AudioFileRepository_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AudioFileRepository_DeleteFile_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *AudioFileRepository_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetAudioChunk provides a mock function with given fields: ctx, chunk
func (_m *AudioFileRepository) GetAudioChunk(ctx context.Context, chunk *entity.AudioChunk) (*entity.AudioChunk, error) {
	ret := _m.Called(ctx, chunk)

	if len(ret) == 0 {
		panic("no return value specified for GetAudioChunk")
	}

	var r0 *entity.AudioChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AudioChunk) (*entity.AudioChunk, error)); ok {
		return rf(ctx, chunk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AudioChunk) *entity.AudioChunk); ok {
		r0 = rf(ctx, chunk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AudioChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.AudioChunk) error); ok {
		r1 = rf(ctx, chunk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AudioFileRepository_GetAudioChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAudioChunk'
type AudioFileRepository_GetAudioChunk_Call struct {
	*mock.Call
}

// GetAudioChunk is a helper method to define mock.On call
//   - ctx context.Context
//   - chunk *entity.AudioChunk
func (_e *AudioFileRepository_Expecter) GetAudioChunk(ctx interface{}, chunk interface{}) *AudioFileRepository_GetAudioChunk_Call {
	return &AudioFileRepository_GetAudioChunk_Call{Call: _e.mock.On("GetAudioChunk", ctx, chunk)}
}

func (_c *AudioFileRepository_GetAudioChunk_Call) Run(run func(ctx context.Context, chunk *entity.AudioChunk)) *AudioFileRepository_GetAudioChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AudioChunk))
	})
	return _c
}

func (_c *AudioFileRepository_GetAudioChunk_Call) Return(_a0 *entity.AudioChunk, _a1 error) *AudioFileRepository_GetAudioChunk_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AudioFileRepository_GetAudioChunk_Call) RunAndReturn(run func(context.Context, *entity.AudioChunk) (*entity.AudioChunk, error)) *AudioFileRepository_GetAudioChunk_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAudioFile provides a mock function with given fields: ctx, chunk
func (_m *AudioFileRepository) UploadAudioFile(ctx context.Context, chunk *entity.AudioChunk) error {
	ret := _m.Called(ctx, chunk)

	if len(ret) == 0 {
		panic("no return value specified for UploadAudioFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AudioChunk) error); ok {
		r0 = rf(ctx, chunk)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AudioFileRepository_UploadAudioFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAudioFile'
type AudioFileRepository_UploadAudioFile_Call struct {
	*mock.Call
}

// UploadAudioFile is a helper method to define mock.On call
//   - ctx context.Context
//   - chunk *entity.AudioChunk
func (_e *AudioFileRepository_Expecter) UploadAudioFile(ctx interface{}, chunk interface{}) *AudioFileRepository_UploadAudioFile_Call {
	return &AudioFileRepository_UploadAudioFile_Call{Call: _e.mock.On("UploadAudioFile", ctx, chunk)}
}

func (_c *AudioFileRepository_UploadAudioFile_Call) Run(run func(ctx context.Context, chunk *entity.AudioChunk)) *AudioFileRepository_UploadAudioFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AudioChunk))
	})
	return _c
}

func (_c *AudioFileRepository_UploadAudioFile_Call) Return(_a0 error) *AudioFileRepository_UploadAudioFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AudioFileRepository_UploadAudioFile_Call) RunAndReturn(run func(context.Context, *entity.AudioChunk) error) *AudioFileRepository_UploadAudioFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewAudioFileRepository creates a new instance of AudioFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAudioFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AudioFileRepository {
	mock := &AudioFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
