// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// GetClaims provides a mock function with given fields: ctx, accessToken
func (_m *AuthService) GetClaims(ctx context.Context, accessToken string) (*entity.Claims, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetClaims")
	}

	var r0 *entity.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Claims, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Claims); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_GetClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaims'
type AuthService_GetClaims_Call struct {
	*mock.Call
}

// GetClaims is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *AuthService_Expecter) GetClaims(ctx interface{}, accessToken interface{}) *AuthService_GetClaims_Call {
	return &AuthService_GetClaims_Call{Call: _e.mock.On("GetClaims", ctx, accessToken)}
}

func (_c *AuthService_GetClaims_Call) Run(run func(ctx context.Context, accessToken string)) *AuthService_GetClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthService_GetClaims_Call) Return(_a0 *entity.Claims, _a1 error) *AuthService_GetClaims_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_GetClaims_Call) RunAndReturn(run func(context.Context, string) (*entity.Claims, error)) *AuthService_GetClaims_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, credentials
func (_m *AuthService) Login(ctx context.Context, credentials *entity.UserCredentials) (*entity.AuthTokens, error) {
	ret := _m.Called(ctx, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *entity.AuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserCredentials) (*entity.AuthTokens, error)); ok {
		return rf(ctx, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserCredentials) *entity.AuthTokens); ok {
		r0 = rf(ctx, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserCredentials) error); ok {
		r1 = rf(ctx, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials *entity.UserCredentials
func (_e *AuthService_Expecter) Login(ctx interface{}, credentials interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, credentials)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, credentials *entity.UserCredentials)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserCredentials))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(_a0 *entity.AuthTokens, _a1 error) *AuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(context.Context, *entity.UserCredentials) (*entity.AuthTokens, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *AuthService) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthService_Expecter) Logout(ctx interface{}, refreshToken interface{}) *AuthService_Logout_Call {
	return &AuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *AuthService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthService_Logout_Call) Return(_a0 error) *AuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_Logout_Call) RunAndReturn(run func(context.Context, string) error) *AuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function with given fields: ctx, refreshToken
func (_m *AuthService) RefreshTokens(ctx context.Context, refreshToken string) (*entity.AuthTokens, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *entity.AuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.AuthTokens, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.AuthTokens); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type AuthService_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthService_Expecter) RefreshTokens(ctx interface{}, refreshToken interface{}) *AuthService_RefreshTokens_Call {
	return &AuthService_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, refreshToken)}
}

func (_c *AuthService_RefreshTokens_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthService_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AuthService_RefreshTokens_Call) Return(_a0 *entity.AuthTokens, _a1 error) *AuthService_RefreshTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_RefreshTokens_Call) RunAndReturn(run func(context.Context, string) (*entity.AuthTokens, error)) *AuthService_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, credentials
func (_m *AuthService) RegisterUser(ctx context.Context, credentials *entity.UserCredentials) (*entity.AuthTokens, error) {
	ret := _m.Called(ctx, credentials)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *entity.AuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserCredentials) (*entity.AuthTokens, error)); ok {
		return rf(ctx, credentials)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserCredentials) *entity.AuthTokens); ok {
		r0 = rf(ctx, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserCredentials) error); ok {
		r1 = rf(ctx, credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type AuthService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials *entity.UserCredentials
func (_e *AuthService_Expecter) RegisterUser(ctx interface{}, credentials interface{}) *AuthService_RegisterUser_Call {
	return &AuthService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, credentials)}
}

func (_c *AuthService_RegisterUser_Call) Run(run func(ctx context.Context, credentials *entity.UserCredentials)) *AuthService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserCredentials))
	})
	return _c
}

func (_c *AuthService_RegisterUser_Call) Return(_a0 *entity.AuthTokens, _a1 error) *AuthService_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_RegisterUser_Call) RunAndReturn(run func(context.Context, *entity.UserCredentials) (*entity.AuthTokens, error)) *AuthService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, userID, passwords
func (_m *AuthService) UpdatePassword(ctx context.Context, userID uuid.UUID, passwords *entity.UserPasswords) error {
	ret := _m.Called(ctx, userID, passwords)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *entity.UserPasswords) error); ok {
		r0 = rf(ctx, userID, passwords)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type AuthService_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - passwords *entity.UserPasswords
func (_e *AuthService_Expecter) UpdatePassword(ctx interface{}, userID interface{}, passwords interface{}) *AuthService_UpdatePassword_Call {
	return &AuthService_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, passwords)}
}

func (_c *AuthService_UpdatePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, passwords *entity.UserPasswords)) *AuthService_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*entity.UserPasswords))
	})
	return _c
}

func (_c *AuthService_UpdatePassword_Call) Return(_a0 error) *AuthService_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_UpdatePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, *entity.UserPasswords) error) *AuthService_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
