// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ContentAggregator is an autogenerated mock type for the ContentAggregator type
type ContentAggregator struct {
	mock.Mock
}

type ContentAggregator_Expecter struct {
	mock *mock.Mock
}

func (_m *ContentAggregator) EXPECT() *ContentAggregator_Expecter {
	return &ContentAggregator_Expecter{mock: &_m.Mock}
}

// GetAlbums provides a mock function with given fields: ctx, albums
func (_m *ContentAggregator) GetAlbums(ctx context.Context, albums ...*entity.AlbumMeta) ([]*entity.AlbumMetaAggregated, error) {
	_va := make([]interface{}, len(albums))
	for _i := range albums {
		_va[_i] = albums[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbums")
	}

	var r0 []*entity.AlbumMetaAggregated
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...*entity.AlbumMeta) ([]*entity.AlbumMetaAggregated, error)); ok {
		return rf(ctx, albums...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...*entity.AlbumMeta) []*entity.AlbumMetaAggregated); ok {
		r0 = rf(ctx, albums...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AlbumMetaAggregated)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...*entity.AlbumMeta) error); ok {
		r1 = rf(ctx, albums...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContentAggregator_GetAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbums'
type ContentAggregator_GetAlbums_Call struct {
	*mock.Call
}

// GetAlbums is a helper method to define mock.On call
//   - ctx context.Context
//   - albums ...*entity.AlbumMeta
func (_e *ContentAggregator_Expecter) GetAlbums(ctx interface{}, albums ...interface{}) *ContentAggregator_GetAlbums_Call {
	return &ContentAggregator_GetAlbums_Call{Call: _e.mock.On("GetAlbums",
		append([]interface{}{ctx}, albums...)...)}
}

func (_c *ContentAggregator_GetAlbums_Call) Run(run func(ctx context.Context, albums ...*entity.AlbumMeta)) *ContentAggregator_GetAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*entity.AlbumMeta, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(*entity.AlbumMeta)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ContentAggregator_GetAlbums_Call) Return(_a0 []*entity.AlbumMetaAggregated, err error) *ContentAggregator_GetAlbums_Call {
	_c.Call.Return(_a0, err)
	return _c
}

func (_c *ContentAggregator_GetAlbums_Call) RunAndReturn(run func(context.Context, ...*entity.AlbumMeta) ([]*entity.AlbumMetaAggregated, error)) *ContentAggregator_GetAlbums_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumsByIDs provides a mock function with given fields: ctx, albumIDs
func (_m *ContentAggregator) GetAlbumsByIDs(ctx context.Context, albumIDs ...uuid.UUID) ([]*entity.AlbumMetaAggregated, error) {
	_va := make([]interface{}, len(albumIDs))
	for _i := range albumIDs {
		_va[_i] = albumIDs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumsByIDs")
	}

	var r0 []*entity.AlbumMetaAggregated
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) ([]*entity.AlbumMetaAggregated, error)); ok {
		return rf(ctx, albumIDs...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) []*entity.AlbumMetaAggregated); ok {
		r0 = rf(ctx, albumIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AlbumMetaAggregated)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...uuid.UUID) error); ok {
		r1 = rf(ctx, albumIDs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContentAggregator_GetAlbumsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumsByIDs'
type ContentAggregator_GetAlbumsByIDs_Call struct {
	*mock.Call
}

// GetAlbumsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - albumIDs ...uuid.UUID
func (_e *ContentAggregator_Expecter) GetAlbumsByIDs(ctx interface{}, albumIDs ...interface{}) *ContentAggregator_GetAlbumsByIDs_Call {
	return &ContentAggregator_GetAlbumsByIDs_Call{Call: _e.mock.On("GetAlbumsByIDs",
		append([]interface{}{ctx}, albumIDs...)...)}
}

func (_c *ContentAggregator_GetAlbumsByIDs_Call) Run(run func(ctx context.Context, albumIDs ...uuid.UUID)) *ContentAggregator_GetAlbumsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]uuid.UUID, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(uuid.UUID)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ContentAggregator_GetAlbumsByIDs_Call) Return(_a0 []*entity.AlbumMetaAggregated, err error) *ContentAggregator_GetAlbumsByIDs_Call {
	_c.Call.Return(_a0, err)
	return _c
}

func (_c *ContentAggregator_GetAlbumsByIDs_Call) RunAndReturn(run func(context.Context, ...uuid.UUID) ([]*entity.AlbumMetaAggregated, error)) *ContentAggregator_GetAlbumsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetTracks provides a mock function with given fields: ctx, tracks
func (_m *ContentAggregator) GetTracks(ctx context.Context, tracks ...*entity.TrackMeta) ([]*entity.TrackMetaAggregated, error) {
	_va := make([]interface{}, len(tracks))
	for _i := range tracks {
		_va[_i] = tracks[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTracks")
	}

	var r0 []*entity.TrackMetaAggregated
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...*entity.TrackMeta) ([]*entity.TrackMetaAggregated, error)); ok {
		return rf(ctx, tracks...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...*entity.TrackMeta) []*entity.TrackMetaAggregated); ok {
		r0 = rf(ctx, tracks...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TrackMetaAggregated)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...*entity.TrackMeta) error); ok {
		r1 = rf(ctx, tracks...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContentAggregator_GetTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTracks'
type ContentAggregator_GetTracks_Call struct {
	*mock.Call
}

// GetTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - tracks ...*entity.TrackMeta
func (_e *ContentAggregator_Expecter) GetTracks(ctx interface{}, tracks ...interface{}) *ContentAggregator_GetTracks_Call {
	return &ContentAggregator_GetTracks_Call{Call: _e.mock.On("GetTracks",
		append([]interface{}{ctx}, tracks...)...)}
}

func (_c *ContentAggregator_GetTracks_Call) Run(run func(ctx context.Context, tracks ...*entity.TrackMeta)) *ContentAggregator_GetTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*entity.TrackMeta, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(*entity.TrackMeta)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ContentAggregator_GetTracks_Call) Return(_a0 []*entity.TrackMetaAggregated, err error) *ContentAggregator_GetTracks_Call {
	_c.Call.Return(_a0, err)
	return _c
}

func (_c *ContentAggregator_GetTracks_Call) RunAndReturn(run func(context.Context, ...*entity.TrackMeta) ([]*entity.TrackMetaAggregated, error)) *ContentAggregator_GetTracks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTracksByIDs provides a mock function with given fields: ctx, trackIDs
func (_m *ContentAggregator) GetTracksByIDs(ctx context.Context, trackIDs ...uuid.UUID) ([]*entity.TrackMetaAggregated, error) {
	_va := make([]interface{}, len(trackIDs))
	for _i := range trackIDs {
		_va[_i] = trackIDs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetTracksByIDs")
	}

	var r0 []*entity.TrackMetaAggregated
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) ([]*entity.TrackMetaAggregated, error)); ok {
		return rf(ctx, trackIDs...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) []*entity.TrackMetaAggregated); ok {
		r0 = rf(ctx, trackIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TrackMetaAggregated)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...uuid.UUID) error); ok {
		r1 = rf(ctx, trackIDs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContentAggregator_GetTracksByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTracksByIDs'
type ContentAggregator_GetTracksByIDs_Call struct {
	*mock.Call
}

// GetTracksByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - trackIDs ...uuid.UUID
func (_e *ContentAggregator_Expecter) GetTracksByIDs(ctx interface{}, trackIDs ...interface{}) *ContentAggregator_GetTracksByIDs_Call {
	return &ContentAggregator_GetTracksByIDs_Call{Call: _e.mock.On("GetTracksByIDs",
		append([]interface{}{ctx}, trackIDs...)...)}
}

func (_c *ContentAggregator_GetTracksByIDs_Call) Run(run func(ctx context.Context, trackIDs ...uuid.UUID)) *ContentAggregator_GetTracksByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]uuid.UUID, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(uuid.UUID)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ContentAggregator_GetTracksByIDs_Call) Return(_a0 []*entity.TrackMetaAggregated, err error) *ContentAggregator_GetTracksByIDs_Call {
	_c.Call.Return(_a0, err)
	return _c
}

func (_c *ContentAggregator_GetTracksByIDs_Call) RunAndReturn(run func(context.Context, ...uuid.UUID) ([]*entity.TrackMetaAggregated, error)) *ContentAggregator_GetTracksByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewContentAggregator creates a new instance of ContentAggregator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContentAggregator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContentAggregator {
	mock := &ContentAggregator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
