// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EventHandler is an autogenerated mock type for the EventHandler type
type EventHandler[T interface{}] struct {
	mock.Mock
}

type EventHandler_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *EventHandler[T]) EXPECT() *EventHandler_Expecter[T] {
	return &EventHandler_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, event
func (_m *EventHandler[T]) Execute(ctx context.Context, event T) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type EventHandler_Execute_Call[T interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - event T
func (_e *EventHandler_Expecter[T]) Execute(ctx interface{}, event interface{}) *EventHandler_Execute_Call[T] {
	return &EventHandler_Execute_Call[T]{Call: _e.mock.On("Execute", ctx, event)}
}

func (_c *EventHandler_Execute_Call[T]) Run(run func(ctx context.Context, event T)) *EventHandler_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *EventHandler_Execute_Call[T]) Return(_a0 error) *EventHandler_Execute_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventHandler_Execute_Call[T]) RunAndReturn(run func(context.Context, T) error) *EventHandler_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewEventHandler creates a new instance of EventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventHandler[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *EventHandler[T] {
	mock := &EventHandler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
