// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// EventBusSub is an autogenerated mock type for the EventBusSub type
type EventBusSub struct {
	mock.Mock
}

type EventBusSub_Expecter struct {
	mock *mock.Mock
}

func (_m *EventBusSub) EXPECT() *EventBusSub_Expecter {
	return &EventBusSub_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: ctx, handler
func (_m *EventBusSub) Subscribe(ctx context.Context, handler func(context.Context, *entity.ListeningEvent) error) error {
	ret := _m.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, *entity.ListeningEvent) error) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventBusSub_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type EventBusSub_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - handler func(context.Context , *entity.ListeningEvent) error
func (_e *EventBusSub_Expecter) Subscribe(ctx interface{}, handler interface{}) *EventBusSub_Subscribe_Call {
	return &EventBusSub_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, handler)}
}

func (_c *EventBusSub_Subscribe_Call) Run(run func(ctx context.Context, handler func(context.Context, *entity.ListeningEvent) error)) *EventBusSub_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context, *entity.ListeningEvent) error))
	})
	return _c
}

func (_c *EventBusSub_Subscribe_Call) Return(_a0 error) *EventBusSub_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventBusSub_Subscribe_Call) RunAndReturn(run func(context.Context, func(context.Context, *entity.ListeningEvent) error) error) *EventBusSub_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventBusSub creates a new instance of EventBusSub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventBusSub(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventBusSub {
	mock := &EventBusSub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
