// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// EventBusPub is an autogenerated mock type for the EventBusPub type
type EventBusPub struct {
	mock.Mock
}

type EventBusPub_Expecter struct {
	mock *mock.Mock
}

func (_m *EventBusPub) EXPECT() *EventBusPub_Expecter {
	return &EventBusPub_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, event
func (_m *EventBusPub) Publish(ctx context.Context, event *entity.ListeningEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ListeningEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventBusPub_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type EventBusPub_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.ListeningEvent
func (_e *EventBusPub_Expecter) Publish(ctx interface{}, event interface{}) *EventBusPub_Publish_Call {
	return &EventBusPub_Publish_Call{Call: _e.mock.On("Publish", ctx, event)}
}

func (_c *EventBusPub_Publish_Call) Run(run func(ctx context.Context, event *entity.ListeningEvent)) *EventBusPub_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ListeningEvent))
	})
	return _c
}

func (_c *EventBusPub_Publish_Call) Return(_a0 error) *EventBusPub_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventBusPub_Publish_Call) RunAndReturn(run func(context.Context, *entity.ListeningEvent) error) *EventBusPub_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventBusPub creates a new instance of EventBusPub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventBusPub(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventBusPub {
	mock := &EventBusPub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
