// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// FavoritesDeletionService is an autogenerated mock type for the FavoritesDeletionService type
type FavoritesDeletionService struct {
	mock.Mock
}

type FavoritesDeletionService_Expecter struct {
	mock *mock.Mock
}

func (_m *FavoritesDeletionService) EXPECT() *FavoritesDeletionService_Expecter {
	return &FavoritesDeletionService_Expecter{mock: &_m.Mock}
}

// AddPlaylistToAllFavorites provides a mock function with given fields: ctx, claims, userIDs, playlistID
func (_m *FavoritesDeletionService) AddPlaylistToAllFavorites(ctx context.Context, claims *entity.Claims, userIDs []uuid.UUID, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, userIDs, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for AddPlaylistToAllFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, []uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, userIDs, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoritesDeletionService_AddPlaylistToAllFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlaylistToAllFavorites'
type FavoritesDeletionService_AddPlaylistToAllFavorites_Call struct {
	*mock.Call
}

// AddPlaylistToAllFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - userIDs []uuid.UUID
//   - playlistID uuid.UUID
func (_e *FavoritesDeletionService_Expecter) AddPlaylistToAllFavorites(ctx interface{}, claims interface{}, userIDs interface{}, playlistID interface{}) *FavoritesDeletionService_AddPlaylistToAllFavorites_Call {
	return &FavoritesDeletionService_AddPlaylistToAllFavorites_Call{Call: _e.mock.On("AddPlaylistToAllFavorites", ctx, claims, userIDs, playlistID)}
}

func (_c *FavoritesDeletionService_AddPlaylistToAllFavorites_Call) Run(run func(ctx context.Context, claims *entity.Claims, userIDs []uuid.UUID, playlistID uuid.UUID)) *FavoritesDeletionService_AddPlaylistToAllFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].([]uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *FavoritesDeletionService_AddPlaylistToAllFavorites_Call) Return(_a0 error) *FavoritesDeletionService_AddPlaylistToAllFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoritesDeletionService_AddPlaylistToAllFavorites_Call) RunAndReturn(run func(context.Context, *entity.Claims, []uuid.UUID, uuid.UUID) error) *FavoritesDeletionService_AddPlaylistToAllFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFromAllFavorites provides a mock function with given fields: ctx, claims, playlistID, withOwner
func (_m *FavoritesDeletionService) DeleteFromAllFavorites(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID, withOwner bool) error {
	ret := _m.Called(ctx, claims, playlistID, withOwner)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFromAllFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, claims, playlistID, withOwner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoritesDeletionService_DeleteFromAllFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromAllFavorites'
type FavoritesDeletionService_DeleteFromAllFavorites_Call struct {
	*mock.Call
}

// DeleteFromAllFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
//   - withOwner bool
func (_e *FavoritesDeletionService_Expecter) DeleteFromAllFavorites(ctx interface{}, claims interface{}, playlistID interface{}, withOwner interface{}) *FavoritesDeletionService_DeleteFromAllFavorites_Call {
	return &FavoritesDeletionService_DeleteFromAllFavorites_Call{Call: _e.mock.On("DeleteFromAllFavorites", ctx, claims, playlistID, withOwner)}
}

func (_c *FavoritesDeletionService_DeleteFromAllFavorites_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID, withOwner bool)) *FavoritesDeletionService_DeleteFromAllFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *FavoritesDeletionService_DeleteFromAllFavorites_Call) Return(_a0 error) *FavoritesDeletionService_DeleteFromAllFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FavoritesDeletionService_DeleteFromAllFavorites_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID, bool) error) *FavoritesDeletionService_DeleteFromAllFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithFavoritePlaylist provides a mock function with given fields: ctx, claims, playlistID, withOwner
func (_m *FavoritesDeletionService) GetUsersWithFavoritePlaylist(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID, withOwner bool) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, claims, playlistID, withOwner)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithFavoritePlaylist")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID, bool) ([]uuid.UUID, error)); ok {
		return rf(ctx, claims, playlistID, withOwner)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID, bool) []uuid.UUID); ok {
		r0 = rf(ctx, claims, playlistID, withOwner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, claims, playlistID, withOwner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithFavoritePlaylist'
type FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call struct {
	*mock.Call
}

// GetUsersWithFavoritePlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
//   - withOwner bool
func (_e *FavoritesDeletionService_Expecter) GetUsersWithFavoritePlaylist(ctx interface{}, claims interface{}, playlistID interface{}, withOwner interface{}) *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call {
	return &FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call{Call: _e.mock.On("GetUsersWithFavoritePlaylist", ctx, claims, playlistID, withOwner)}
}

func (_c *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID, withOwner bool)) *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call) Return(_a0 []uuid.UUID, _a1 error) *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID, bool) ([]uuid.UUID, error)) *FavoritesDeletionService_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// NewFavoritesDeletionService creates a new instance of FavoritesDeletionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFavoritesDeletionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FavoritesDeletionService {
	mock := &FavoritesDeletionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
