// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GenreAssignRepository is an autogenerated mock type for the GenreAssignRepository type
type GenreAssignRepository struct {
	mock.Mock
}

type GenreAssignRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GenreAssignRepository) EXPECT() *GenreAssignRepository_Expecter {
	return &GenreAssignRepository_Expecter{mock: &_m.Mock}
}

// AssignGenreToAlbum provides a mock function with given fields: ctx, genreID, albumID
func (_m *GenreAssignRepository) AssignGenreToAlbum(ctx context.Context, genreID uuid.UUID, albumID uuid.UUID) error {
	ret := _m.Called(ctx, genreID, albumID)

	if len(ret) == 0 {
		panic("no return value specified for AssignGenreToAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, genreID, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreAssignRepository_AssignGenreToAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignGenreToAlbum'
type GenreAssignRepository_AssignGenreToAlbum_Call struct {
	*mock.Call
}

// AssignGenreToAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - genreID uuid.UUID
//   - albumID uuid.UUID
func (_e *GenreAssignRepository_Expecter) AssignGenreToAlbum(ctx interface{}, genreID interface{}, albumID interface{}) *GenreAssignRepository_AssignGenreToAlbum_Call {
	return &GenreAssignRepository_AssignGenreToAlbum_Call{Call: _e.mock.On("AssignGenreToAlbum", ctx, genreID, albumID)}
}

func (_c *GenreAssignRepository_AssignGenreToAlbum_Call) Run(run func(ctx context.Context, genreID uuid.UUID, albumID uuid.UUID)) *GenreAssignRepository_AssignGenreToAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *GenreAssignRepository_AssignGenreToAlbum_Call) Return(_a0 error) *GenreAssignRepository_AssignGenreToAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreAssignRepository_AssignGenreToAlbum_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *GenreAssignRepository_AssignGenreToAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// UnassignGenreFromAlbum provides a mock function with given fields: ctx, genreID, albumID
func (_m *GenreAssignRepository) UnassignGenreFromAlbum(ctx context.Context, genreID uuid.UUID, albumID uuid.UUID) error {
	ret := _m.Called(ctx, genreID, albumID)

	if len(ret) == 0 {
		panic("no return value specified for UnassignGenreFromAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, genreID, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreAssignRepository_UnassignGenreFromAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnassignGenreFromAlbum'
type GenreAssignRepository_UnassignGenreFromAlbum_Call struct {
	*mock.Call
}

// UnassignGenreFromAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - genreID uuid.UUID
//   - albumID uuid.UUID
func (_e *GenreAssignRepository_Expecter) UnassignGenreFromAlbum(ctx interface{}, genreID interface{}, albumID interface{}) *GenreAssignRepository_UnassignGenreFromAlbum_Call {
	return &GenreAssignRepository_UnassignGenreFromAlbum_Call{Call: _e.mock.On("UnassignGenreFromAlbum", ctx, genreID, albumID)}
}

func (_c *GenreAssignRepository_UnassignGenreFromAlbum_Call) Run(run func(ctx context.Context, genreID uuid.UUID, albumID uuid.UUID)) *GenreAssignRepository_UnassignGenreFromAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *GenreAssignRepository_UnassignGenreFromAlbum_Call) Return(_a0 error) *GenreAssignRepository_UnassignGenreFromAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreAssignRepository_UnassignGenreFromAlbum_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *GenreAssignRepository_UnassignGenreFromAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewGenreAssignRepository creates a new instance of GenreAssignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenreAssignRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenreAssignRepository {
	mock := &GenreAssignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
