// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GenreRepository is an autogenerated mock type for the GenreRepository type
type GenreRepository struct {
	mock.Mock
}

type GenreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GenreRepository) EXPECT() *GenreRepository_Expecter {
	return &GenreRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *GenreRepository) Create(ctx context.Context, _a1 *entity.Genre) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Genre) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type GenreRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Genre
func (_e *GenreRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *GenreRepository_Create_Call {
	return &GenreRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *GenreRepository_Create_Call) Run(run func(ctx context.Context, _a1 *entity.Genre)) *GenreRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Genre))
	})
	return _c
}

func (_c *GenreRepository_Create_Call) Return(_a0 error) *GenreRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Genre) error) *GenreRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, genreID
func (_m *GenreRepository) Delete(ctx context.Context, genreID uuid.UUID) error {
	ret := _m.Called(ctx, genreID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, genreID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type GenreRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - genreID uuid.UUID
func (_e *GenreRepository_Expecter) Delete(ctx interface{}, genreID interface{}) *GenreRepository_Delete_Call {
	return &GenreRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, genreID)}
}

func (_c *GenreRepository_Delete_Call) Run(run func(ctx context.Context, genreID uuid.UUID)) *GenreRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GenreRepository_Delete_Call) Return(_a0 error) *GenreRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *GenreRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *GenreRepository) GetAll(ctx context.Context) ([]*entity.Genre, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.Genre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Genre, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Genre); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenreRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type GenreRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *GenreRepository_Expecter) GetAll(ctx interface{}) *GenreRepository_GetAll_Call {
	return &GenreRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *GenreRepository_GetAll_Call) Run(run func(ctx context.Context)) *GenreRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *GenreRepository_GetAll_Call) Return(_a0 []*entity.Genre, _a1 error) *GenreRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GenreRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*entity.Genre, error)) *GenreRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAlbum provides a mock function with given fields: ctx, albumID
func (_m *GenreRepository) GetByAlbum(ctx context.Context, albumID uuid.UUID) ([]*entity.Genre, error) {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAlbum")
	}

	var r0 []*entity.Genre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Genre, error)); ok {
		return rf(ctx, albumID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Genre); ok {
		r0 = rf(ctx, albumID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, albumID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenreRepository_GetByAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAlbum'
type GenreRepository_GetByAlbum_Call struct {
	*mock.Call
}

// GetByAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID uuid.UUID
func (_e *GenreRepository_Expecter) GetByAlbum(ctx interface{}, albumID interface{}) *GenreRepository_GetByAlbum_Call {
	return &GenreRepository_GetByAlbum_Call{Call: _e.mock.On("GetByAlbum", ctx, albumID)}
}

func (_c *GenreRepository_GetByAlbum_Call) Run(run func(ctx context.Context, albumID uuid.UUID)) *GenreRepository_GetByAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GenreRepository_GetByAlbum_Call) Return(_a0 []*entity.Genre, _a1 error) *GenreRepository_GetByAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GenreRepository_GetByAlbum_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Genre, error)) *GenreRepository_GetByAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, genreID
func (_m *GenreRepository) GetByID(ctx context.Context, genreID uuid.UUID) (*entity.Genre, error) {
	ret := _m.Called(ctx, genreID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Genre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Genre, error)); ok {
		return rf(ctx, genreID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Genre); ok {
		r0 = rf(ctx, genreID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, genreID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenreRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type GenreRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - genreID uuid.UUID
func (_e *GenreRepository_Expecter) GetByID(ctx interface{}, genreID interface{}) *GenreRepository_GetByID_Call {
	return &GenreRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, genreID)}
}

func (_c *GenreRepository_GetByID_Call) Run(run func(ctx context.Context, genreID uuid.UUID)) *GenreRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *GenreRepository_GetByID_Call) Return(_a0 *entity.Genre, _a1 error) *GenreRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GenreRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Genre, error)) *GenreRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *GenreRepository) Update(ctx context.Context, _a1 *entity.Genre) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Genre) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type GenreRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Genre
func (_e *GenreRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *GenreRepository_Update_Call {
	return &GenreRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *GenreRepository_Update_Call) Run(run func(ctx context.Context, _a1 *entity.Genre)) *GenreRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Genre))
	})
	return _c
}

func (_c *GenreRepository_Update_Call) Return(_a0 error) *GenreRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Genre) error) *GenreRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewGenreRepository creates a new instance of GenreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenreRepository {
	mock := &GenreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
