// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GenreAssignService is an autogenerated mock type for the GenreAssignService type
type GenreAssignService struct {
	mock.Mock
}

type GenreAssignService_Expecter struct {
	mock *mock.Mock
}

func (_m *GenreAssignService) EXPECT() *GenreAssignService_Expecter {
	return &GenreAssignService_Expecter{mock: &_m.Mock}
}

// AssignGenreToAlbum provides a mock function with given fields: ctx, claims, genreID, albumID
func (_m *GenreAssignService) AssignGenreToAlbum(ctx context.Context, claims *entity.Claims, genreID uuid.UUID, albumID uuid.UUID) error {
	ret := _m.Called(ctx, claims, genreID, albumID)

	if len(ret) == 0 {
		panic("no return value specified for AssignGenreToAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, genreID, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreAssignService_AssignGenreToAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignGenreToAlbum'
type GenreAssignService_AssignGenreToAlbum_Call struct {
	*mock.Call
}

// AssignGenreToAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - genreID uuid.UUID
//   - albumID uuid.UUID
func (_e *GenreAssignService_Expecter) AssignGenreToAlbum(ctx interface{}, claims interface{}, genreID interface{}, albumID interface{}) *GenreAssignService_AssignGenreToAlbum_Call {
	return &GenreAssignService_AssignGenreToAlbum_Call{Call: _e.mock.On("AssignGenreToAlbum", ctx, claims, genreID, albumID)}
}

func (_c *GenreAssignService_AssignGenreToAlbum_Call) Run(run func(ctx context.Context, claims *entity.Claims, genreID uuid.UUID, albumID uuid.UUID)) *GenreAssignService_AssignGenreToAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *GenreAssignService_AssignGenreToAlbum_Call) Return(_a0 error) *GenreAssignService_AssignGenreToAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreAssignService_AssignGenreToAlbum_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID, uuid.UUID) error) *GenreAssignService_AssignGenreToAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// UnassignGenreFromAlbum provides a mock function with given fields: ctx, claims, genreID, albumID
func (_m *GenreAssignService) UnassignGenreFromAlbum(ctx context.Context, claims *entity.Claims, genreID uuid.UUID, albumID uuid.UUID) error {
	ret := _m.Called(ctx, claims, genreID, albumID)

	if len(ret) == 0 {
		panic("no return value specified for UnassignGenreFromAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, genreID, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenreAssignService_UnassignGenreFromAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnassignGenreFromAlbum'
type GenreAssignService_UnassignGenreFromAlbum_Call struct {
	*mock.Call
}

// UnassignGenreFromAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - genreID uuid.UUID
//   - albumID uuid.UUID
func (_e *GenreAssignService_Expecter) UnassignGenreFromAlbum(ctx interface{}, claims interface{}, genreID interface{}, albumID interface{}) *GenreAssignService_UnassignGenreFromAlbum_Call {
	return &GenreAssignService_UnassignGenreFromAlbum_Call{Call: _e.mock.On("UnassignGenreFromAlbum", ctx, claims, genreID, albumID)}
}

func (_c *GenreAssignService_UnassignGenreFromAlbum_Call) Run(run func(ctx context.Context, claims *entity.Claims, genreID uuid.UUID, albumID uuid.UUID)) *GenreAssignService_UnassignGenreFromAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *GenreAssignService_UnassignGenreFromAlbum_Call) Return(_a0 error) *GenreAssignService_UnassignGenreFromAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GenreAssignService_UnassignGenreFromAlbum_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID, uuid.UUID) error) *GenreAssignService_UnassignGenreFromAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewGenreAssignService creates a new instance of GenreAssignService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenreAssignService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenreAssignService {
	mock := &GenreAssignService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
