// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// LicenseService is an autogenerated mock type for the LicenseService type
type LicenseService struct {
	mock.Mock
}

type LicenseService_Expecter struct {
	mock *mock.Mock
}

func (_m *LicenseService) EXPECT() *LicenseService_Expecter {
	return &LicenseService_Expecter{mock: &_m.Mock}
}

// CreateLicense provides a mock function with given fields: ctx, claims, _a2
func (_m *LicenseService) CreateLicense(ctx context.Context, claims *entity.Claims, _a2 *entity.License) error {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateLicense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.License) error); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LicenseService_CreateLicense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLicense'
type LicenseService_CreateLicense_Call struct {
	*mock.Call
}

// CreateLicense is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.License
func (_e *LicenseService_Expecter) CreateLicense(ctx interface{}, claims interface{}, _a2 interface{}) *LicenseService_CreateLicense_Call {
	return &LicenseService_CreateLicense_Call{Call: _e.mock.On("CreateLicense", ctx, claims, _a2)}
}

func (_c *LicenseService_CreateLicense_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.License)) *LicenseService_CreateLicense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.License))
	})
	return _c
}

func (_c *LicenseService_CreateLicense_Call) Return(err error) *LicenseService_CreateLicense_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LicenseService_CreateLicense_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.License) error) *LicenseService_CreateLicense_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLicense provides a mock function with given fields: ctx, claims, licenseID
func (_m *LicenseService) DeleteLicense(ctx context.Context, claims *entity.Claims, licenseID uuid.UUID) error {
	ret := _m.Called(ctx, claims, licenseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLicense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, licenseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LicenseService_DeleteLicense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLicense'
type LicenseService_DeleteLicense_Call struct {
	*mock.Call
}

// DeleteLicense is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - licenseID uuid.UUID
func (_e *LicenseService_Expecter) DeleteLicense(ctx interface{}, claims interface{}, licenseID interface{}) *LicenseService_DeleteLicense_Call {
	return &LicenseService_DeleteLicense_Call{Call: _e.mock.On("DeleteLicense", ctx, claims, licenseID)}
}

func (_c *LicenseService_DeleteLicense_Call) Run(run func(ctx context.Context, claims *entity.Claims, licenseID uuid.UUID)) *LicenseService_DeleteLicense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *LicenseService_DeleteLicense_Call) Return(err error) *LicenseService_DeleteLicense_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LicenseService_DeleteLicense_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *LicenseService_DeleteLicense_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllLicenses provides a mock function with given fields: ctx
func (_m *LicenseService) GetAllLicenses(ctx context.Context) ([]*entity.License, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllLicenses")
	}

	var r0 []*entity.License
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.License, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.License); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.License)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LicenseService_GetAllLicenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllLicenses'
type LicenseService_GetAllLicenses_Call struct {
	*mock.Call
}

// GetAllLicenses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LicenseService_Expecter) GetAllLicenses(ctx interface{}) *LicenseService_GetAllLicenses_Call {
	return &LicenseService_GetAllLicenses_Call{Call: _e.mock.On("GetAllLicenses", ctx)}
}

func (_c *LicenseService_GetAllLicenses_Call) Run(run func(ctx context.Context)) *LicenseService_GetAllLicenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LicenseService_GetAllLicenses_Call) Return(_a0 []*entity.License, err error) *LicenseService_GetAllLicenses_Call {
	_c.Call.Return(_a0, err)
	return _c
}

func (_c *LicenseService_GetAllLicenses_Call) RunAndReturn(run func(context.Context) ([]*entity.License, error)) *LicenseService_GetAllLicenses_Call {
	_c.Call.Return(run)
	return _c
}

// GetLicenseByID provides a mock function with given fields: ctx, licenseID
func (_m *LicenseService) GetLicenseByID(ctx context.Context, licenseID uuid.UUID) (*entity.License, error) {
	ret := _m.Called(ctx, licenseID)

	if len(ret) == 0 {
		panic("no return value specified for GetLicenseByID")
	}

	var r0 *entity.License
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.License, error)); ok {
		return rf(ctx, licenseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.License); ok {
		r0 = rf(ctx, licenseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.License)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, licenseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LicenseService_GetLicenseByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLicenseByID'
type LicenseService_GetLicenseByID_Call struct {
	*mock.Call
}

// GetLicenseByID is a helper method to define mock.On call
//   - ctx context.Context
//   - licenseID uuid.UUID
func (_e *LicenseService_Expecter) GetLicenseByID(ctx interface{}, licenseID interface{}) *LicenseService_GetLicenseByID_Call {
	return &LicenseService_GetLicenseByID_Call{Call: _e.mock.On("GetLicenseByID", ctx, licenseID)}
}

func (_c *LicenseService_GetLicenseByID_Call) Run(run func(ctx context.Context, licenseID uuid.UUID)) *LicenseService_GetLicenseByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *LicenseService_GetLicenseByID_Call) Return(_a0 *entity.License, err error) *LicenseService_GetLicenseByID_Call {
	_c.Call.Return(_a0, err)
	return _c
}

func (_c *LicenseService_GetLicenseByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.License, error)) *LicenseService_GetLicenseByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLicense provides a mock function with given fields: ctx, claims, _a2
func (_m *LicenseService) UpdateLicense(ctx context.Context, claims *entity.Claims, _a2 *entity.License) error {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLicense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.License) error); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LicenseService_UpdateLicense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLicense'
type LicenseService_UpdateLicense_Call struct {
	*mock.Call
}

// UpdateLicense is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.License
func (_e *LicenseService_Expecter) UpdateLicense(ctx interface{}, claims interface{}, _a2 interface{}) *LicenseService_UpdateLicense_Call {
	return &LicenseService_UpdateLicense_Call{Call: _e.mock.On("UpdateLicense", ctx, claims, _a2)}
}

func (_c *LicenseService_UpdateLicense_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.License)) *LicenseService_UpdateLicense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.License))
	})
	return _c
}

func (_c *LicenseService_UpdateLicense_Call) Return(err error) *LicenseService_UpdateLicense_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LicenseService_UpdateLicense_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.License) error) *LicenseService_UpdateLicense_Call {
	_c.Call.Return(run)
	return _c
}

// NewLicenseService creates a new instance of LicenseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLicenseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LicenseService {
	mock := &LicenseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
