// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// LicenseRepository is an autogenerated mock type for the LicenseRepository type
type LicenseRepository struct {
	mock.Mock
}

type LicenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LicenseRepository) EXPECT() *LicenseRepository_Expecter {
	return &LicenseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *LicenseRepository) Create(ctx context.Context, _a1 *entity.License) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.License) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LicenseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LicenseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.License
func (_e *LicenseRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *LicenseRepository_Create_Call {
	return &LicenseRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *LicenseRepository_Create_Call) Run(run func(ctx context.Context, _a1 *entity.License)) *LicenseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.License))
	})
	return _c
}

func (_c *LicenseRepository_Create_Call) Return(_a0 error) *LicenseRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LicenseRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.License) error) *LicenseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, licenseID
func (_m *LicenseRepository) Delete(ctx context.Context, licenseID uuid.UUID) error {
	ret := _m.Called(ctx, licenseID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, licenseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LicenseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LicenseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - licenseID uuid.UUID
func (_e *LicenseRepository_Expecter) Delete(ctx interface{}, licenseID interface{}) *LicenseRepository_Delete_Call {
	return &LicenseRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, licenseID)}
}

func (_c *LicenseRepository_Delete_Call) Run(run func(ctx context.Context, licenseID uuid.UUID)) *LicenseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *LicenseRepository_Delete_Call) Return(_a0 error) *LicenseRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LicenseRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *LicenseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *LicenseRepository) GetAll(ctx context.Context) ([]*entity.License, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.License
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.License, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.License); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.License)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LicenseRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type LicenseRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LicenseRepository_Expecter) GetAll(ctx interface{}) *LicenseRepository_GetAll_Call {
	return &LicenseRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *LicenseRepository_GetAll_Call) Run(run func(ctx context.Context)) *LicenseRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LicenseRepository_GetAll_Call) Return(_a0 []*entity.License, _a1 error) *LicenseRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LicenseRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*entity.License, error)) *LicenseRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, licenseID
func (_m *LicenseRepository) GetByID(ctx context.Context, licenseID uuid.UUID) (*entity.License, error) {
	ret := _m.Called(ctx, licenseID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.License
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.License, error)); ok {
		return rf(ctx, licenseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.License); ok {
		r0 = rf(ctx, licenseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.License)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, licenseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LicenseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type LicenseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - licenseID uuid.UUID
func (_e *LicenseRepository_Expecter) GetByID(ctx interface{}, licenseID interface{}) *LicenseRepository_GetByID_Call {
	return &LicenseRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, licenseID)}
}

func (_c *LicenseRepository_GetByID_Call) Run(run func(ctx context.Context, licenseID uuid.UUID)) *LicenseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *LicenseRepository_GetByID_Call) Return(_a0 *entity.License, _a1 error) *LicenseRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LicenseRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.License, error)) *LicenseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *LicenseRepository) Update(ctx context.Context, _a1 *entity.License) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.License) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LicenseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LicenseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.License
func (_e *LicenseRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *LicenseRepository_Update_Call {
	return &LicenseRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *LicenseRepository_Update_Call) Run(run func(ctx context.Context, _a1 *entity.License)) *LicenseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.License))
	})
	return _c
}

func (_c *LicenseRepository_Update_Call) Return(_a0 error) *LicenseRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LicenseRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.License) error) *LicenseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewLicenseRepository creates a new instance of LicenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLicenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LicenseRepository {
	mock := &LicenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
