// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// ListeningEventPublisher is an autogenerated mock type for the ListeningEventPublisher type
type ListeningEventPublisher struct {
	mock.Mock
}

type ListeningEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *ListeningEventPublisher) EXPECT() *ListeningEventPublisher_Expecter {
	return &ListeningEventPublisher_Expecter{mock: &_m.Mock}
}

// SendListeningEvent provides a mock function with given fields: ctx, event
func (_m *ListeningEventPublisher) SendListeningEvent(ctx context.Context, event *entity.ListeningEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendListeningEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ListeningEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListeningEventPublisher_SendListeningEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendListeningEvent'
type ListeningEventPublisher_SendListeningEvent_Call struct {
	*mock.Call
}

// SendListeningEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.ListeningEvent
func (_e *ListeningEventPublisher_Expecter) SendListeningEvent(ctx interface{}, event interface{}) *ListeningEventPublisher_SendListeningEvent_Call {
	return &ListeningEventPublisher_SendListeningEvent_Call{Call: _e.mock.On("SendListeningEvent", ctx, event)}
}

func (_c *ListeningEventPublisher_SendListeningEvent_Call) Run(run func(ctx context.Context, event *entity.ListeningEvent)) *ListeningEventPublisher_SendListeningEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ListeningEvent))
	})
	return _c
}

func (_c *ListeningEventPublisher_SendListeningEvent_Call) Return(_a0 error) *ListeningEventPublisher_SendListeningEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ListeningEventPublisher_SendListeningEvent_Call) RunAndReturn(run func(context.Context, *entity.ListeningEvent) error) *ListeningEventPublisher_SendListeningEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewListeningEventPublisher creates a new instance of ListeningEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListeningEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListeningEventPublisher {
	mock := &ListeningEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
