// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// ListeningStatService is an autogenerated mock type for the ListeningStatService type
type ListeningStatService struct {
	mock.Mock
}

type ListeningStatService_Expecter struct {
	mock *mock.Mock
}

func (_m *ListeningStatService) EXPECT() *ListeningStatService_Expecter {
	return &ListeningStatService_Expecter{mock: &_m.Mock}
}

// UpdateStat provides a mock function with given fields: ctx, event
func (_m *ListeningStatService) UpdateStat(ctx context.Context, event *entity.ListeningEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ListeningEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListeningStatService_UpdateStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStat'
type ListeningStatService_UpdateStat_Call struct {
	*mock.Call
}

// UpdateStat is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.ListeningEvent
func (_e *ListeningStatService_Expecter) UpdateStat(ctx interface{}, event interface{}) *ListeningStatService_UpdateStat_Call {
	return &ListeningStatService_UpdateStat_Call{Call: _e.mock.On("UpdateStat", ctx, event)}
}

func (_c *ListeningStatService_UpdateStat_Call) Run(run func(ctx context.Context, event *entity.ListeningEvent)) *ListeningStatService_UpdateStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.ListeningEvent))
	})
	return _c
}

func (_c *ListeningStatService_UpdateStat_Call) Return(_a0 error) *ListeningStatService_UpdateStat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ListeningStatService_UpdateStat_Call) RunAndReturn(run func(context.Context, *entity.ListeningEvent) error) *ListeningStatService_UpdateStat_Call {
	_c.Call.Return(run)
	return _c
}

// NewListeningStatService creates a new instance of ListeningStatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListeningStatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListeningStatService {
	mock := &ListeningStatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
