// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MetaDeletionService is an autogenerated mock type for the MetaDeletionService type
type MetaDeletionService struct {
	mock.Mock
}

type MetaDeletionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MetaDeletionService) EXPECT() *MetaDeletionService_Expecter {
	return &MetaDeletionService_Expecter{mock: &_m.Mock}
}

// DeleteMeta provides a mock function with given fields: ctx, claims, playlistID
func (_m *MetaDeletionService) DeleteMeta(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetaDeletionService_DeleteMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMeta'
type MetaDeletionService_DeleteMeta_Call struct {
	*mock.Call
}

// DeleteMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *MetaDeletionService_Expecter) DeleteMeta(ctx interface{}, claims interface{}, playlistID interface{}) *MetaDeletionService_DeleteMeta_Call {
	return &MetaDeletionService_DeleteMeta_Call{Call: _e.mock.On("DeleteMeta", ctx, claims, playlistID)}
}

func (_c *MetaDeletionService_DeleteMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *MetaDeletionService_DeleteMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MetaDeletionService_DeleteMeta_Call) Return(_a0 error) *MetaDeletionService_DeleteMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetaDeletionService_DeleteMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *MetaDeletionService_DeleteMeta_Call {
	_c.Call.Return(run)
	return _c
}

// NewMetaDeletionService creates a new instance of MetaDeletionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetaDeletionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetaDeletionService {
	mock := &MetaDeletionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
