// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordHasher is an autogenerated mock type for the PasswordHasher type
type PasswordHasher struct {
	mock.Mock
}

type PasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordHasher) EXPECT() *PasswordHasher_Expecter {
	return &PasswordHasher_Expecter{mock: &_m.Mock}
}

// CompareHashAndPassword provides a mock function with given fields: hashed, password
func (_m *PasswordHasher) CompareHashAndPassword(hashed string, password string) error {
	ret := _m.Called(hashed, password)

	if len(ret) == 0 {
		panic("no return value specified for CompareHashAndPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hashed, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PasswordHasher_CompareHashAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareHashAndPassword'
type PasswordHasher_CompareHashAndPassword_Call struct {
	*mock.Call
}

// CompareHashAndPassword is a helper method to define mock.On call
//   - hashed string
//   - password string
func (_e *PasswordHasher_Expecter) CompareHashAndPassword(hashed interface{}, password interface{}) *PasswordHasher_CompareHashAndPassword_Call {
	return &PasswordHasher_CompareHashAndPassword_Call{Call: _e.mock.On("CompareHashAndPassword", hashed, password)}
}

func (_c *PasswordHasher_CompareHashAndPassword_Call) Run(run func(hashed string, password string)) *PasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PasswordHasher_CompareHashAndPassword_Call) Return(_a0 error) *PasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PasswordHasher_CompareHashAndPassword_Call) RunAndReturn(run func(string, string) error) *PasswordHasher_CompareHashAndPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateFromPassword provides a mock function with given fields: password
func (_m *PasswordHasher) GenerateFromPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordHasher_GenerateFromPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFromPassword'
type PasswordHasher_GenerateFromPassword_Call struct {
	*mock.Call
}

// GenerateFromPassword is a helper method to define mock.On call
//   - password string
func (_e *PasswordHasher_Expecter) GenerateFromPassword(password interface{}) *PasswordHasher_GenerateFromPassword_Call {
	return &PasswordHasher_GenerateFromPassword_Call{Call: _e.mock.On("GenerateFromPassword", password)}
}

func (_c *PasswordHasher_GenerateFromPassword_Call) Run(run func(password string)) *PasswordHasher_GenerateFromPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PasswordHasher_GenerateFromPassword_Call) Return(_a0 string, _a1 error) *PasswordHasher_GenerateFromPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordHasher_GenerateFromPassword_Call) RunAndReturn(run func(string) (string, error)) *PasswordHasher_GenerateFromPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswordHasher creates a new instance of PasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHasher {
	mock := &PasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
