// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistTracksRepository is an autogenerated mock type for the PlaylistTracksRepository type
type PlaylistTracksRepository struct {
	mock.Mock
}

type PlaylistTracksRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistTracksRepository) EXPECT() *PlaylistTracksRepository_Expecter {
	return &PlaylistTracksRepository_Expecter{mock: &_m.Mock}
}

// AddTrackToPlaylist provides a mock function with given fields: ctx, playlistTrack
func (_m *PlaylistTracksRepository) AddTrackToPlaylist(ctx context.Context, playlistTrack *entity.PlaylistTrack) error {
	ret := _m.Called(ctx, playlistTrack)

	if len(ret) == 0 {
		panic("no return value specified for AddTrackToPlaylist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PlaylistTrack) error); ok {
		r0 = rf(ctx, playlistTrack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistTracksRepository_AddTrackToPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTrackToPlaylist'
type PlaylistTracksRepository_AddTrackToPlaylist_Call struct {
	*mock.Call
}

// AddTrackToPlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistTrack *entity.PlaylistTrack
func (_e *PlaylistTracksRepository_Expecter) AddTrackToPlaylist(ctx interface{}, playlistTrack interface{}) *PlaylistTracksRepository_AddTrackToPlaylist_Call {
	return &PlaylistTracksRepository_AddTrackToPlaylist_Call{Call: _e.mock.On("AddTrackToPlaylist", ctx, playlistTrack)}
}

func (_c *PlaylistTracksRepository_AddTrackToPlaylist_Call) Run(run func(ctx context.Context, playlistTrack *entity.PlaylistTrack)) *PlaylistTracksRepository_AddTrackToPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.PlaylistTrack))
	})
	return _c
}

func (_c *PlaylistTracksRepository_AddTrackToPlaylist_Call) Return(_a0 error) *PlaylistTracksRepository_AddTrackToPlaylist_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistTracksRepository_AddTrackToPlaylist_Call) RunAndReturn(run func(context.Context, *entity.PlaylistTrack) error) *PlaylistTracksRepository_AddTrackToPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeTrackPosition provides a mock function with given fields: ctx, playlistTrack
func (_m *PlaylistTracksRepository) ChangeTrackPosition(ctx context.Context, playlistTrack *entity.PlaylistTrack) error {
	ret := _m.Called(ctx, playlistTrack)

	if len(ret) == 0 {
		panic("no return value specified for ChangeTrackPosition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PlaylistTrack) error); ok {
		r0 = rf(ctx, playlistTrack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistTracksRepository_ChangeTrackPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeTrackPosition'
type PlaylistTracksRepository_ChangeTrackPosition_Call struct {
	*mock.Call
}

// ChangeTrackPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistTrack *entity.PlaylistTrack
func (_e *PlaylistTracksRepository_Expecter) ChangeTrackPosition(ctx interface{}, playlistTrack interface{}) *PlaylistTracksRepository_ChangeTrackPosition_Call {
	return &PlaylistTracksRepository_ChangeTrackPosition_Call{Call: _e.mock.On("ChangeTrackPosition", ctx, playlistTrack)}
}

func (_c *PlaylistTracksRepository_ChangeTrackPosition_Call) Run(run func(ctx context.Context, playlistTrack *entity.PlaylistTrack)) *PlaylistTracksRepository_ChangeTrackPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.PlaylistTrack))
	})
	return _c
}

func (_c *PlaylistTracksRepository_ChangeTrackPosition_Call) Return(_a0 error) *PlaylistTracksRepository_ChangeTrackPosition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistTracksRepository_ChangeTrackPosition_Call) RunAndReturn(run func(context.Context, *entity.PlaylistTrack) error) *PlaylistTracksRepository_ChangeTrackPosition_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllTracksFromPlaylist provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistTracksRepository) DeleteAllTracksFromPlaylist(ctx context.Context, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllTracksFromPlaylist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllTracksFromPlaylist'
type PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call struct {
	*mock.Call
}

// DeleteAllTracksFromPlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistTracksRepository_Expecter) DeleteAllTracksFromPlaylist(ctx interface{}, playlistID interface{}) *PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call {
	return &PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call{Call: _e.mock.On("DeleteAllTracksFromPlaylist", ctx, playlistID)}
}

func (_c *PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call) Return(_a0 error) *PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PlaylistTracksRepository_DeleteAllTracksFromPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTrackFromPlaylist provides a mock function with given fields: ctx, playlistTrack
func (_m *PlaylistTracksRepository) DeleteTrackFromPlaylist(ctx context.Context, playlistTrack *entity.PlaylistTrack) error {
	ret := _m.Called(ctx, playlistTrack)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrackFromPlaylist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PlaylistTrack) error); ok {
		r0 = rf(ctx, playlistTrack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistTracksRepository_DeleteTrackFromPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrackFromPlaylist'
type PlaylistTracksRepository_DeleteTrackFromPlaylist_Call struct {
	*mock.Call
}

// DeleteTrackFromPlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistTrack *entity.PlaylistTrack
func (_e *PlaylistTracksRepository_Expecter) DeleteTrackFromPlaylist(ctx interface{}, playlistTrack interface{}) *PlaylistTracksRepository_DeleteTrackFromPlaylist_Call {
	return &PlaylistTracksRepository_DeleteTrackFromPlaylist_Call{Call: _e.mock.On("DeleteTrackFromPlaylist", ctx, playlistTrack)}
}

func (_c *PlaylistTracksRepository_DeleteTrackFromPlaylist_Call) Run(run func(ctx context.Context, playlistTrack *entity.PlaylistTrack)) *PlaylistTracksRepository_DeleteTrackFromPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.PlaylistTrack))
	})
	return _c
}

func (_c *PlaylistTracksRepository_DeleteTrackFromPlaylist_Call) Return(_a0 error) *PlaylistTracksRepository_DeleteTrackFromPlaylist_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistTracksRepository_DeleteTrackFromPlaylist_Call) RunAndReturn(run func(context.Context, *entity.PlaylistTrack) error) *PlaylistTracksRepository_DeleteTrackFromPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPlaylistTracks provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistTracksRepository) GetAllPlaylistTracks(ctx context.Context, playlistID uuid.UUID) ([]*entity.TrackMeta, error) {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPlaylistTracks")
	}

	var r0 []*entity.TrackMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.TrackMeta, error)); ok {
		return rf(ctx, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.TrackMeta); ok {
		r0 = rf(ctx, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TrackMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistTracksRepository_GetAllPlaylistTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPlaylistTracks'
type PlaylistTracksRepository_GetAllPlaylistTracks_Call struct {
	*mock.Call
}

// GetAllPlaylistTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistTracksRepository_Expecter) GetAllPlaylistTracks(ctx interface{}, playlistID interface{}) *PlaylistTracksRepository_GetAllPlaylistTracks_Call {
	return &PlaylistTracksRepository_GetAllPlaylistTracks_Call{Call: _e.mock.On("GetAllPlaylistTracks", ctx, playlistID)}
}

func (_c *PlaylistTracksRepository_GetAllPlaylistTracks_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistTracksRepository_GetAllPlaylistTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistTracksRepository_GetAllPlaylistTracks_Call) Return(_a0 []*entity.TrackMeta, _a1 error) *PlaylistTracksRepository_GetAllPlaylistTracks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistTracksRepository_GetAllPlaylistTracks_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.TrackMeta, error)) *PlaylistTracksRepository_GetAllPlaylistTracks_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistTracksRepository creates a new instance of PlaylistTracksRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistTracksRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistTracksRepository {
	mock := &PlaylistTracksRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
