// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistDeletionService is an autogenerated mock type for the PlaylistDeletionService type
type PlaylistDeletionService struct {
	mock.Mock
}

type PlaylistDeletionService_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistDeletionService) EXPECT() *PlaylistDeletionService_Expecter {
	return &PlaylistDeletionService_Expecter{mock: &_m.Mock}
}

// DeletePlaylist provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistDeletionService) DeletePlaylist(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlaylist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistDeletionService_DeletePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlaylist'
type PlaylistDeletionService_DeletePlaylist_Call struct {
	*mock.Call
}

// DeletePlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistDeletionService_Expecter) DeletePlaylist(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistDeletionService_DeletePlaylist_Call {
	return &PlaylistDeletionService_DeletePlaylist_Call{Call: _e.mock.On("DeletePlaylist", ctx, claims, playlistID)}
}

func (_c *PlaylistDeletionService_DeletePlaylist_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistDeletionService_DeletePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistDeletionService_DeletePlaylist_Call) Return(_a0 error) *PlaylistDeletionService_DeletePlaylist_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistDeletionService_DeletePlaylist_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *PlaylistDeletionService_DeletePlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistDeletionService creates a new instance of PlaylistDeletionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistDeletionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistDeletionService {
	mock := &PlaylistDeletionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
