// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistMetaService is an autogenerated mock type for the PlaylistMetaService type
type PlaylistMetaService struct {
	mock.Mock
}

type PlaylistMetaService_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistMetaService) EXPECT() *PlaylistMetaService_Expecter {
	return &PlaylistMetaService_Expecter{mock: &_m.Mock}
}

// CreateMeta provides a mock function with given fields: ctx, claims, _a2
func (_m *PlaylistMetaService) CreateMeta(ctx context.Context, claims *entity.Claims, _a2 *entity.PlaylistMeta) error {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.PlaylistMeta) error); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistMetaService_CreateMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMeta'
type PlaylistMetaService_CreateMeta_Call struct {
	*mock.Call
}

// CreateMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.PlaylistMeta
func (_e *PlaylistMetaService_Expecter) CreateMeta(ctx interface{}, claims interface{}, _a2 interface{}) *PlaylistMetaService_CreateMeta_Call {
	return &PlaylistMetaService_CreateMeta_Call{Call: _e.mock.On("CreateMeta", ctx, claims, _a2)}
}

func (_c *PlaylistMetaService_CreateMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.PlaylistMeta)) *PlaylistMetaService_CreateMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.PlaylistMeta))
	})
	return _c
}

func (_c *PlaylistMetaService_CreateMeta_Call) Return(_a0 error) *PlaylistMetaService_CreateMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistMetaService_CreateMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.PlaylistMeta) error) *PlaylistMetaService_CreateMeta_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMeta provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistMetaService) DeleteMeta(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistMetaService_DeleteMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMeta'
type PlaylistMetaService_DeleteMeta_Call struct {
	*mock.Call
}

// DeleteMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistMetaService_Expecter) DeleteMeta(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistMetaService_DeleteMeta_Call {
	return &PlaylistMetaService_DeleteMeta_Call{Call: _e.mock.On("DeleteMeta", ctx, claims, playlistID)}
}

func (_c *PlaylistMetaService_DeleteMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistMetaService_DeleteMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistMetaService_DeleteMeta_Call) Return(_a0 error) *PlaylistMetaService_DeleteMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistMetaService_DeleteMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *PlaylistMetaService_DeleteMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeta provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistMetaService) GetMeta(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) (*entity.PlaylistMeta, error) {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetMeta")
	}

	var r0 *entity.PlaylistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) (*entity.PlaylistMeta, error)); ok {
		return rf(ctx, claims, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) *entity.PlaylistMeta); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlaylistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistMetaService_GetMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeta'
type PlaylistMetaService_GetMeta_Call struct {
	*mock.Call
}

// GetMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistMetaService_Expecter) GetMeta(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistMetaService_GetMeta_Call {
	return &PlaylistMetaService_GetMeta_Call{Call: _e.mock.On("GetMeta", ctx, claims, playlistID)}
}

func (_c *PlaylistMetaService_GetMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistMetaService_GetMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistMetaService_GetMeta_Call) Return(_a0 *entity.PlaylistMeta, _a1 error) *PlaylistMetaService_GetMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistMetaService_GetMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) (*entity.PlaylistMeta, error)) *PlaylistMetaService_GetMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAllPlaylistsMeta provides a mock function with given fields: ctx, claims, userID
func (_m *PlaylistMetaService) GetUserAllPlaylistsMeta(ctx context.Context, claims *entity.Claims, userID uuid.UUID) ([]*entity.PlaylistMeta, error) {
	ret := _m.Called(ctx, claims, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAllPlaylistsMeta")
	}

	var r0 []*entity.PlaylistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) ([]*entity.PlaylistMeta, error)); ok {
		return rf(ctx, claims, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) []*entity.PlaylistMeta); ok {
		r0 = rf(ctx, claims, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PlaylistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistMetaService_GetUserAllPlaylistsMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAllPlaylistsMeta'
type PlaylistMetaService_GetUserAllPlaylistsMeta_Call struct {
	*mock.Call
}

// GetUserAllPlaylistsMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - userID uuid.UUID
func (_e *PlaylistMetaService_Expecter) GetUserAllPlaylistsMeta(ctx interface{}, claims interface{}, userID interface{}) *PlaylistMetaService_GetUserAllPlaylistsMeta_Call {
	return &PlaylistMetaService_GetUserAllPlaylistsMeta_Call{Call: _e.mock.On("GetUserAllPlaylistsMeta", ctx, claims, userID)}
}

func (_c *PlaylistMetaService_GetUserAllPlaylistsMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, userID uuid.UUID)) *PlaylistMetaService_GetUserAllPlaylistsMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistMetaService_GetUserAllPlaylistsMeta_Call) Return(_a0 []*entity.PlaylistMeta, _a1 error) *PlaylistMetaService_GetUserAllPlaylistsMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistMetaService_GetUserAllPlaylistsMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) ([]*entity.PlaylistMeta, error)) *PlaylistMetaService_GetUserAllPlaylistsMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMeta provides a mock function with given fields: ctx, claims, _a2
func (_m *PlaylistMetaService) UpdateMeta(ctx context.Context, claims *entity.Claims, _a2 *entity.PlaylistMeta) error {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.PlaylistMeta) error); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistMetaService_UpdateMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMeta'
type PlaylistMetaService_UpdateMeta_Call struct {
	*mock.Call
}

// UpdateMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.PlaylistMeta
func (_e *PlaylistMetaService_Expecter) UpdateMeta(ctx interface{}, claims interface{}, _a2 interface{}) *PlaylistMetaService_UpdateMeta_Call {
	return &PlaylistMetaService_UpdateMeta_Call{Call: _e.mock.On("UpdateMeta", ctx, claims, _a2)}
}

func (_c *PlaylistMetaService_UpdateMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.PlaylistMeta)) *PlaylistMetaService_UpdateMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.PlaylistMeta))
	})
	return _c
}

func (_c *PlaylistMetaService_UpdateMeta_Call) Return(_a0 error) *PlaylistMetaService_UpdateMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistMetaService_UpdateMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.PlaylistMeta) error) *PlaylistMetaService_UpdateMeta_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistMetaService creates a new instance of PlaylistMetaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistMetaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistMetaService {
	mock := &PlaylistMetaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
