// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistTrackService is an autogenerated mock type for the PlaylistTrackService type
type PlaylistTrackService struct {
	mock.Mock
}

type PlaylistTrackService_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistTrackService) EXPECT() *PlaylistTrackService_Expecter {
	return &PlaylistTrackService_Expecter{mock: &_m.Mock}
}

// AddTrack provides a mock function with given fields: ctx, claims, playlistTrack
func (_m *PlaylistTrackService) AddTrack(ctx context.Context, claims *entity.Claims, playlistTrack *entity.PlaylistTrack) error {
	ret := _m.Called(ctx, claims, playlistTrack)

	if len(ret) == 0 {
		panic("no return value specified for AddTrack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.PlaylistTrack) error); ok {
		r0 = rf(ctx, claims, playlistTrack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistTrackService_AddTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTrack'
type PlaylistTrackService_AddTrack_Call struct {
	*mock.Call
}

// AddTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistTrack *entity.PlaylistTrack
func (_e *PlaylistTrackService_Expecter) AddTrack(ctx interface{}, claims interface{}, playlistTrack interface{}) *PlaylistTrackService_AddTrack_Call {
	return &PlaylistTrackService_AddTrack_Call{Call: _e.mock.On("AddTrack", ctx, claims, playlistTrack)}
}

func (_c *PlaylistTrackService_AddTrack_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistTrack *entity.PlaylistTrack)) *PlaylistTrackService_AddTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.PlaylistTrack))
	})
	return _c
}

func (_c *PlaylistTrackService_AddTrack_Call) Return(_a0 error) *PlaylistTrackService_AddTrack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistTrackService_AddTrack_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.PlaylistTrack) error) *PlaylistTrackService_AddTrack_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeTrackPosition provides a mock function with given fields: ctx, claims, playlistTrack
func (_m *PlaylistTrackService) ChangeTrackPosition(ctx context.Context, claims *entity.Claims, playlistTrack *entity.PlaylistTrack) error {
	ret := _m.Called(ctx, claims, playlistTrack)

	if len(ret) == 0 {
		panic("no return value specified for ChangeTrackPosition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.PlaylistTrack) error); ok {
		r0 = rf(ctx, claims, playlistTrack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistTrackService_ChangeTrackPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeTrackPosition'
type PlaylistTrackService_ChangeTrackPosition_Call struct {
	*mock.Call
}

// ChangeTrackPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistTrack *entity.PlaylistTrack
func (_e *PlaylistTrackService_Expecter) ChangeTrackPosition(ctx interface{}, claims interface{}, playlistTrack interface{}) *PlaylistTrackService_ChangeTrackPosition_Call {
	return &PlaylistTrackService_ChangeTrackPosition_Call{Call: _e.mock.On("ChangeTrackPosition", ctx, claims, playlistTrack)}
}

func (_c *PlaylistTrackService_ChangeTrackPosition_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistTrack *entity.PlaylistTrack)) *PlaylistTrackService_ChangeTrackPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.PlaylistTrack))
	})
	return _c
}

func (_c *PlaylistTrackService_ChangeTrackPosition_Call) Return(_a0 error) *PlaylistTrackService_ChangeTrackPosition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistTrackService_ChangeTrackPosition_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.PlaylistTrack) error) *PlaylistTrackService_ChangeTrackPosition_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllTracks provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistTrackService) DeleteAllTracks(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllTracks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistTrackService_DeleteAllTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllTracks'
type PlaylistTrackService_DeleteAllTracks_Call struct {
	*mock.Call
}

// DeleteAllTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistTrackService_Expecter) DeleteAllTracks(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistTrackService_DeleteAllTracks_Call {
	return &PlaylistTrackService_DeleteAllTracks_Call{Call: _e.mock.On("DeleteAllTracks", ctx, claims, playlistID)}
}

func (_c *PlaylistTrackService_DeleteAllTracks_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistTrackService_DeleteAllTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistTrackService_DeleteAllTracks_Call) Return(_a0 error) *PlaylistTrackService_DeleteAllTracks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistTrackService_DeleteAllTracks_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *PlaylistTrackService_DeleteAllTracks_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTrack provides a mock function with given fields: ctx, claims, playlistTrack
func (_m *PlaylistTrackService) DeleteTrack(ctx context.Context, claims *entity.Claims, playlistTrack *entity.PlaylistTrack) error {
	ret := _m.Called(ctx, claims, playlistTrack)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.PlaylistTrack) error); ok {
		r0 = rf(ctx, claims, playlistTrack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistTrackService_DeleteTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrack'
type PlaylistTrackService_DeleteTrack_Call struct {
	*mock.Call
}

// DeleteTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistTrack *entity.PlaylistTrack
func (_e *PlaylistTrackService_Expecter) DeleteTrack(ctx interface{}, claims interface{}, playlistTrack interface{}) *PlaylistTrackService_DeleteTrack_Call {
	return &PlaylistTrackService_DeleteTrack_Call{Call: _e.mock.On("DeleteTrack", ctx, claims, playlistTrack)}
}

func (_c *PlaylistTrackService_DeleteTrack_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistTrack *entity.PlaylistTrack)) *PlaylistTrackService_DeleteTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.PlaylistTrack))
	})
	return _c
}

func (_c *PlaylistTrackService_DeleteTrack_Call) Return(_a0 error) *PlaylistTrackService_DeleteTrack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistTrackService_DeleteTrack_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.PlaylistTrack) error) *PlaylistTrackService_DeleteTrack_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTracks provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistTrackService) GetAllTracks(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) ([]*entity.TrackMeta, error) {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTracks")
	}

	var r0 []*entity.TrackMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) ([]*entity.TrackMeta, error)); ok {
		return rf(ctx, claims, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) []*entity.TrackMeta); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TrackMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistTrackService_GetAllTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTracks'
type PlaylistTrackService_GetAllTracks_Call struct {
	*mock.Call
}

// GetAllTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistTrackService_Expecter) GetAllTracks(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistTrackService_GetAllTracks_Call {
	return &PlaylistTrackService_GetAllTracks_Call{Call: _e.mock.On("GetAllTracks", ctx, claims, playlistID)}
}

func (_c *PlaylistTrackService_GetAllTracks_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistTrackService_GetAllTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistTrackService_GetAllTracks_Call) Return(tracks []*entity.TrackMeta, err error) *PlaylistTrackService_GetAllTracks_Call {
	_c.Call.Return(tracks, err)
	return _c
}

func (_c *PlaylistTrackService_GetAllTracks_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) ([]*entity.TrackMeta, error)) *PlaylistTrackService_GetAllTracks_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistTrackService creates a new instance of PlaylistTrackService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistTrackService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistTrackService {
	mock := &PlaylistTrackService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
