// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistAccessMetaDeleter is an autogenerated mock type for the PlaylistAccessMetaDeleter type
type PlaylistAccessMetaDeleter struct {
	mock.Mock
}

type PlaylistAccessMetaDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistAccessMetaDeleter) EXPECT() *PlaylistAccessMetaDeleter_Expecter {
	return &PlaylistAccessMetaDeleter_Expecter{mock: &_m.Mock}
}

// DeleteAccessMeta provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistAccessMetaDeleter) DeleteAccessMeta(ctx context.Context, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistAccessMetaDeleter_DeleteAccessMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessMeta'
type PlaylistAccessMetaDeleter_DeleteAccessMeta_Call struct {
	*mock.Call
}

// DeleteAccessMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistAccessMetaDeleter_Expecter) DeleteAccessMeta(ctx interface{}, playlistID interface{}) *PlaylistAccessMetaDeleter_DeleteAccessMeta_Call {
	return &PlaylistAccessMetaDeleter_DeleteAccessMeta_Call{Call: _e.mock.On("DeleteAccessMeta", ctx, playlistID)}
}

func (_c *PlaylistAccessMetaDeleter_DeleteAccessMeta_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistAccessMetaDeleter_DeleteAccessMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistAccessMetaDeleter_DeleteAccessMeta_Call) Return(_a0 error) *PlaylistAccessMetaDeleter_DeleteAccessMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistAccessMetaDeleter_DeleteAccessMeta_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PlaylistAccessMetaDeleter_DeleteAccessMeta_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistAccessMetaDeleter creates a new instance of PlaylistAccessMetaDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistAccessMetaDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistAccessMetaDeleter {
	mock := &PlaylistAccessMetaDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
