// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistPrivacyRepository is an autogenerated mock type for the PlaylistPrivacyRepository type
type PlaylistPrivacyRepository struct {
	mock.Mock
}

type PlaylistPrivacyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistPrivacyRepository) EXPECT() *PlaylistPrivacyRepository_Expecter {
	return &PlaylistPrivacyRepository_Expecter{mock: &_m.Mock}
}

// UpdatePrivacy provides a mock function with given fields: ctx, playlistID, isPrivate
func (_m *PlaylistPrivacyRepository) UpdatePrivacy(ctx context.Context, playlistID uuid.UUID, isPrivate bool) error {
	ret := _m.Called(ctx, playlistID, isPrivate)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrivacy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, playlistID, isPrivate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistPrivacyRepository_UpdatePrivacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePrivacy'
type PlaylistPrivacyRepository_UpdatePrivacy_Call struct {
	*mock.Call
}

// UpdatePrivacy is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
//   - isPrivate bool
func (_e *PlaylistPrivacyRepository_Expecter) UpdatePrivacy(ctx interface{}, playlistID interface{}, isPrivate interface{}) *PlaylistPrivacyRepository_UpdatePrivacy_Call {
	return &PlaylistPrivacyRepository_UpdatePrivacy_Call{Call: _e.mock.On("UpdatePrivacy", ctx, playlistID, isPrivate)}
}

func (_c *PlaylistPrivacyRepository_UpdatePrivacy_Call) Run(run func(ctx context.Context, playlistID uuid.UUID, isPrivate bool)) *PlaylistPrivacyRepository_UpdatePrivacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *PlaylistPrivacyRepository_UpdatePrivacy_Call) Return(_a0 error) *PlaylistPrivacyRepository_UpdatePrivacy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistPrivacyRepository_UpdatePrivacy_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *PlaylistPrivacyRepository_UpdatePrivacy_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistPrivacyRepository creates a new instance of PlaylistPrivacyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistPrivacyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistPrivacyRepository {
	mock := &PlaylistPrivacyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
