// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistCoverRepository is an autogenerated mock type for the PlaylistCoverRepository type
type PlaylistCoverRepository struct {
	mock.Mock
}

type PlaylistCoverRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistCoverRepository) EXPECT() *PlaylistCoverRepository_Expecter {
	return &PlaylistCoverRepository_Expecter{mock: &_m.Mock}
}

// DeleteCover provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistCoverRepository) DeleteCover(ctx context.Context, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistCoverRepository_DeleteCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCover'
type PlaylistCoverRepository_DeleteCover_Call struct {
	*mock.Call
}

// DeleteCover is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistCoverRepository_Expecter) DeleteCover(ctx interface{}, playlistID interface{}) *PlaylistCoverRepository_DeleteCover_Call {
	return &PlaylistCoverRepository_DeleteCover_Call{Call: _e.mock.On("DeleteCover", ctx, playlistID)}
}

func (_c *PlaylistCoverRepository_DeleteCover_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistCoverRepository_DeleteCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistCoverRepository_DeleteCover_Call) Return(_a0 error) *PlaylistCoverRepository_DeleteCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistCoverRepository_DeleteCover_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PlaylistCoverRepository_DeleteCover_Call {
	_c.Call.Return(run)
	return _c
}

// GetCover provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistCoverRepository) GetCover(ctx context.Context, playlistID uuid.UUID) (*entity.Cover, error) {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetCover")
	}

	var r0 *entity.Cover
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Cover, error)); ok {
		return rf(ctx, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Cover); ok {
		r0 = rf(ctx, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cover)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistCoverRepository_GetCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCover'
type PlaylistCoverRepository_GetCover_Call struct {
	*mock.Call
}

// GetCover is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistCoverRepository_Expecter) GetCover(ctx interface{}, playlistID interface{}) *PlaylistCoverRepository_GetCover_Call {
	return &PlaylistCoverRepository_GetCover_Call{Call: _e.mock.On("GetCover", ctx, playlistID)}
}

func (_c *PlaylistCoverRepository_GetCover_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistCoverRepository_GetCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistCoverRepository_GetCover_Call) Return(_a0 *entity.Cover, _a1 error) *PlaylistCoverRepository_GetCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistCoverRepository_GetCover_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Cover, error)) *PlaylistCoverRepository_GetCover_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCover provides a mock function with given fields: ctx, _a1
func (_m *PlaylistCoverRepository) SaveCover(ctx context.Context, _a1 *entity.Cover) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Cover) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistCoverRepository_SaveCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCover'
type PlaylistCoverRepository_SaveCover_Call struct {
	*mock.Call
}

// SaveCover is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entity.Cover
func (_e *PlaylistCoverRepository_Expecter) SaveCover(ctx interface{}, _a1 interface{}) *PlaylistCoverRepository_SaveCover_Call {
	return &PlaylistCoverRepository_SaveCover_Call{Call: _e.mock.On("SaveCover", ctx, _a1)}
}

func (_c *PlaylistCoverRepository_SaveCover_Call) Run(run func(ctx context.Context, _a1 *entity.Cover)) *PlaylistCoverRepository_SaveCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Cover))
	})
	return _c
}

func (_c *PlaylistCoverRepository_SaveCover_Call) Return(_a0 error) *PlaylistCoverRepository_SaveCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistCoverRepository_SaveCover_Call) RunAndReturn(run func(context.Context, *entity.Cover) error) *PlaylistCoverRepository_SaveCover_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistCoverRepository creates a new instance of PlaylistCoverRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistCoverRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistCoverRepository {
	mock := &PlaylistCoverRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
