// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistCoverService is an autogenerated mock type for the PlaylistCoverService type
type PlaylistCoverService struct {
	mock.Mock
}

type PlaylistCoverService_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistCoverService) EXPECT() *PlaylistCoverService_Expecter {
	return &PlaylistCoverService_Expecter{mock: &_m.Mock}
}

// DeleteCover provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistCoverService) DeleteCover(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistCoverService_DeleteCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCover'
type PlaylistCoverService_DeleteCover_Call struct {
	*mock.Call
}

// DeleteCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistCoverService_Expecter) DeleteCover(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistCoverService_DeleteCover_Call {
	return &PlaylistCoverService_DeleteCover_Call{Call: _e.mock.On("DeleteCover", ctx, claims, playlistID)}
}

func (_c *PlaylistCoverService_DeleteCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistCoverService_DeleteCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistCoverService_DeleteCover_Call) Return(_a0 error) *PlaylistCoverService_DeleteCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistCoverService_DeleteCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *PlaylistCoverService_DeleteCover_Call {
	_c.Call.Return(run)
	return _c
}

// GetCover provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistCoverService) GetCover(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) (*entity.Cover, error) {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetCover")
	}

	var r0 *entity.Cover
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) (*entity.Cover, error)); ok {
		return rf(ctx, claims, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) *entity.Cover); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cover)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistCoverService_GetCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCover'
type PlaylistCoverService_GetCover_Call struct {
	*mock.Call
}

// GetCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistCoverService_Expecter) GetCover(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistCoverService_GetCover_Call {
	return &PlaylistCoverService_GetCover_Call{Call: _e.mock.On("GetCover", ctx, claims, playlistID)}
}

func (_c *PlaylistCoverService_GetCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistCoverService_GetCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistCoverService_GetCover_Call) Return(_a0 *entity.Cover, _a1 error) *PlaylistCoverService_GetCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistCoverService_GetCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) (*entity.Cover, error)) *PlaylistCoverService_GetCover_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCover provides a mock function with given fields: ctx, claims, cover
func (_m *PlaylistCoverService) UploadCover(ctx context.Context, claims *entity.Claims, cover *entity.Cover) error {
	ret := _m.Called(ctx, claims, cover)

	if len(ret) == 0 {
		panic("no return value specified for UploadCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.Cover) error); ok {
		r0 = rf(ctx, claims, cover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistCoverService_UploadCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCover'
type PlaylistCoverService_UploadCover_Call struct {
	*mock.Call
}

// UploadCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - cover *entity.Cover
func (_e *PlaylistCoverService_Expecter) UploadCover(ctx interface{}, claims interface{}, cover interface{}) *PlaylistCoverService_UploadCover_Call {
	return &PlaylistCoverService_UploadCover_Call{Call: _e.mock.On("UploadCover", ctx, claims, cover)}
}

func (_c *PlaylistCoverService_UploadCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, cover *entity.Cover)) *PlaylistCoverService_UploadCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.Cover))
	})
	return _c
}

func (_c *PlaylistCoverService_UploadCover_Call) Return(_a0 error) *PlaylistCoverService_UploadCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistCoverService_UploadCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.Cover) error) *PlaylistCoverService_UploadCover_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistCoverService creates a new instance of PlaylistCoverService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistCoverService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistCoverService {
	mock := &PlaylistCoverService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
