// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistPrivacyChanger is an autogenerated mock type for the PlaylistPrivacyChanger type
type PlaylistPrivacyChanger struct {
	mock.Mock
}

type PlaylistPrivacyChanger_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistPrivacyChanger) EXPECT() *PlaylistPrivacyChanger_Expecter {
	return &PlaylistPrivacyChanger_Expecter{mock: &_m.Mock}
}

// ChangePrivacy provides a mock function with given fields: ctx, claims, playlistID, isPrivate
func (_m *PlaylistPrivacyChanger) ChangePrivacy(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID, isPrivate bool) error {
	ret := _m.Called(ctx, claims, playlistID, isPrivate)

	if len(ret) == 0 {
		panic("no return value specified for ChangePrivacy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, claims, playlistID, isPrivate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistPrivacyChanger_ChangePrivacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePrivacy'
type PlaylistPrivacyChanger_ChangePrivacy_Call struct {
	*mock.Call
}

// ChangePrivacy is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
//   - isPrivate bool
func (_e *PlaylistPrivacyChanger_Expecter) ChangePrivacy(ctx interface{}, claims interface{}, playlistID interface{}, isPrivate interface{}) *PlaylistPrivacyChanger_ChangePrivacy_Call {
	return &PlaylistPrivacyChanger_ChangePrivacy_Call{Call: _e.mock.On("ChangePrivacy", ctx, claims, playlistID, isPrivate)}
}

func (_c *PlaylistPrivacyChanger_ChangePrivacy_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID, isPrivate bool)) *PlaylistPrivacyChanger_ChangePrivacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *PlaylistPrivacyChanger_ChangePrivacy_Call) Return(_a0 error) *PlaylistPrivacyChanger_ChangePrivacy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistPrivacyChanger_ChangePrivacy_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID, bool) error) *PlaylistPrivacyChanger_ChangePrivacy_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistPrivacyChanger creates a new instance of PlaylistPrivacyChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistPrivacyChanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistPrivacyChanger {
	mock := &PlaylistPrivacyChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
