// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistFavoriteService is an autogenerated mock type for the PlaylistFavoriteService type
type PlaylistFavoriteService struct {
	mock.Mock
}

type PlaylistFavoriteService_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistFavoriteService) EXPECT() *PlaylistFavoriteService_Expecter {
	return &PlaylistFavoriteService_Expecter{mock: &_m.Mock}
}

// AddToUserFavorites provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistFavoriteService) AddToUserFavorites(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for AddToUserFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistFavoriteService_AddToUserFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToUserFavorites'
type PlaylistFavoriteService_AddToUserFavorites_Call struct {
	*mock.Call
}

// AddToUserFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteService_Expecter) AddToUserFavorites(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistFavoriteService_AddToUserFavorites_Call {
	return &PlaylistFavoriteService_AddToUserFavorites_Call{Call: _e.mock.On("AddToUserFavorites", ctx, claims, playlistID)}
}

func (_c *PlaylistFavoriteService_AddToUserFavorites_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistFavoriteService_AddToUserFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteService_AddToUserFavorites_Call) Return(_a0 error) *PlaylistFavoriteService_AddToUserFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistFavoriteService_AddToUserFavorites_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *PlaylistFavoriteService_AddToUserFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFromUserFavorites provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistFavoriteService) DeleteFromUserFavorites(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFromUserFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistFavoriteService_DeleteFromUserFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromUserFavorites'
type PlaylistFavoriteService_DeleteFromUserFavorites_Call struct {
	*mock.Call
}

// DeleteFromUserFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteService_Expecter) DeleteFromUserFavorites(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistFavoriteService_DeleteFromUserFavorites_Call {
	return &PlaylistFavoriteService_DeleteFromUserFavorites_Call{Call: _e.mock.On("DeleteFromUserFavorites", ctx, claims, playlistID)}
}

func (_c *PlaylistFavoriteService_DeleteFromUserFavorites_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistFavoriteService_DeleteFromUserFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteService_DeleteFromUserFavorites_Call) Return(_a0 error) *PlaylistFavoriteService_DeleteFromUserFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistFavoriteService_DeleteFromUserFavorites_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *PlaylistFavoriteService_DeleteFromUserFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserFavorites provides a mock function with given fields: ctx, claims
func (_m *PlaylistFavoriteService) GetUserFavorites(ctx context.Context, claims *entity.Claims) ([]*entity.PlaylistMeta, error) {
	ret := _m.Called(ctx, claims)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFavorites")
	}

	var r0 []*entity.PlaylistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims) ([]*entity.PlaylistMeta, error)); ok {
		return rf(ctx, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims) []*entity.PlaylistMeta); ok {
		r0 = rf(ctx, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PlaylistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims) error); ok {
		r1 = rf(ctx, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistFavoriteService_GetUserFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFavorites'
type PlaylistFavoriteService_GetUserFavorites_Call struct {
	*mock.Call
}

// GetUserFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
func (_e *PlaylistFavoriteService_Expecter) GetUserFavorites(ctx interface{}, claims interface{}) *PlaylistFavoriteService_GetUserFavorites_Call {
	return &PlaylistFavoriteService_GetUserFavorites_Call{Call: _e.mock.On("GetUserFavorites", ctx, claims)}
}

func (_c *PlaylistFavoriteService_GetUserFavorites_Call) Run(run func(ctx context.Context, claims *entity.Claims)) *PlaylistFavoriteService_GetUserFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims))
	})
	return _c
}

func (_c *PlaylistFavoriteService_GetUserFavorites_Call) Return(_a0 []*entity.PlaylistMeta, _a1 error) *PlaylistFavoriteService_GetUserFavorites_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistFavoriteService_GetUserFavorites_Call) RunAndReturn(run func(context.Context, *entity.Claims) ([]*entity.PlaylistMeta, error)) *PlaylistFavoriteService_GetUserFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// IsFavorite provides a mock function with given fields: ctx, claims, playlistID
func (_m *PlaylistFavoriteService) IsFavorite(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for IsFavorite")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) (bool, error)); ok {
		return rf(ctx, claims, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) bool); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistFavoriteService_IsFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFavorite'
type PlaylistFavoriteService_IsFavorite_Call struct {
	*mock.Call
}

// IsFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteService_Expecter) IsFavorite(ctx interface{}, claims interface{}, playlistID interface{}) *PlaylistFavoriteService_IsFavorite_Call {
	return &PlaylistFavoriteService_IsFavorite_Call{Call: _e.mock.On("IsFavorite", ctx, claims, playlistID)}
}

func (_c *PlaylistFavoriteService_IsFavorite_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *PlaylistFavoriteService_IsFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteService_IsFavorite_Call) Return(_a0 bool, _a1 error) *PlaylistFavoriteService_IsFavorite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistFavoriteService_IsFavorite_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) (bool, error)) *PlaylistFavoriteService_IsFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistFavoriteService creates a new instance of PlaylistFavoriteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistFavoriteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistFavoriteService {
	mock := &PlaylistFavoriteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
