// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistAccessRepository is an autogenerated mock type for the PlaylistAccessRepository type
type PlaylistAccessRepository struct {
	mock.Mock
}

type PlaylistAccessRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistAccessRepository) EXPECT() *PlaylistAccessRepository_Expecter {
	return &PlaylistAccessRepository_Expecter{mock: &_m.Mock}
}

// GetAccessMeta provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistAccessRepository) GetAccessMeta(ctx context.Context, playlistID uuid.UUID) (*entity.PlaylistAccessMeta, error) {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessMeta")
	}

	var r0 *entity.PlaylistAccessMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.PlaylistAccessMeta, error)); ok {
		return rf(ctx, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.PlaylistAccessMeta); ok {
		r0 = rf(ctx, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlaylistAccessMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistAccessRepository_GetAccessMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessMeta'
type PlaylistAccessRepository_GetAccessMeta_Call struct {
	*mock.Call
}

// GetAccessMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistAccessRepository_Expecter) GetAccessMeta(ctx interface{}, playlistID interface{}) *PlaylistAccessRepository_GetAccessMeta_Call {
	return &PlaylistAccessRepository_GetAccessMeta_Call{Call: _e.mock.On("GetAccessMeta", ctx, playlistID)}
}

func (_c *PlaylistAccessRepository_GetAccessMeta_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistAccessRepository_GetAccessMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistAccessRepository_GetAccessMeta_Call) Return(_a0 *entity.PlaylistAccessMeta, _a1 error) *PlaylistAccessRepository_GetAccessMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistAccessRepository_GetAccessMeta_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.PlaylistAccessMeta, error)) *PlaylistAccessRepository_GetAccessMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePrivacy provides a mock function with given fields: ctx, playlistID, isPrivate
func (_m *PlaylistAccessRepository) UpdatePrivacy(ctx context.Context, playlistID uuid.UUID, isPrivate bool) error {
	ret := _m.Called(ctx, playlistID, isPrivate)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrivacy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, playlistID, isPrivate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistAccessRepository_UpdatePrivacy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePrivacy'
type PlaylistAccessRepository_UpdatePrivacy_Call struct {
	*mock.Call
}

// UpdatePrivacy is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
//   - isPrivate bool
func (_e *PlaylistAccessRepository_Expecter) UpdatePrivacy(ctx interface{}, playlistID interface{}, isPrivate interface{}) *PlaylistAccessRepository_UpdatePrivacy_Call {
	return &PlaylistAccessRepository_UpdatePrivacy_Call{Call: _e.mock.On("UpdatePrivacy", ctx, playlistID, isPrivate)}
}

func (_c *PlaylistAccessRepository_UpdatePrivacy_Call) Run(run func(ctx context.Context, playlistID uuid.UUID, isPrivate bool)) *PlaylistAccessRepository_UpdatePrivacy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *PlaylistAccessRepository_UpdatePrivacy_Call) Return(_a0 error) *PlaylistAccessRepository_UpdatePrivacy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistAccessRepository_UpdatePrivacy_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *PlaylistAccessRepository_UpdatePrivacy_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistAccessRepository creates a new instance of PlaylistAccessRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistAccessRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistAccessRepository {
	mock := &PlaylistAccessRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
