// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistFavoriteRepository is an autogenerated mock type for the PlaylistFavoriteRepository type
type PlaylistFavoriteRepository struct {
	mock.Mock
}

type PlaylistFavoriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistFavoriteRepository) EXPECT() *PlaylistFavoriteRepository_Expecter {
	return &PlaylistFavoriteRepository_Expecter{mock: &_m.Mock}
}

// AddToFavorites provides a mock function with given fields: ctx, userID, playlistID
func (_m *PlaylistFavoriteRepository) AddToFavorites(ctx context.Context, userID uuid.UUID, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, userID, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for AddToFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistFavoriteRepository_AddToFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToFavorites'
type PlaylistFavoriteRepository_AddToFavorites_Call struct {
	*mock.Call
}

// AddToFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) AddToFavorites(ctx interface{}, userID interface{}, playlistID interface{}) *PlaylistFavoriteRepository_AddToFavorites_Call {
	return &PlaylistFavoriteRepository_AddToFavorites_Call{Call: _e.mock.On("AddToFavorites", ctx, userID, playlistID)}
}

func (_c *PlaylistFavoriteRepository_AddToFavorites_Call) Run(run func(ctx context.Context, userID uuid.UUID, playlistID uuid.UUID)) *PlaylistFavoriteRepository_AddToFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_AddToFavorites_Call) Return(_a0 error) *PlaylistFavoriteRepository_AddToFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistFavoriteRepository_AddToFavorites_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *PlaylistFavoriteRepository_AddToFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFromAllFavorites provides a mock function with given fields: ctx, playlistID, withOwner
func (_m *PlaylistFavoriteRepository) DeleteFromAllFavorites(ctx context.Context, playlistID uuid.UUID, withOwner bool) error {
	ret := _m.Called(ctx, playlistID, withOwner)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFromAllFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, playlistID, withOwner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistFavoriteRepository_DeleteFromAllFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromAllFavorites'
type PlaylistFavoriteRepository_DeleteFromAllFavorites_Call struct {
	*mock.Call
}

// DeleteFromAllFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
//   - withOwner bool
func (_e *PlaylistFavoriteRepository_Expecter) DeleteFromAllFavorites(ctx interface{}, playlistID interface{}, withOwner interface{}) *PlaylistFavoriteRepository_DeleteFromAllFavorites_Call {
	return &PlaylistFavoriteRepository_DeleteFromAllFavorites_Call{Call: _e.mock.On("DeleteFromAllFavorites", ctx, playlistID, withOwner)}
}

func (_c *PlaylistFavoriteRepository_DeleteFromAllFavorites_Call) Run(run func(ctx context.Context, playlistID uuid.UUID, withOwner bool)) *PlaylistFavoriteRepository_DeleteFromAllFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_DeleteFromAllFavorites_Call) Return(_a0 error) *PlaylistFavoriteRepository_DeleteFromAllFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistFavoriteRepository_DeleteFromAllFavorites_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *PlaylistFavoriteRepository_DeleteFromAllFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFromUserFavorites provides a mock function with given fields: ctx, userID, trackID
func (_m *PlaylistFavoriteRepository) DeleteFromUserFavorites(ctx context.Context, userID uuid.UUID, trackID uuid.UUID) error {
	ret := _m.Called(ctx, userID, trackID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFromUserFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistFavoriteRepository_DeleteFromUserFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromUserFavorites'
type PlaylistFavoriteRepository_DeleteFromUserFavorites_Call struct {
	*mock.Call
}

// DeleteFromUserFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - trackID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) DeleteFromUserFavorites(ctx interface{}, userID interface{}, trackID interface{}) *PlaylistFavoriteRepository_DeleteFromUserFavorites_Call {
	return &PlaylistFavoriteRepository_DeleteFromUserFavorites_Call{Call: _e.mock.On("DeleteFromUserFavorites", ctx, userID, trackID)}
}

func (_c *PlaylistFavoriteRepository_DeleteFromUserFavorites_Call) Run(run func(ctx context.Context, userID uuid.UUID, trackID uuid.UUID)) *PlaylistFavoriteRepository_DeleteFromUserFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_DeleteFromUserFavorites_Call) Return(_a0 error) *PlaylistFavoriteRepository_DeleteFromUserFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistFavoriteRepository_DeleteFromUserFavorites_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *PlaylistFavoriteRepository_DeleteFromUserFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserFavorites provides a mock function with given fields: ctx, userID
func (_m *PlaylistFavoriteRepository) GetUserFavorites(ctx context.Context, userID uuid.UUID) ([]*entity.PlaylistMeta, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFavorites")
	}

	var r0 []*entity.PlaylistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.PlaylistMeta, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.PlaylistMeta); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PlaylistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistFavoriteRepository_GetUserFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserFavorites'
type PlaylistFavoriteRepository_GetUserFavorites_Call struct {
	*mock.Call
}

// GetUserFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) GetUserFavorites(ctx interface{}, userID interface{}) *PlaylistFavoriteRepository_GetUserFavorites_Call {
	return &PlaylistFavoriteRepository_GetUserFavorites_Call{Call: _e.mock.On("GetUserFavorites", ctx, userID)}
}

func (_c *PlaylistFavoriteRepository_GetUserFavorites_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *PlaylistFavoriteRepository_GetUserFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_GetUserFavorites_Call) Return(_a0 []*entity.PlaylistMeta, _a1 error) *PlaylistFavoriteRepository_GetUserFavorites_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistFavoriteRepository_GetUserFavorites_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.PlaylistMeta, error)) *PlaylistFavoriteRepository_GetUserFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithFavoritePlaylist provides a mock function with given fields: ctx, playlistID, withOwner
func (_m *PlaylistFavoriteRepository) GetUsersWithFavoritePlaylist(ctx context.Context, playlistID uuid.UUID, withOwner bool) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, playlistID, withOwner)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithFavoritePlaylist")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) ([]uuid.UUID, error)); ok {
		return rf(ctx, playlistID, withOwner)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) []uuid.UUID); ok {
		r0 = rf(ctx, playlistID, withOwner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, playlistID, withOwner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithFavoritePlaylist'
type PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call struct {
	*mock.Call
}

// GetUsersWithFavoritePlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
//   - withOwner bool
func (_e *PlaylistFavoriteRepository_Expecter) GetUsersWithFavoritePlaylist(ctx interface{}, playlistID interface{}, withOwner interface{}) *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call {
	return &PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call{Call: _e.mock.On("GetUsersWithFavoritePlaylist", ctx, playlistID, withOwner)}
}

func (_c *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call) Run(run func(ctx context.Context, playlistID uuid.UUID, withOwner bool)) *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call) Return(_a0 []uuid.UUID, _a1 error) *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) ([]uuid.UUID, error)) *PlaylistFavoriteRepository_GetUsersWithFavoritePlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// IsFavorite provides a mock function with given fields: ctx, userID, playlistID
func (_m *PlaylistFavoriteRepository) IsFavorite(ctx context.Context, userID uuid.UUID, playlistID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for IsFavorite")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, userID, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID, playlistID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistFavoriteRepository_IsFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFavorite'
type PlaylistFavoriteRepository_IsFavorite_Call struct {
	*mock.Call
}

// IsFavorite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) IsFavorite(ctx interface{}, userID interface{}, playlistID interface{}) *PlaylistFavoriteRepository_IsFavorite_Call {
	return &PlaylistFavoriteRepository_IsFavorite_Call{Call: _e.mock.On("IsFavorite", ctx, userID, playlistID)}
}

func (_c *PlaylistFavoriteRepository_IsFavorite_Call) Run(run func(ctx context.Context, userID uuid.UUID, playlistID uuid.UUID)) *PlaylistFavoriteRepository_IsFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_IsFavorite_Call) Return(_a0 bool, _a1 error) *PlaylistFavoriteRepository_IsFavorite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistFavoriteRepository_IsFavorite_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *PlaylistFavoriteRepository_IsFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreAllFavorites provides a mock function with given fields: ctx, userIDs, playlistID
func (_m *PlaylistFavoriteRepository) RestoreAllFavorites(ctx context.Context, userIDs []uuid.UUID, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, userIDs, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreAllFavorites")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userIDs, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistFavoriteRepository_RestoreAllFavorites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreAllFavorites'
type PlaylistFavoriteRepository_RestoreAllFavorites_Call struct {
	*mock.Call
}

// RestoreAllFavorites is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []uuid.UUID
//   - playlistID uuid.UUID
func (_e *PlaylistFavoriteRepository_Expecter) RestoreAllFavorites(ctx interface{}, userIDs interface{}, playlistID interface{}) *PlaylistFavoriteRepository_RestoreAllFavorites_Call {
	return &PlaylistFavoriteRepository_RestoreAllFavorites_Call{Call: _e.mock.On("RestoreAllFavorites", ctx, userIDs, playlistID)}
}

func (_c *PlaylistFavoriteRepository_RestoreAllFavorites_Call) Run(run func(ctx context.Context, userIDs []uuid.UUID, playlistID uuid.UUID)) *PlaylistFavoriteRepository_RestoreAllFavorites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistFavoriteRepository_RestoreAllFavorites_Call) Return(_a0 error) *PlaylistFavoriteRepository_RestoreAllFavorites_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistFavoriteRepository_RestoreAllFavorites_Call) RunAndReturn(run func(context.Context, []uuid.UUID, uuid.UUID) error) *PlaylistFavoriteRepository_RestoreAllFavorites_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistFavoriteRepository creates a new instance of PlaylistFavoriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistFavoriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistFavoriteRepository {
	mock := &PlaylistFavoriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
