// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistMetaRepository is an autogenerated mock type for the PlaylistMetaRepository type
type PlaylistMetaRepository struct {
	mock.Mock
}

type PlaylistMetaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistMetaRepository) EXPECT() *PlaylistMetaRepository_Expecter {
	return &PlaylistMetaRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, playlist
func (_m *PlaylistMetaRepository) Create(ctx context.Context, playlist *entity.PlaylistMeta) error {
	ret := _m.Called(ctx, playlist)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PlaylistMeta) error); ok {
		r0 = rf(ctx, playlist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistMetaRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PlaylistMetaRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - playlist *entity.PlaylistMeta
func (_e *PlaylistMetaRepository_Expecter) Create(ctx interface{}, playlist interface{}) *PlaylistMetaRepository_Create_Call {
	return &PlaylistMetaRepository_Create_Call{Call: _e.mock.On("Create", ctx, playlist)}
}

func (_c *PlaylistMetaRepository_Create_Call) Run(run func(ctx context.Context, playlist *entity.PlaylistMeta)) *PlaylistMetaRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.PlaylistMeta))
	})
	return _c
}

func (_c *PlaylistMetaRepository_Create_Call) Return(_a0 error) *PlaylistMetaRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistMetaRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.PlaylistMeta) error) *PlaylistMetaRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistMetaRepository) Delete(ctx context.Context, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistMetaRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PlaylistMetaRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistMetaRepository_Expecter) Delete(ctx interface{}, playlistID interface{}) *PlaylistMetaRepository_Delete_Call {
	return &PlaylistMetaRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, playlistID)}
}

func (_c *PlaylistMetaRepository_Delete_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistMetaRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistMetaRepository_Delete_Call) Return(_a0 error) *PlaylistMetaRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistMetaRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *PlaylistMetaRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistMetaRepository) GetByID(ctx context.Context, playlistID uuid.UUID) (*entity.PlaylistMeta, error) {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.PlaylistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.PlaylistMeta, error)); ok {
		return rf(ctx, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.PlaylistMeta); ok {
		r0 = rf(ctx, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlaylistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistMetaRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PlaylistMetaRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID uuid.UUID
func (_e *PlaylistMetaRepository_Expecter) GetByID(ctx interface{}, playlistID interface{}) *PlaylistMetaRepository_GetByID_Call {
	return &PlaylistMetaRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, playlistID)}
}

func (_c *PlaylistMetaRepository_GetByID_Call) Run(run func(ctx context.Context, playlistID uuid.UUID)) *PlaylistMetaRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistMetaRepository_GetByID_Call) Return(_a0 *entity.PlaylistMeta, _a1 error) *PlaylistMetaRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistMetaRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.PlaylistMeta, error)) *PlaylistMetaRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function with given fields: ctx, userID
func (_m *PlaylistMetaRepository) GetByUser(ctx context.Context, userID uuid.UUID) ([]*entity.PlaylistMeta, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []*entity.PlaylistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.PlaylistMeta, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.PlaylistMeta); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PlaylistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistMetaRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type PlaylistMetaRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *PlaylistMetaRepository_Expecter) GetByUser(ctx interface{}, userID interface{}) *PlaylistMetaRepository_GetByUser_Call {
	return &PlaylistMetaRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userID)}
}

func (_c *PlaylistMetaRepository_GetByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *PlaylistMetaRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistMetaRepository_GetByUser_Call) Return(_a0 []*entity.PlaylistMeta, _a1 error) *PlaylistMetaRepository_GetByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistMetaRepository_GetByUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.PlaylistMeta, error)) *PlaylistMetaRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, playlist
func (_m *PlaylistMetaRepository) Update(ctx context.Context, playlist *entity.PlaylistMeta) error {
	ret := _m.Called(ctx, playlist)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.PlaylistMeta) error); ok {
		r0 = rf(ctx, playlist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistMetaRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PlaylistMetaRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - playlist *entity.PlaylistMeta
func (_e *PlaylistMetaRepository_Expecter) Update(ctx interface{}, playlist interface{}) *PlaylistMetaRepository_Update_Call {
	return &PlaylistMetaRepository_Update_Call{Call: _e.mock.On("Update", ctx, playlist)}
}

func (_c *PlaylistMetaRepository_Update_Call) Run(run func(ctx context.Context, playlist *entity.PlaylistMeta)) *PlaylistMetaRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.PlaylistMeta))
	})
	return _c
}

func (_c *PlaylistMetaRepository_Update_Call) Return(_a0 error) *PlaylistMetaRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistMetaRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.PlaylistMeta) error) *PlaylistMetaRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistMetaRepository creates a new instance of PlaylistMetaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistMetaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistMetaRepository {
	mock := &PlaylistMetaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
