// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistCoverDeletionService is an autogenerated mock type for the PlaylistCoverDeletionService type
type PlaylistCoverDeletionService struct {
	mock.Mock
}

type PlaylistCoverDeletionService_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistCoverDeletionService) EXPECT() *PlaylistCoverDeletionService_Expecter {
	return &PlaylistCoverDeletionService_Expecter{mock: &_m.Mock}
}

// DeleteCover provides a mock function with given fields: ctx, claims, objectID
func (_m *PlaylistCoverDeletionService) DeleteCover(ctx context.Context, claims *entity.Claims, objectID uuid.UUID) error {
	ret := _m.Called(ctx, claims, objectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, objectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistCoverDeletionService_DeleteCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCover'
type PlaylistCoverDeletionService_DeleteCover_Call struct {
	*mock.Call
}

// DeleteCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - objectID uuid.UUID
func (_e *PlaylistCoverDeletionService_Expecter) DeleteCover(ctx interface{}, claims interface{}, objectID interface{}) *PlaylistCoverDeletionService_DeleteCover_Call {
	return &PlaylistCoverDeletionService_DeleteCover_Call{Call: _e.mock.On("DeleteCover", ctx, claims, objectID)}
}

func (_c *PlaylistCoverDeletionService_DeleteCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, objectID uuid.UUID)) *PlaylistCoverDeletionService_DeleteCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistCoverDeletionService_DeleteCover_Call) Return(_a0 error) *PlaylistCoverDeletionService_DeleteCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistCoverDeletionService_DeleteCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *PlaylistCoverDeletionService_DeleteCover_Call {
	_c.Call.Return(run)
	return _c
}

// GetCover provides a mock function with given fields: ctx, claims, objectID
func (_m *PlaylistCoverDeletionService) GetCover(ctx context.Context, claims *entity.Claims, objectID uuid.UUID) (*entity.Cover, error) {
	ret := _m.Called(ctx, claims, objectID)

	if len(ret) == 0 {
		panic("no return value specified for GetCover")
	}

	var r0 *entity.Cover
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) (*entity.Cover, error)); ok {
		return rf(ctx, claims, objectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) *entity.Cover); ok {
		r0 = rf(ctx, claims, objectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Cover)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, objectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistCoverDeletionService_GetCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCover'
type PlaylistCoverDeletionService_GetCover_Call struct {
	*mock.Call
}

// GetCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - objectID uuid.UUID
func (_e *PlaylistCoverDeletionService_Expecter) GetCover(ctx interface{}, claims interface{}, objectID interface{}) *PlaylistCoverDeletionService_GetCover_Call {
	return &PlaylistCoverDeletionService_GetCover_Call{Call: _e.mock.On("GetCover", ctx, claims, objectID)}
}

func (_c *PlaylistCoverDeletionService_GetCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, objectID uuid.UUID)) *PlaylistCoverDeletionService_GetCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *PlaylistCoverDeletionService_GetCover_Call) Return(_a0 *entity.Cover, _a1 error) *PlaylistCoverDeletionService_GetCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistCoverDeletionService_GetCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) (*entity.Cover, error)) *PlaylistCoverDeletionService_GetCover_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCover provides a mock function with given fields: ctx, claims, cover
func (_m *PlaylistCoverDeletionService) UploadCover(ctx context.Context, claims *entity.Claims, cover *entity.Cover) error {
	ret := _m.Called(ctx, claims, cover)

	if len(ret) == 0 {
		panic("no return value specified for UploadCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.Cover) error); ok {
		r0 = rf(ctx, claims, cover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlaylistCoverDeletionService_UploadCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCover'
type PlaylistCoverDeletionService_UploadCover_Call struct {
	*mock.Call
}

// UploadCover is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - cover *entity.Cover
func (_e *PlaylistCoverDeletionService_Expecter) UploadCover(ctx interface{}, claims interface{}, cover interface{}) *PlaylistCoverDeletionService_UploadCover_Call {
	return &PlaylistCoverDeletionService_UploadCover_Call{Call: _e.mock.On("UploadCover", ctx, claims, cover)}
}

func (_c *PlaylistCoverDeletionService_UploadCover_Call) Run(run func(ctx context.Context, claims *entity.Claims, cover *entity.Cover)) *PlaylistCoverDeletionService_UploadCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.Cover))
	})
	return _c
}

func (_c *PlaylistCoverDeletionService_UploadCover_Call) Return(_a0 error) *PlaylistCoverDeletionService_UploadCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PlaylistCoverDeletionService_UploadCover_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.Cover) error) *PlaylistCoverDeletionService_UploadCover_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistCoverDeletionService creates a new instance of PlaylistCoverDeletionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistCoverDeletionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistCoverDeletionService {
	mock := &PlaylistCoverDeletionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
