// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlaylistAggregator is an autogenerated mock type for the PlaylistAggregator type
type PlaylistAggregator struct {
	mock.Mock
}

type PlaylistAggregator_Expecter struct {
	mock *mock.Mock
}

func (_m *PlaylistAggregator) EXPECT() *PlaylistAggregator_Expecter {
	return &PlaylistAggregator_Expecter{mock: &_m.Mock}
}

// GetPlaylists provides a mock function with given fields: ctx, claims, playlists
func (_m *PlaylistAggregator) GetPlaylists(ctx context.Context, claims *entity.Claims, playlists ...*entity.PlaylistMeta) ([]*entity.PlaylistMetaAggregated, error) {
	_va := make([]interface{}, len(playlists))
	for _i := range playlists {
		_va[_i] = playlists[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, claims)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPlaylists")
	}

	var r0 []*entity.PlaylistMetaAggregated
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, ...*entity.PlaylistMeta) ([]*entity.PlaylistMetaAggregated, error)); ok {
		return rf(ctx, claims, playlists...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, ...*entity.PlaylistMeta) []*entity.PlaylistMetaAggregated); ok {
		r0 = rf(ctx, claims, playlists...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PlaylistMetaAggregated)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, ...*entity.PlaylistMeta) error); ok {
		r1 = rf(ctx, claims, playlists...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistAggregator_GetPlaylists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlaylists'
type PlaylistAggregator_GetPlaylists_Call struct {
	*mock.Call
}

// GetPlaylists is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlists ...*entity.PlaylistMeta
func (_e *PlaylistAggregator_Expecter) GetPlaylists(ctx interface{}, claims interface{}, playlists ...interface{}) *PlaylistAggregator_GetPlaylists_Call {
	return &PlaylistAggregator_GetPlaylists_Call{Call: _e.mock.On("GetPlaylists",
		append([]interface{}{ctx, claims}, playlists...)...)}
}

func (_c *PlaylistAggregator_GetPlaylists_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlists ...*entity.PlaylistMeta)) *PlaylistAggregator_GetPlaylists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*entity.PlaylistMeta, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(*entity.PlaylistMeta)
			}
		}
		run(args[0].(context.Context), args[1].(*entity.Claims), variadicArgs...)
	})
	return _c
}

func (_c *PlaylistAggregator_GetPlaylists_Call) Return(_a0 []*entity.PlaylistMetaAggregated, _a1 error) *PlaylistAggregator_GetPlaylists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistAggregator_GetPlaylists_Call) RunAndReturn(run func(context.Context, *entity.Claims, ...*entity.PlaylistMeta) ([]*entity.PlaylistMetaAggregated, error)) *PlaylistAggregator_GetPlaylists_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlaylistsByIDs provides a mock function with given fields: ctx, claims, playlistIDs
func (_m *PlaylistAggregator) GetPlaylistsByIDs(ctx context.Context, claims *entity.Claims, playlistIDs ...uuid.UUID) ([]*entity.PlaylistMetaAggregated, error) {
	_va := make([]interface{}, len(playlistIDs))
	for _i := range playlistIDs {
		_va[_i] = playlistIDs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, claims)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPlaylistsByIDs")
	}

	var r0 []*entity.PlaylistMetaAggregated
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, ...uuid.UUID) ([]*entity.PlaylistMetaAggregated, error)); ok {
		return rf(ctx, claims, playlistIDs...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, ...uuid.UUID) []*entity.PlaylistMetaAggregated); ok {
		r0 = rf(ctx, claims, playlistIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PlaylistMetaAggregated)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, ...uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistIDs...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaylistAggregator_GetPlaylistsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlaylistsByIDs'
type PlaylistAggregator_GetPlaylistsByIDs_Call struct {
	*mock.Call
}

// GetPlaylistsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistIDs ...uuid.UUID
func (_e *PlaylistAggregator_Expecter) GetPlaylistsByIDs(ctx interface{}, claims interface{}, playlistIDs ...interface{}) *PlaylistAggregator_GetPlaylistsByIDs_Call {
	return &PlaylistAggregator_GetPlaylistsByIDs_Call{Call: _e.mock.On("GetPlaylistsByIDs",
		append([]interface{}{ctx, claims}, playlistIDs...)...)}
}

func (_c *PlaylistAggregator_GetPlaylistsByIDs_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistIDs ...uuid.UUID)) *PlaylistAggregator_GetPlaylistsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]uuid.UUID, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(uuid.UUID)
			}
		}
		run(args[0].(context.Context), args[1].(*entity.Claims), variadicArgs...)
	})
	return _c
}

func (_c *PlaylistAggregator_GetPlaylistsByIDs_Call) Return(_a0 []*entity.PlaylistMetaAggregated, _a1 error) *PlaylistAggregator_GetPlaylistsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PlaylistAggregator_GetPlaylistsByIDs_Call) RunAndReturn(run func(context.Context, *entity.Claims, ...uuid.UUID) ([]*entity.PlaylistMetaAggregated, error)) *PlaylistAggregator_GetPlaylistsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewPlaylistAggregator creates a new instance of PlaylistAggregator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistAggregator(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistAggregator {
	mock := &PlaylistAggregator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
