// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// RoutersRegistrator is an autogenerated mock type for the RoutersRegistrator type
type RoutersRegistrator struct {
	mock.Mock
}

type RoutersRegistrator_Expecter struct {
	mock *mock.Mock
}

func (_m *RoutersRegistrator) EXPECT() *RoutersRegistrator_Expecter {
	return &RoutersRegistrator_Expecter{mock: &_m.Mock}
}

// RegisterRoutes provides a mock function with given fields: _a0
func (_m *RoutersRegistrator) RegisterRoutes(_a0 *gin.RouterGroup) {
	_m.Called(_a0)
}

// RoutersRegistrator_RegisterRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRoutes'
type RoutersRegistrator_RegisterRoutes_Call struct {
	*mock.Call
}

// RegisterRoutes is a helper method to define mock.On call
//   - _a0 *gin.RouterGroup
func (_e *RoutersRegistrator_Expecter) RegisterRoutes(_a0 interface{}) *RoutersRegistrator_RegisterRoutes_Call {
	return &RoutersRegistrator_RegisterRoutes_Call{Call: _e.mock.On("RegisterRoutes", _a0)}
}

func (_c *RoutersRegistrator_RegisterRoutes_Call) Run(run func(_a0 *gin.RouterGroup)) *RoutersRegistrator_RegisterRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.RouterGroup))
	})
	return _c
}

func (_c *RoutersRegistrator_RegisterRoutes_Call) Return() *RoutersRegistrator_RegisterRoutes_Call {
	_c.Call.Return()
	return _c
}

func (_c *RoutersRegistrator_RegisterRoutes_Call) RunAndReturn(run func(*gin.RouterGroup)) *RoutersRegistrator_RegisterRoutes_Call {
	_c.Run(run)
	return _c
}

// NewRoutersRegistrator creates a new instance of RoutersRegistrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoutersRegistrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoutersRegistrator {
	mock := &RoutersRegistrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
