// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// SearchRepository is an autogenerated mock type for the SearchRepository type
type SearchRepository struct {
	mock.Mock
}

type SearchRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SearchRepository) EXPECT() *SearchRepository_Expecter {
	return &SearchRepository_Expecter{mock: &_m.Mock}
}

// SearchAlbums provides a mock function with given fields: ctx, req
func (_m *SearchRepository) SearchAlbums(ctx context.Context, req *entity.SearchRequest) ([]*entity.AlbumMeta, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchAlbums")
	}

	var r0 []*entity.AlbumMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) ([]*entity.AlbumMeta, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) []*entity.AlbumMeta); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AlbumMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchRepository_SearchAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAlbums'
type SearchRepository_SearchAlbums_Call struct {
	*mock.Call
}

// SearchAlbums is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.SearchRequest
func (_e *SearchRepository_Expecter) SearchAlbums(ctx interface{}, req interface{}) *SearchRepository_SearchAlbums_Call {
	return &SearchRepository_SearchAlbums_Call{Call: _e.mock.On("SearchAlbums", ctx, req)}
}

func (_c *SearchRepository_SearchAlbums_Call) Run(run func(ctx context.Context, req *entity.SearchRequest)) *SearchRepository_SearchAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SearchRequest))
	})
	return _c
}

func (_c *SearchRepository_SearchAlbums_Call) Return(_a0 []*entity.AlbumMeta, _a1 error) *SearchRepository_SearchAlbums_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchRepository_SearchAlbums_Call) RunAndReturn(run func(context.Context, *entity.SearchRequest) ([]*entity.AlbumMeta, error)) *SearchRepository_SearchAlbums_Call {
	_c.Call.Return(run)
	return _c
}

// SearchArtists provides a mock function with given fields: ctx, req
func (_m *SearchRepository) SearchArtists(ctx context.Context, req *entity.SearchRequest) ([]*entity.ArtistMeta, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchArtists")
	}

	var r0 []*entity.ArtistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) ([]*entity.ArtistMeta, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) []*entity.ArtistMeta); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ArtistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchRepository_SearchArtists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchArtists'
type SearchRepository_SearchArtists_Call struct {
	*mock.Call
}

// SearchArtists is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.SearchRequest
func (_e *SearchRepository_Expecter) SearchArtists(ctx interface{}, req interface{}) *SearchRepository_SearchArtists_Call {
	return &SearchRepository_SearchArtists_Call{Call: _e.mock.On("SearchArtists", ctx, req)}
}

func (_c *SearchRepository_SearchArtists_Call) Run(run func(ctx context.Context, req *entity.SearchRequest)) *SearchRepository_SearchArtists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SearchRequest))
	})
	return _c
}

func (_c *SearchRepository_SearchArtists_Call) Return(_a0 []*entity.ArtistMeta, _a1 error) *SearchRepository_SearchArtists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchRepository_SearchArtists_Call) RunAndReturn(run func(context.Context, *entity.SearchRequest) ([]*entity.ArtistMeta, error)) *SearchRepository_SearchArtists_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPlaylists provides a mock function with given fields: ctx, req
func (_m *SearchRepository) SearchPlaylists(ctx context.Context, req *entity.SearchRequest) ([]*entity.PlaylistMeta, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchPlaylists")
	}

	var r0 []*entity.PlaylistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) ([]*entity.PlaylistMeta, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) []*entity.PlaylistMeta); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PlaylistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchRepository_SearchPlaylists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPlaylists'
type SearchRepository_SearchPlaylists_Call struct {
	*mock.Call
}

// SearchPlaylists is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.SearchRequest
func (_e *SearchRepository_Expecter) SearchPlaylists(ctx interface{}, req interface{}) *SearchRepository_SearchPlaylists_Call {
	return &SearchRepository_SearchPlaylists_Call{Call: _e.mock.On("SearchPlaylists", ctx, req)}
}

func (_c *SearchRepository_SearchPlaylists_Call) Run(run func(ctx context.Context, req *entity.SearchRequest)) *SearchRepository_SearchPlaylists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SearchRequest))
	})
	return _c
}

func (_c *SearchRepository_SearchPlaylists_Call) Return(_a0 []*entity.PlaylistMeta, _a1 error) *SearchRepository_SearchPlaylists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchRepository_SearchPlaylists_Call) RunAndReturn(run func(context.Context, *entity.SearchRequest) ([]*entity.PlaylistMeta, error)) *SearchRepository_SearchPlaylists_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTracks provides a mock function with given fields: ctx, req
func (_m *SearchRepository) SearchTracks(ctx context.Context, req *entity.SearchRequest) ([]*entity.TrackMeta, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchTracks")
	}

	var r0 []*entity.TrackMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) ([]*entity.TrackMeta, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) []*entity.TrackMeta); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TrackMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchRepository_SearchTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTracks'
type SearchRepository_SearchTracks_Call struct {
	*mock.Call
}

// SearchTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.SearchRequest
func (_e *SearchRepository_Expecter) SearchTracks(ctx interface{}, req interface{}) *SearchRepository_SearchTracks_Call {
	return &SearchRepository_SearchTracks_Call{Call: _e.mock.On("SearchTracks", ctx, req)}
}

func (_c *SearchRepository_SearchTracks_Call) Run(run func(ctx context.Context, req *entity.SearchRequest)) *SearchRepository_SearchTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SearchRequest))
	})
	return _c
}

func (_c *SearchRepository_SearchTracks_Call) Return(_a0 []*entity.TrackMeta, _a1 error) *SearchRepository_SearchTracks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchRepository_SearchTracks_Call) RunAndReturn(run func(context.Context, *entity.SearchRequest) ([]*entity.TrackMeta, error)) *SearchRepository_SearchTracks_Call {
	_c.Call.Return(run)
	return _c
}

// NewSearchRepository creates a new instance of SearchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchRepository {
	mock := &SearchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
