// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// SearchService is an autogenerated mock type for the SearchService type
type SearchService struct {
	mock.Mock
}

type SearchService_Expecter struct {
	mock *mock.Mock
}

func (_m *SearchService) EXPECT() *SearchService_Expecter {
	return &SearchService_Expecter{mock: &_m.Mock}
}

// SearchAlbums provides a mock function with given fields: ctx, request
func (_m *SearchService) SearchAlbums(ctx context.Context, request *entity.SearchRequest) ([]*entity.AlbumMeta, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SearchAlbums")
	}

	var r0 []*entity.AlbumMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) ([]*entity.AlbumMeta, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) []*entity.AlbumMeta); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AlbumMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.SearchRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchService_SearchAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAlbums'
type SearchService_SearchAlbums_Call struct {
	*mock.Call
}

// SearchAlbums is a helper method to define mock.On call
//   - ctx context.Context
//   - request *entity.SearchRequest
func (_e *SearchService_Expecter) SearchAlbums(ctx interface{}, request interface{}) *SearchService_SearchAlbums_Call {
	return &SearchService_SearchAlbums_Call{Call: _e.mock.On("SearchAlbums", ctx, request)}
}

func (_c *SearchService_SearchAlbums_Call) Run(run func(ctx context.Context, request *entity.SearchRequest)) *SearchService_SearchAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SearchRequest))
	})
	return _c
}

func (_c *SearchService_SearchAlbums_Call) Return(_a0 []*entity.AlbumMeta, _a1 error) *SearchService_SearchAlbums_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchService_SearchAlbums_Call) RunAndReturn(run func(context.Context, *entity.SearchRequest) ([]*entity.AlbumMeta, error)) *SearchService_SearchAlbums_Call {
	_c.Call.Return(run)
	return _c
}

// SearchArtists provides a mock function with given fields: ctx, request
func (_m *SearchService) SearchArtists(ctx context.Context, request *entity.SearchRequest) ([]*entity.ArtistMeta, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SearchArtists")
	}

	var r0 []*entity.ArtistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) ([]*entity.ArtistMeta, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) []*entity.ArtistMeta); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ArtistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.SearchRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchService_SearchArtists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchArtists'
type SearchService_SearchArtists_Call struct {
	*mock.Call
}

// SearchArtists is a helper method to define mock.On call
//   - ctx context.Context
//   - request *entity.SearchRequest
func (_e *SearchService_Expecter) SearchArtists(ctx interface{}, request interface{}) *SearchService_SearchArtists_Call {
	return &SearchService_SearchArtists_Call{Call: _e.mock.On("SearchArtists", ctx, request)}
}

func (_c *SearchService_SearchArtists_Call) Run(run func(ctx context.Context, request *entity.SearchRequest)) *SearchService_SearchArtists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SearchRequest))
	})
	return _c
}

func (_c *SearchService_SearchArtists_Call) Return(_a0 []*entity.ArtistMeta, _a1 error) *SearchService_SearchArtists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchService_SearchArtists_Call) RunAndReturn(run func(context.Context, *entity.SearchRequest) ([]*entity.ArtistMeta, error)) *SearchService_SearchArtists_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPlaylists provides a mock function with given fields: ctx, claims, request
func (_m *SearchService) SearchPlaylists(ctx context.Context, claims *entity.Claims, request *entity.SearchRequest) ([]*entity.PlaylistMeta, error) {
	ret := _m.Called(ctx, claims, request)

	if len(ret) == 0 {
		panic("no return value specified for SearchPlaylists")
	}

	var r0 []*entity.PlaylistMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.SearchRequest) ([]*entity.PlaylistMeta, error)); ok {
		return rf(ctx, claims, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.SearchRequest) []*entity.PlaylistMeta); ok {
		r0 = rf(ctx, claims, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.PlaylistMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, *entity.SearchRequest) error); ok {
		r1 = rf(ctx, claims, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchService_SearchPlaylists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPlaylists'
type SearchService_SearchPlaylists_Call struct {
	*mock.Call
}

// SearchPlaylists is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - request *entity.SearchRequest
func (_e *SearchService_Expecter) SearchPlaylists(ctx interface{}, claims interface{}, request interface{}) *SearchService_SearchPlaylists_Call {
	return &SearchService_SearchPlaylists_Call{Call: _e.mock.On("SearchPlaylists", ctx, claims, request)}
}

func (_c *SearchService_SearchPlaylists_Call) Run(run func(ctx context.Context, claims *entity.Claims, request *entity.SearchRequest)) *SearchService_SearchPlaylists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.SearchRequest))
	})
	return _c
}

func (_c *SearchService_SearchPlaylists_Call) Return(_a0 []*entity.PlaylistMeta, _a1 error) *SearchService_SearchPlaylists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchService_SearchPlaylists_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.SearchRequest) ([]*entity.PlaylistMeta, error)) *SearchService_SearchPlaylists_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTracks provides a mock function with given fields: ctx, request
func (_m *SearchService) SearchTracks(ctx context.Context, request *entity.SearchRequest) ([]*entity.TrackMeta, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SearchTracks")
	}

	var r0 []*entity.TrackMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) ([]*entity.TrackMeta, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.SearchRequest) []*entity.TrackMeta); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TrackMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.SearchRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchService_SearchTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTracks'
type SearchService_SearchTracks_Call struct {
	*mock.Call
}

// SearchTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - request *entity.SearchRequest
func (_e *SearchService_Expecter) SearchTracks(ctx interface{}, request interface{}) *SearchService_SearchTracks_Call {
	return &SearchService_SearchTracks_Call{Call: _e.mock.On("SearchTracks", ctx, request)}
}

func (_c *SearchService_SearchTracks_Call) Run(run func(ctx context.Context, request *entity.SearchRequest)) *SearchService_SearchTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.SearchRequest))
	})
	return _c
}

func (_c *SearchService_SearchTracks_Call) Return(_a0 []*entity.TrackMeta, _a1 error) *SearchService_SearchTracks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SearchService_SearchTracks_Call) RunAndReturn(run func(context.Context, *entity.SearchRequest) ([]*entity.TrackMeta, error)) *SearchService_SearchTracks_Call {
	_c.Call.Return(run)
	return _c
}

// NewSearchService creates a new instance of SearchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchService {
	mock := &SearchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
