// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SegmentStatRepository is an autogenerated mock type for the SegmentStatRepository type
type SegmentStatRepository struct {
	mock.Mock
}

type SegmentStatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SegmentStatRepository) EXPECT() *SegmentStatRepository_Expecter {
	return &SegmentStatRepository_Expecter{mock: &_m.Mock}
}

// GetSegments provides a mock function with given fields: ctx, trackID
func (_m *SegmentStatRepository) GetSegments(ctx context.Context, trackID uuid.UUID) ([]*entity.Segment, error) {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for GetSegments")
	}

	var r0 []*entity.Segment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Segment, error)); ok {
		return rf(ctx, trackID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Segment); ok {
		r0 = rf(ctx, trackID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Segment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, trackID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SegmentStatRepository_GetSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSegments'
type SegmentStatRepository_GetSegments_Call struct {
	*mock.Call
}

// GetSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
func (_e *SegmentStatRepository_Expecter) GetSegments(ctx interface{}, trackID interface{}) *SegmentStatRepository_GetSegments_Call {
	return &SegmentStatRepository_GetSegments_Call{Call: _e.mock.On("GetSegments", ctx, trackID)}
}

func (_c *SegmentStatRepository_GetSegments_Call) Run(run func(ctx context.Context, trackID uuid.UUID)) *SegmentStatRepository_GetSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SegmentStatRepository_GetSegments_Call) Return(_a0 []*entity.Segment, _a1 error) *SegmentStatRepository_GetSegments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SegmentStatRepository_GetSegments_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Segment, error)) *SegmentStatRepository_GetSegments_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementTotalStreams provides a mock function with given fields: ctx, trackID, segmentsIdxs
func (_m *SegmentStatRepository) IncrementTotalStreams(ctx context.Context, trackID uuid.UUID, segmentsIdxs []int) error {
	ret := _m.Called(ctx, trackID, segmentsIdxs)

	if len(ret) == 0 {
		panic("no return value specified for IncrementTotalStreams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []int) error); ok {
		r0 = rf(ctx, trackID, segmentsIdxs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SegmentStatRepository_IncrementTotalStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementTotalStreams'
type SegmentStatRepository_IncrementTotalStreams_Call struct {
	*mock.Call
}

// IncrementTotalStreams is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
//   - segmentsIdxs []int
func (_e *SegmentStatRepository_Expecter) IncrementTotalStreams(ctx interface{}, trackID interface{}, segmentsIdxs interface{}) *SegmentStatRepository_IncrementTotalStreams_Call {
	return &SegmentStatRepository_IncrementTotalStreams_Call{Call: _e.mock.On("IncrementTotalStreams", ctx, trackID, segmentsIdxs)}
}

func (_c *SegmentStatRepository_IncrementTotalStreams_Call) Run(run func(ctx context.Context, trackID uuid.UUID, segmentsIdxs []int)) *SegmentStatRepository_IncrementTotalStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]int))
	})
	return _c
}

func (_c *SegmentStatRepository_IncrementTotalStreams_Call) Return(_a0 error) *SegmentStatRepository_IncrementTotalStreams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SegmentStatRepository_IncrementTotalStreams_Call) RunAndReturn(run func(context.Context, uuid.UUID, []int) error) *SegmentStatRepository_IncrementTotalStreams_Call {
	_c.Call.Return(run)
	return _c
}

// NewSegmentStatRepository creates a new instance of SegmentStatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSegmentStatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SegmentStatRepository {
	mock := &SegmentStatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
