// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TablePrinter is an autogenerated mock type for the TablePrinter type
type TablePrinter struct {
	mock.Mock
}

type TablePrinter_Expecter struct {
	mock *mock.Mock
}

func (_m *TablePrinter) EXPECT() *TablePrinter_Expecter {
	return &TablePrinter_Expecter{mock: &_m.Mock}
}

// PrintTable provides a mock function with given fields: headers, rows
func (_m *TablePrinter) PrintTable(headers []string, rows [][]interface{}) {
	_m.Called(headers, rows)
}

// TablePrinter_PrintTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintTable'
type TablePrinter_PrintTable_Call struct {
	*mock.Call
}

// PrintTable is a helper method to define mock.On call
//   - headers []string
//   - rows [][]interface{}
func (_e *TablePrinter_Expecter) PrintTable(headers interface{}, rows interface{}) *TablePrinter_PrintTable_Call {
	return &TablePrinter_PrintTable_Call{Call: _e.mock.On("PrintTable", headers, rows)}
}

func (_c *TablePrinter_PrintTable_Call) Run(run func(headers []string, rows [][]interface{})) *TablePrinter_PrintTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].([][]interface{}))
	})
	return _c
}

func (_c *TablePrinter_PrintTable_Call) Return() *TablePrinter_PrintTable_Call {
	_c.Call.Return()
	return _c
}

func (_c *TablePrinter_PrintTable_Call) RunAndReturn(run func([]string, [][]interface{})) *TablePrinter_PrintTable_Call {
	_c.Run(run)
	return _c
}

// NewTablePrinter creates a new instance of TablePrinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTablePrinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TablePrinter {
	mock := &TablePrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
