// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TrackStatRepository is an autogenerated mock type for the TrackStatRepository type
type TrackStatRepository struct {
	mock.Mock
}

type TrackStatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TrackStatRepository) EXPECT() *TrackStatRepository_Expecter {
	return &TrackStatRepository_Expecter{mock: &_m.Mock}
}

// IncrementTrackTotalStreams provides a mock function with given fields: ctx, trackID
func (_m *TrackStatRepository) IncrementTrackTotalStreams(ctx context.Context, trackID uuid.UUID) error {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementTrackTotalStreams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackStatRepository_IncrementTrackTotalStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementTrackTotalStreams'
type TrackStatRepository_IncrementTrackTotalStreams_Call struct {
	*mock.Call
}

// IncrementTrackTotalStreams is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
func (_e *TrackStatRepository_Expecter) IncrementTrackTotalStreams(ctx interface{}, trackID interface{}) *TrackStatRepository_IncrementTrackTotalStreams_Call {
	return &TrackStatRepository_IncrementTrackTotalStreams_Call{Call: _e.mock.On("IncrementTrackTotalStreams", ctx, trackID)}
}

func (_c *TrackStatRepository_IncrementTrackTotalStreams_Call) Run(run func(ctx context.Context, trackID uuid.UUID)) *TrackStatRepository_IncrementTrackTotalStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TrackStatRepository_IncrementTrackTotalStreams_Call) Return(_a0 error) *TrackStatRepository_IncrementTrackTotalStreams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackStatRepository_IncrementTrackTotalStreams_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *TrackStatRepository_IncrementTrackTotalStreams_Call {
	_c.Call.Return(run)
	return _c
}

// NewTrackStatRepository creates a new instance of TrackStatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackStatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackStatRepository {
	mock := &TrackStatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
