// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TrackDeletionService is an autogenerated mock type for the TrackDeletionService type
type TrackDeletionService struct {
	mock.Mock
}

type TrackDeletionService_Expecter struct {
	mock *mock.Mock
}

func (_m *TrackDeletionService) EXPECT() *TrackDeletionService_Expecter {
	return &TrackDeletionService_Expecter{mock: &_m.Mock}
}

// DeleteAllTracks provides a mock function with given fields: ctx, claims, playlistID
func (_m *TrackDeletionService) DeleteAllTracks(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllTracks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackDeletionService_DeleteAllTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllTracks'
type TrackDeletionService_DeleteAllTracks_Call struct {
	*mock.Call
}

// DeleteAllTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *TrackDeletionService_Expecter) DeleteAllTracks(ctx interface{}, claims interface{}, playlistID interface{}) *TrackDeletionService_DeleteAllTracks_Call {
	return &TrackDeletionService_DeleteAllTracks_Call{Call: _e.mock.On("DeleteAllTracks", ctx, claims, playlistID)}
}

func (_c *TrackDeletionService_DeleteAllTracks_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *TrackDeletionService_DeleteAllTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TrackDeletionService_DeleteAllTracks_Call) Return(_a0 error) *TrackDeletionService_DeleteAllTracks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackDeletionService_DeleteAllTracks_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *TrackDeletionService_DeleteAllTracks_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTracks provides a mock function with given fields: ctx, claims, playlistID
func (_m *TrackDeletionService) GetAllTracks(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID) ([]*entity.TrackMeta, error) {
	ret := _m.Called(ctx, claims, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTracks")
	}

	var r0 []*entity.TrackMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) ([]*entity.TrackMeta, error)); ok {
		return rf(ctx, claims, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) []*entity.TrackMeta); ok {
		r0 = rf(ctx, claims, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TrackMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r1 = rf(ctx, claims, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrackDeletionService_GetAllTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTracks'
type TrackDeletionService_GetAllTracks_Call struct {
	*mock.Call
}

// GetAllTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
func (_e *TrackDeletionService_Expecter) GetAllTracks(ctx interface{}, claims interface{}, playlistID interface{}) *TrackDeletionService_GetAllTracks_Call {
	return &TrackDeletionService_GetAllTracks_Call{Call: _e.mock.On("GetAllTracks", ctx, claims, playlistID)}
}

func (_c *TrackDeletionService_GetAllTracks_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID)) *TrackDeletionService_GetAllTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TrackDeletionService_GetAllTracks_Call) Return(_a0 []*entity.TrackMeta, _a1 error) *TrackDeletionService_GetAllTracks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TrackDeletionService_GetAllTracks_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) ([]*entity.TrackMeta, error)) *TrackDeletionService_GetAllTracks_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreAllTracks provides a mock function with given fields: ctx, claims, playlistID, trackIDs
func (_m *TrackDeletionService) RestoreAllTracks(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID, trackIDs []uuid.UUID) error {
	ret := _m.Called(ctx, claims, playlistID, trackIDs)

	if len(ret) == 0 {
		panic("no return value specified for RestoreAllTracks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, claims, playlistID, trackIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackDeletionService_RestoreAllTracks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreAllTracks'
type TrackDeletionService_RestoreAllTracks_Call struct {
	*mock.Call
}

// RestoreAllTracks is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - playlistID uuid.UUID
//   - trackIDs []uuid.UUID
func (_e *TrackDeletionService_Expecter) RestoreAllTracks(ctx interface{}, claims interface{}, playlistID interface{}, trackIDs interface{}) *TrackDeletionService_RestoreAllTracks_Call {
	return &TrackDeletionService_RestoreAllTracks_Call{Call: _e.mock.On("RestoreAllTracks", ctx, claims, playlistID, trackIDs)}
}

func (_c *TrackDeletionService_RestoreAllTracks_Call) Run(run func(ctx context.Context, claims *entity.Claims, playlistID uuid.UUID, trackIDs []uuid.UUID)) *TrackDeletionService_RestoreAllTracks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID), args[3].([]uuid.UUID))
	})
	return _c
}

func (_c *TrackDeletionService_RestoreAllTracks_Call) Return(_a0 error) *TrackDeletionService_RestoreAllTracks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackDeletionService_RestoreAllTracks_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID, []uuid.UUID) error) *TrackDeletionService_RestoreAllTracks_Call {
	_c.Call.Return(run)
	return _c
}

// NewTrackDeletionService creates a new instance of TrackDeletionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackDeletionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackDeletionService {
	mock := &TrackDeletionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
