// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TrackMetaRepository is an autogenerated mock type for the TrackMetaRepository type
type TrackMetaRepository struct {
	mock.Mock
}

type TrackMetaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TrackMetaRepository) EXPECT() *TrackMetaRepository_Expecter {
	return &TrackMetaRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, track
func (_m *TrackMetaRepository) Create(ctx context.Context, track *entity.TrackMeta) error {
	ret := _m.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.TrackMeta) error); ok {
		r0 = rf(ctx, track)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackMetaRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TrackMetaRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - track *entity.TrackMeta
func (_e *TrackMetaRepository_Expecter) Create(ctx interface{}, track interface{}) *TrackMetaRepository_Create_Call {
	return &TrackMetaRepository_Create_Call{Call: _e.mock.On("Create", ctx, track)}
}

func (_c *TrackMetaRepository_Create_Call) Run(run func(ctx context.Context, track *entity.TrackMeta)) *TrackMetaRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.TrackMeta))
	})
	return _c
}

func (_c *TrackMetaRepository_Create_Call) Return(_a0 error) *TrackMetaRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackMetaRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.TrackMeta) error) *TrackMetaRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, trackID
func (_m *TrackMetaRepository) Delete(ctx context.Context, trackID uuid.UUID) error {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackMetaRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TrackMetaRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
func (_e *TrackMetaRepository_Expecter) Delete(ctx interface{}, trackID interface{}) *TrackMetaRepository_Delete_Call {
	return &TrackMetaRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, trackID)}
}

func (_c *TrackMetaRepository_Delete_Call) Run(run func(ctx context.Context, trackID uuid.UUID)) *TrackMetaRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TrackMetaRepository_Delete_Call) Return(_a0 error) *TrackMetaRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackMetaRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *TrackMetaRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, trackID
func (_m *TrackMetaRepository) GetByID(ctx context.Context, trackID uuid.UUID) (*entity.TrackMeta, error) {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.TrackMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.TrackMeta, error)); ok {
		return rf(ctx, trackID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.TrackMeta); ok {
		r0 = rf(ctx, trackID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TrackMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, trackID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrackMetaRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TrackMetaRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
func (_e *TrackMetaRepository_Expecter) GetByID(ctx interface{}, trackID interface{}) *TrackMetaRepository_GetByID_Call {
	return &TrackMetaRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, trackID)}
}

func (_c *TrackMetaRepository_GetByID_Call) Run(run func(ctx context.Context, trackID uuid.UUID)) *TrackMetaRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TrackMetaRepository_GetByID_Call) Return(_a0 *entity.TrackMeta, _a1 error) *TrackMetaRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TrackMetaRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.TrackMeta, error)) *TrackMetaRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, track
func (_m *TrackMetaRepository) Update(ctx context.Context, track *entity.TrackMeta) error {
	ret := _m.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.TrackMeta) error); ok {
		r0 = rf(ctx, track)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackMetaRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TrackMetaRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - track *entity.TrackMeta
func (_e *TrackMetaRepository_Expecter) Update(ctx interface{}, track interface{}) *TrackMetaRepository_Update_Call {
	return &TrackMetaRepository_Update_Call{Call: _e.mock.On("Update", ctx, track)}
}

func (_c *TrackMetaRepository_Update_Call) Run(run func(ctx context.Context, track *entity.TrackMeta)) *TrackMetaRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.TrackMeta))
	})
	return _c
}

func (_c *TrackMetaRepository_Update_Call) Return(_a0 error) *TrackMetaRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackMetaRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.TrackMeta) error) *TrackMetaRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewTrackMetaRepository creates a new instance of TrackMetaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackMetaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackMetaRepository {
	mock := &TrackMetaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
