// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TrackMetaService is an autogenerated mock type for the TrackMetaService type
type TrackMetaService struct {
	mock.Mock
}

type TrackMetaService_Expecter struct {
	mock *mock.Mock
}

func (_m *TrackMetaService) EXPECT() *TrackMetaService_Expecter {
	return &TrackMetaService_Expecter{mock: &_m.Mock}
}

// CreateTrackMeta provides a mock function with given fields: ctx, claims, _a2
func (_m *TrackMetaService) CreateTrackMeta(ctx context.Context, claims *entity.Claims, _a2 *entity.TrackMeta) (uuid.UUID, error) {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrackMeta")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.TrackMeta) (uuid.UUID, error)); ok {
		return rf(ctx, claims, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.TrackMeta) uuid.UUID); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Claims, *entity.TrackMeta) error); ok {
		r1 = rf(ctx, claims, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrackMetaService_CreateTrackMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTrackMeta'
type TrackMetaService_CreateTrackMeta_Call struct {
	*mock.Call
}

// CreateTrackMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.TrackMeta
func (_e *TrackMetaService_Expecter) CreateTrackMeta(ctx interface{}, claims interface{}, _a2 interface{}) *TrackMetaService_CreateTrackMeta_Call {
	return &TrackMetaService_CreateTrackMeta_Call{Call: _e.mock.On("CreateTrackMeta", ctx, claims, _a2)}
}

func (_c *TrackMetaService_CreateTrackMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.TrackMeta)) *TrackMetaService_CreateTrackMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.TrackMeta))
	})
	return _c
}

func (_c *TrackMetaService_CreateTrackMeta_Call) Return(_a0 uuid.UUID, _a1 error) *TrackMetaService_CreateTrackMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TrackMetaService_CreateTrackMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.TrackMeta) (uuid.UUID, error)) *TrackMetaService_CreateTrackMeta_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTrackMeta provides a mock function with given fields: ctx, claims, trackID
func (_m *TrackMetaService) DeleteTrackMeta(ctx context.Context, claims *entity.Claims, trackID uuid.UUID) error {
	ret := _m.Called(ctx, claims, trackID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrackMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, uuid.UUID) error); ok {
		r0 = rf(ctx, claims, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackMetaService_DeleteTrackMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrackMeta'
type TrackMetaService_DeleteTrackMeta_Call struct {
	*mock.Call
}

// DeleteTrackMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - trackID uuid.UUID
func (_e *TrackMetaService_Expecter) DeleteTrackMeta(ctx interface{}, claims interface{}, trackID interface{}) *TrackMetaService_DeleteTrackMeta_Call {
	return &TrackMetaService_DeleteTrackMeta_Call{Call: _e.mock.On("DeleteTrackMeta", ctx, claims, trackID)}
}

func (_c *TrackMetaService_DeleteTrackMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, trackID uuid.UUID)) *TrackMetaService_DeleteTrackMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TrackMetaService_DeleteTrackMeta_Call) Return(_a0 error) *TrackMetaService_DeleteTrackMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackMetaService_DeleteTrackMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, uuid.UUID) error) *TrackMetaService_DeleteTrackMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrackMeta provides a mock function with given fields: ctx, trackID
func (_m *TrackMetaService) GetTrackMeta(ctx context.Context, trackID uuid.UUID) (*entity.TrackMeta, error) {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackMeta")
	}

	var r0 *entity.TrackMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.TrackMeta, error)); ok {
		return rf(ctx, trackID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.TrackMeta); ok {
		r0 = rf(ctx, trackID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TrackMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, trackID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrackMetaService_GetTrackMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrackMeta'
type TrackMetaService_GetTrackMeta_Call struct {
	*mock.Call
}

// GetTrackMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
func (_e *TrackMetaService_Expecter) GetTrackMeta(ctx interface{}, trackID interface{}) *TrackMetaService_GetTrackMeta_Call {
	return &TrackMetaService_GetTrackMeta_Call{Call: _e.mock.On("GetTrackMeta", ctx, trackID)}
}

func (_c *TrackMetaService_GetTrackMeta_Call) Run(run func(ctx context.Context, trackID uuid.UUID)) *TrackMetaService_GetTrackMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TrackMetaService_GetTrackMeta_Call) Return(_a0 *entity.TrackMeta, _a1 error) *TrackMetaService_GetTrackMeta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TrackMetaService_GetTrackMeta_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.TrackMeta, error)) *TrackMetaService_GetTrackMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTrackMeta provides a mock function with given fields: ctx, claims, _a2
func (_m *TrackMetaService) UpdateTrackMeta(ctx context.Context, claims *entity.Claims, _a2 *entity.TrackMeta) error {
	ret := _m.Called(ctx, claims, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTrackMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Claims, *entity.TrackMeta) error); ok {
		r0 = rf(ctx, claims, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackMetaService_UpdateTrackMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTrackMeta'
type TrackMetaService_UpdateTrackMeta_Call struct {
	*mock.Call
}

// UpdateTrackMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - claims *entity.Claims
//   - _a2 *entity.TrackMeta
func (_e *TrackMetaService_Expecter) UpdateTrackMeta(ctx interface{}, claims interface{}, _a2 interface{}) *TrackMetaService_UpdateTrackMeta_Call {
	return &TrackMetaService_UpdateTrackMeta_Call{Call: _e.mock.On("UpdateTrackMeta", ctx, claims, _a2)}
}

func (_c *TrackMetaService_UpdateTrackMeta_Call) Run(run func(ctx context.Context, claims *entity.Claims, _a2 *entity.TrackMeta)) *TrackMetaService_UpdateTrackMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Claims), args[2].(*entity.TrackMeta))
	})
	return _c
}

func (_c *TrackMetaService_UpdateTrackMeta_Call) Return(_a0 error) *TrackMetaService_UpdateTrackMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackMetaService_UpdateTrackMeta_Call) RunAndReturn(run func(context.Context, *entity.Claims, *entity.TrackMeta) error) *TrackMetaService_UpdateTrackMeta_Call {
	_c.Call.Return(run)
	return _c
}

// NewTrackMetaService creates a new instance of TrackMetaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackMetaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackMetaService {
	mock := &TrackMetaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
