// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TrackSegmentRepository is an autogenerated mock type for the TrackSegmentRepository type
type TrackSegmentRepository struct {
	mock.Mock
}

type TrackSegmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TrackSegmentRepository) EXPECT() *TrackSegmentRepository_Expecter {
	return &TrackSegmentRepository_Expecter{mock: &_m.Mock}
}

// CreateSegments provides a mock function with given fields: ctx, trackID, segments
func (_m *TrackSegmentRepository) CreateSegments(ctx context.Context, trackID uuid.UUID, segments []*entity.Segment) error {
	ret := _m.Called(ctx, trackID, segments)

	if len(ret) == 0 {
		panic("no return value specified for CreateSegments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []*entity.Segment) error); ok {
		r0 = rf(ctx, trackID, segments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackSegmentRepository_CreateSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSegments'
type TrackSegmentRepository_CreateSegments_Call struct {
	*mock.Call
}

// CreateSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
//   - segments []*entity.Segment
func (_e *TrackSegmentRepository_Expecter) CreateSegments(ctx interface{}, trackID interface{}, segments interface{}) *TrackSegmentRepository_CreateSegments_Call {
	return &TrackSegmentRepository_CreateSegments_Call{Call: _e.mock.On("CreateSegments", ctx, trackID, segments)}
}

func (_c *TrackSegmentRepository_CreateSegments_Call) Run(run func(ctx context.Context, trackID uuid.UUID, segments []*entity.Segment)) *TrackSegmentRepository_CreateSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]*entity.Segment))
	})
	return _c
}

func (_c *TrackSegmentRepository_CreateSegments_Call) Return(_a0 error) *TrackSegmentRepository_CreateSegments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackSegmentRepository_CreateSegments_Call) RunAndReturn(run func(context.Context, uuid.UUID, []*entity.Segment) error) *TrackSegmentRepository_CreateSegments_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSegments provides a mock function with given fields: ctx, trackID
func (_m *TrackSegmentRepository) DeleteSegments(ctx context.Context, trackID uuid.UUID) error {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSegments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackSegmentRepository_DeleteSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSegments'
type TrackSegmentRepository_DeleteSegments_Call struct {
	*mock.Call
}

// DeleteSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
func (_e *TrackSegmentRepository_Expecter) DeleteSegments(ctx interface{}, trackID interface{}) *TrackSegmentRepository_DeleteSegments_Call {
	return &TrackSegmentRepository_DeleteSegments_Call{Call: _e.mock.On("DeleteSegments", ctx, trackID)}
}

func (_c *TrackSegmentRepository_DeleteSegments_Call) Run(run func(ctx context.Context, trackID uuid.UUID)) *TrackSegmentRepository_DeleteSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TrackSegmentRepository_DeleteSegments_Call) Return(_a0 error) *TrackSegmentRepository_DeleteSegments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackSegmentRepository_DeleteSegments_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *TrackSegmentRepository_DeleteSegments_Call {
	_c.Call.Return(run)
	return _c
}

// GetSegments provides a mock function with given fields: ctx, trackID
func (_m *TrackSegmentRepository) GetSegments(ctx context.Context, trackID uuid.UUID) ([]*entity.Segment, error) {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for GetSegments")
	}

	var r0 []*entity.Segment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Segment, error)); ok {
		return rf(ctx, trackID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Segment); ok {
		r0 = rf(ctx, trackID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Segment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, trackID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrackSegmentRepository_GetSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSegments'
type TrackSegmentRepository_GetSegments_Call struct {
	*mock.Call
}

// GetSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
func (_e *TrackSegmentRepository_Expecter) GetSegments(ctx interface{}, trackID interface{}) *TrackSegmentRepository_GetSegments_Call {
	return &TrackSegmentRepository_GetSegments_Call{Call: _e.mock.On("GetSegments", ctx, trackID)}
}

func (_c *TrackSegmentRepository_GetSegments_Call) Run(run func(ctx context.Context, trackID uuid.UUID)) *TrackSegmentRepository_GetSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TrackSegmentRepository_GetSegments_Call) Return(_a0 []*entity.Segment, _a1 error) *TrackSegmentRepository_GetSegments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TrackSegmentRepository_GetSegments_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Segment, error)) *TrackSegmentRepository_GetSegments_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementTotalStreams provides a mock function with given fields: ctx, trackID, segmentsIdxs
func (_m *TrackSegmentRepository) IncrementTotalStreams(ctx context.Context, trackID uuid.UUID, segmentsIdxs []int) error {
	ret := _m.Called(ctx, trackID, segmentsIdxs)

	if len(ret) == 0 {
		panic("no return value specified for IncrementTotalStreams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []int) error); ok {
		r0 = rf(ctx, trackID, segmentsIdxs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrackSegmentRepository_IncrementTotalStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementTotalStreams'
type TrackSegmentRepository_IncrementTotalStreams_Call struct {
	*mock.Call
}

// IncrementTotalStreams is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID uuid.UUID
//   - segmentsIdxs []int
func (_e *TrackSegmentRepository_Expecter) IncrementTotalStreams(ctx interface{}, trackID interface{}, segmentsIdxs interface{}) *TrackSegmentRepository_IncrementTotalStreams_Call {
	return &TrackSegmentRepository_IncrementTotalStreams_Call{Call: _e.mock.On("IncrementTotalStreams", ctx, trackID, segmentsIdxs)}
}

func (_c *TrackSegmentRepository_IncrementTotalStreams_Call) Run(run func(ctx context.Context, trackID uuid.UUID, segmentsIdxs []int)) *TrackSegmentRepository_IncrementTotalStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]int))
	})
	return _c
}

func (_c *TrackSegmentRepository_IncrementTotalStreams_Call) Return(_a0 error) *TrackSegmentRepository_IncrementTotalStreams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TrackSegmentRepository_IncrementTotalStreams_Call) RunAndReturn(run func(context.Context, uuid.UUID, []int) error) *TrackSegmentRepository_IncrementTotalStreams_Call {
	_c.Call.Return(run)
	return _c
}

// NewTrackSegmentRepository creates a new instance of TrackSegmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackSegmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackSegmentRepository {
	mock := &TrackSegmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
