// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/hahaclassic/orpheon/backend/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserCreatorService is an autogenerated mock type for the UserCreatorService type
type UserCreatorService struct {
	mock.Mock
}

type UserCreatorService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserCreatorService) EXPECT() *UserCreatorService_Expecter {
	return &UserCreatorService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, info
func (_m *UserCreatorService) CreateUser(ctx context.Context, info *entity.UserInfo) (uuid.UUID, error) {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserInfo) (uuid.UUID, error)); ok {
		return rf(ctx, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserInfo) uuid.UUID); ok {
		r0 = rf(ctx, info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserInfo) error); ok {
		r1 = rf(ctx, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserCreatorService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserCreatorService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - info *entity.UserInfo
func (_e *UserCreatorService_Expecter) CreateUser(ctx interface{}, info interface{}) *UserCreatorService_CreateUser_Call {
	return &UserCreatorService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, info)}
}

func (_c *UserCreatorService_CreateUser_Call) Run(run func(ctx context.Context, info *entity.UserInfo)) *UserCreatorService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserInfo))
	})
	return _c
}

func (_c *UserCreatorService_CreateUser_Call) Return(_a0 uuid.UUID, _a1 error) *UserCreatorService_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserCreatorService_CreateUser_Call) RunAndReturn(run func(context.Context, *entity.UserInfo) (uuid.UUID, error)) *UserCreatorService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserCreatorService creates a new instance of UserCreatorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCreatorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCreatorService {
	mock := &UserCreatorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
